import {v,ConvexError} from 'convex/values';
import {action,query,mutation,internalAction,internalQuery,internalMutation} from './_generated/server';
import {internal} from './_generated/api';
import type {Id} from './_generated/dataModel';
import {requireCustomer,requireSigned} from './access';
import {canReadFile} from './customerFiles';
import {sealToken,openToken,stateHash,socialCaption} from '../shared/meta';
import {base64url,bufferRateLimits,pkceChallenge,bufferAccountQuery,bufferChannelsQuery,bufferCreateQuery,bufferVideoInput,supportedBufferChannel,type BufferChannel} from '../shared/buffer';
class BufferResponseError extends Error {constructor(public detail:string){super('Buffer request failed')}}
function providerDetail(value:unknown,token?:string){const text=typeof value==='string'?value:JSON.stringify(value);return token?text.split(token).join('[REDACTED]'):text;}
export const channelValidator=v.object({id:v.string(),name:v.string(),service:v.string(),organizationId:v.string(),type:v.string(),isDisconnected:v.boolean(),isLocked:v.boolean()});
function config(){const clientId=process.env.BUFFER_CLIENT_ID,key=process.env.META_TOKEN_KEY,site=process.env.CONVEX_SITE_URL;if(!clientId||!key||!site)throw new ConvexError('ربط Buffer ينتظر تفعيل تطبيق مشهد من الإدارة.');return {clientId,key,redirect:site+'/buffer/callback',secret:process.env.BUFFER_CLIENT_SECRET};}
type Audit={ctx:import('./_generated/server').ActionCtx;subject:string;operation:string;postId?:Id<'bufferPosts'>};
async function measuredFetch(url:string,init:RequestInit,audit?:Audit){
 const id=audit?await audit.ctx.runMutation(internal.buffer.auditStart,{subject:audit.subject,operation:audit.operation,postId:audit.postId,endpoint:url.includes('/token')?'oauth':'graphql'}):null;
 let response:Response|undefined;
 try {response=await fetch(url,init);return response;}
 finally {if(audit&&id)await audit.ctx.runMutation(internal.buffer.auditFinish,{id,status:response?.status,failed:!response||!response.ok,limits:bufferRateLimits(response?.headers.get('ratelimit')??null)});}
}
export const auditStart=internalMutation({args:{subject:v.string(),postId:v.optional(v.id('bufferPosts')),operation:v.string(),endpoint:v.union(v.literal('graphql'),v.literal('oauth'))},handler:async(ctx,a)=>{if(a.postId){const p=await ctx.db.get(a.postId);if(!p||p.subject!==a.subject)throw new Error('Invalid audit owner');const field=a.endpoint==='graphql'?'apiRequests':'tokenRequests';await ctx.db.patch(p._id,{[field]:(p[field]??0)+1});}return ctx.db.insert('bufferRequests',{...a,startedAt:Date.now()});}});
export const auditFinish=internalMutation({args:{id:v.id('bufferRequests'),status:v.optional(v.number()),failed:v.boolean(),limits:v.array(v.object({policy:v.string(),remaining:v.number(),resetSeconds:v.number()}))},handler:async(ctx,{id,...a})=>{await ctx.db.patch(id,{...a,endedAt:Date.now()});}});
export const usage=query({args:{},handler:async ctx=>{const u=await requireCustomer(ctx);return ctx.db.query('bufferRequests').withIndex('by_subject',q=>q.eq('subject',u.subject)).order('desc').take(100);}});
async function graph<T>(token:string,query:string,variables:unknown={},audit?:Audit):Promise<T>{const r=await measuredFetch('https://api.buffer.com',{method:'POST',headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json'},body:JSON.stringify({query,variables}),signal:AbortSignal.timeout(30000)},audit);const text=await r.text();let body:{data?:T;errors?:unknown[]};try{body=JSON.parse(text)}catch{throw new BufferResponseError(providerDetail(text,token))}if(!r.ok||body.errors?.length||!body.data)throw new BufferResponseError(providerDetail(body.errors??text,token));return body.data;}
async function exchange(fields:Record<string,string>,audit?:Audit){const c=config(),r=await measuredFetch('https://auth.buffer.com/token',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({...fields,client_id:c.clientId,...(c.secret?{client_secret:c.secret}:{})}),signal:AbortSignal.timeout(30000)},audit);const t=await r.json() as {access_token?:string;refresh_token?:string;expires_in?:number;scope?:string};if(!r.ok||!t.access_token||!t.refresh_token||!Number.isFinite(t.expires_in)||t.expires_in!<=0)throw new Error('Buffer authorization failed');return {access:t.access_token,refresh:t.refresh_token,expires:Date.now()+t.expires_in!*1000};}
async function channels(token:string,audit?:Audit){const account=await graph<{account:{id:string;organizations:{id:string}[]}}>(token,bufferAccountQuery,{},audit?{...audit,operation:'account'}:undefined),list:BufferChannel[]=[];for(const org of account.account.organizations.slice(0,50)){const data=await graph<{channels:BufferChannel[]}>(token,bufferChannelsQuery,{input:{organizationId:org.id}},audit?{...audit,operation:'channels'}:undefined);list.push(...data.channels.filter(supportedBufferChannel));}return {accountId:account.account.id,channels:list};}
export const state=query({args:{},handler:async ctx=>{const u=await requireCustomer(ctx),row=await ctx.db.query('bufferConnections').withIndex('by_subject',q=>q.eq('subject',u.subject)).unique();let configured=true;try{config()}catch{configured=false}return {configured,connected:!!row,needsReconnect:!!row?.refreshLock&&row.refreshLock.until<Date.now(),channels:row?.channels??[],posts:(await ctx.db.query('bufferPosts').withIndex('by_subject',q=>q.eq('subject',u.subject)).order('desc').take(20)).map(p=>({_id:p._id,stage:p.stage,providerId:p.providerId,createdAt:p.createdAt,dueAt:p.dueAt,channelId:p.channelId,caption:p.caption,storageId:p.storageId,apiRequests:p.apiRequests??0,tokenRequests:p.tokenRequests??0,providerStatus:p.providerStatus,providerError:p.providerError,externalLink:p.externalLink,history:p.history??[]}))};}});
export const authStore=internalMutation({args:{subject:v.string(),hash:v.string(),origin:v.string(),verifier:v.string()},handler:async(ctx,a)=>{for(const old of await ctx.db.query('bufferAuth').withIndex('by_subject',q=>q.eq('subject',a.subject)).collect())await ctx.db.delete(old._id);await ctx.db.insert('bufferAuth',{...a,expiresAt:Date.now()+600000});}});
export const authTake=internalMutation({args:{hash:v.string()},handler:async(ctx,a)=>{const row=await ctx.db.query('bufferAuth').withIndex('by_hash',q=>q.eq('hash',a.hash)).unique();if(!row)return null;await ctx.db.delete(row._id);return row.expiresAt>Date.now()?row:null;}});
export const begin=action({args:{origin:v.string()},handler:async(ctx,a):Promise<string>=>{const u=await requireSigned(ctx);await ctx.runQuery(internal.access.customerAllowed,{});const c=config();if(!(process.env.CLIENT_ORIGINS??'').split(',').map(s=>s.trim()).includes(a.origin)||new URL(a.origin).origin!==a.origin)throw new ConvexError('عنوان العودة غير مسموح.');const state=base64url(crypto.getRandomValues(new Uint8Array(32))),verifier=base64url(crypto.getRandomValues(new Uint8Array(32)));await ctx.runMutation(internal.buffer.authStore,{subject:u.subject,hash:await stateHash(state),origin:a.origin,verifier:await sealToken(verifier,c.key,u.subject)});const url=new URL('https://auth.buffer.com/auth');for(const [k,value] of Object.entries({client_id:c.clientId,redirect_uri:c.redirect,response_type:'code',scope:'account:read posts:read posts:write offline_access',state,code_challenge:await pkceChallenge(verifier),code_challenge_method:'S256',prompt:'consent'}))url.searchParams.set(k,value);return url.href;}});
export const save=internalMutation({args:{subject:v.string(),accountId:v.string(),access:v.string(),refresh:v.string(),expires:v.number(),channels:v.array(channelValidator)},handler:async(ctx,a)=>{const old=await ctx.db.query('bufferConnections').withIndex('by_subject',q=>q.eq('subject',a.subject)).unique();if((await ctx.db.query('bufferPosts').withIndex('by_subject',q=>q.eq('subject',a.subject)).collect()).some(p=>['preparing','sending'].includes(p.stage)))throw new ConvexError('انتظر انتهاء إرسال الفيديو.');const values={...a,revision:crypto.randomUUID(),connectedAt:Date.now(),refreshLock:undefined};if(old)await ctx.db.patch(old._id,values);else await ctx.db.insert('bufferConnections',values);}});
export const callback=internalAction({args:{state:v.string(),code:v.optional(v.string())},handler:async(ctx,a):Promise<string>=>{const session=await ctx.runMutation(internal.buffer.authTake,{hash:await stateHash(a.state)});if(!session)return 'https://iraqaistudio.com/?buffer=expired';const back=new URL(session.origin);back.searchParams.set('buffer',a.code?'failed':'cancelled');if(!a.code)return back.href;try{const c=config(),t=await exchange({grant_type:'authorization_code',code:a.code,redirect_uri:c.redirect,code_verifier:await openToken(session.verifier,c.key,session.subject)},{ctx,subject:session.subject,operation:'authorization'}),data=await channels(t.access,{ctx,subject:session.subject,operation:'connect'});await ctx.runMutation(internal.buffer.save,{subject:session.subject,...data,access:await sealToken(t.access,c.key,session.subject),refresh:await sealToken(t.refresh,c.key,session.subject),expires:t.expires});back.searchParams.set('buffer',data.channels.length?'connected':'no_channels');}catch{/* Never expose OAuth codes, tokens, or raw provider errors. */}return back.href;}});
export const connection=internalQuery({args:{subject:v.string()},handler:(ctx,a)=>ctx.db.query('bufferConnections').withIndex('by_subject',q=>q.eq('subject',a.subject)).unique()});
export const lockRefresh=internalMutation({args:{subject:v.string(),revision:v.string(),fence:v.string()},handler:async(ctx,a)=>{const r=await ctx.db.query('bufferConnections').withIndex('by_subject',q=>q.eq('subject',a.subject)).unique();if(!r||r.revision!==a.revision||r.refreshLock)return false;await ctx.db.patch(r._id,{refreshLock:{fence:a.fence,until:Date.now()+45000}});return true;}});
export const finishRefresh=internalMutation({args:{subject:v.string(),revision:v.string(),fence:v.string(),access:v.string(),refresh:v.string(),expires:v.number()},handler:async(ctx,a)=>{const r=await ctx.db.query('bufferConnections').withIndex('by_subject',q=>q.eq('subject',a.subject)).unique();if(!r||r.revision!==a.revision||r.refreshLock?.fence!==a.fence)throw new Error('Connection changed');await ctx.db.patch(r._id,{access:a.access,refresh:a.refresh,expires:a.expires,refreshLock:undefined});}});
async function accessToken(ctx:import('./_generated/server').ActionCtx,subject:string,postId?:Id<'bufferPosts'>){const r=await ctx.runQuery(internal.buffer.connection,{subject});if(!r)throw new ConvexError('اربط Buffer أولًا.');const c=config();if(r.refreshLock)throw new ConvexError(r.refreshLock.until>Date.now()?'جارٍ تحديث الربط؛ حاول بعد لحظات.':'حدّث ربط Buffer من الإعدادات.');if(r.expires>Date.now()+60000)return {token:await openToken(r.access,c.key,subject),connection:r};const fence=crypto.randomUUID();if(!await ctx.runMutation(internal.buffer.lockRefresh,{subject,revision:r.revision,fence}))throw new ConvexError('جارٍ تحديث الربط؛ حاول بعد لحظات.');try{const t=await exchange({grant_type:'refresh_token',refresh_token:await openToken(r.refresh,c.key,subject)},{ctx,subject,postId,operation:'refresh-token'});await ctx.runMutation(internal.buffer.finishRefresh,{subject,revision:r.revision,fence,access:await sealToken(t.access,c.key,subject),refresh:await sealToken(t.refresh,c.key,subject),expires:t.expires});return {token:t.access,connection:r};}catch{throw new ConvexError('تعذر تحديث التصريح؛ أعد ربط Buffer من الإعدادات.');}}
export const sync=action({args:{},handler:async(ctx):Promise<void>=>{const u=await requireSigned(ctx);await ctx.runQuery(internal.access.customerAllowed,{});const {token,connection}=await accessToken(ctx,u.subject),data=await channels(token,{ctx,subject:u.subject,operation:'sync'});await ctx.runMutation(internal.buffer.updateChannels,{subject:u.subject,revision:connection.revision,channels:data.channels});}});
export const updateChannels=internalMutation({args:{subject:v.string(),revision:v.string(),channels:v.array(channelValidator)},handler:async(ctx,a)=>{const r=await ctx.db.query('bufferConnections').withIndex('by_subject',q=>q.eq('subject',a.subject)).unique();if(r?.revision===a.revision)await ctx.db.patch(r._id,{channels:a.channels});}});
export const disconnect=mutation({args:{},handler:async ctx=>{const u=await requireCustomer(ctx);if((await ctx.db.query('bufferPosts').withIndex('by_subject',q=>q.eq('subject',u.subject)).collect()).some(p=>['preparing','sending'].includes(p.stage)))throw new ConvexError('انتظر انتهاء إرسال الفيديو.');for(const r of await ctx.db.query('bufferConnections').withIndex('by_subject',q=>q.eq('subject',u.subject)).collect())await ctx.db.delete(r._id);for(const r of await ctx.db.query('bufferAuth').withIndex('by_subject',q=>q.eq('subject',u.subject)).collect())await ctx.db.delete(r._id);}});
export const claim=internalMutation({args:{key:v.string(),channelId:v.string(),storageId:v.id('_storage'),caption:v.string(),dueAt:v.optional(v.number())},handler:async(ctx,a)=>{const u=await requireCustomer(ctx);if(!/^[\w-]{16,100}$/.test(a.key))throw new ConvexError('طلب غير صالح.');const key=u.subject+':'+a.key,caption=socialCaption(a.caption),old=await ctx.db.query('bufferPosts').withIndex('by_key',q=>q.eq('key',key)).unique();if(old){if(old.channelId!==a.channelId||old.storageId!==a.storageId||old.caption!==caption||old.dueAt!==a.dueAt)throw new ConvexError('تغير طلب النشر.');return {id:old._id,created:false};}if(a.dueAt!==undefined&&(!Number.isFinite(a.dueAt)||a.dueAt<Date.now()+300000||a.dueAt>Date.now()+30*86400000))throw new ConvexError('اختر موعدًا بعد 5 دقائق على الأقل وخلال 30 يومًا.');const c=await ctx.db.query('bufferConnections').withIndex('by_subject',q=>q.eq('subject',u.subject)).unique();if(!c?.channels.some(channel=>channel.id===a.channelId&&supportedBufferChannel(channel)))throw new ConvexError('الحساب غير متاح.');if(!await canReadFile(ctx,u.subject,a.storageId))throw new ConvexError('الفيديو لا يخص حسابك.');const file=await ctx.db.query('uploads').withIndex('by_storage',q=>q.eq('storageId',a.storageId)).unique();if(file?.kind!=='video'||file.type!=='video/mp4')throw new ConvexError('اختر فيديو MP4.');if((await ctx.db.query('bufferPosts').withIndex('by_subject',q=>q.eq('subject',u.subject)).collect()).some(p=>['preparing','sending'].includes(p.stage)))throw new ConvexError('انتظر انتهاء إرسال الفيديو الحالي.');const id=await ctx.db.insert('bufferPosts',{...a,key,caption,subject:u.subject,revision:c.revision,stage:'preparing',createdAt:Date.now(),apiRequests:0,tokenRequests:0,history:[{status:'created',at:Date.now()}]});return {id,created:true};}});
export const publish=action({args:{key:v.string(),channelId:v.string(),storageId:v.id('_storage'),caption:v.string(),dueAt:v.optional(v.number()),confirmed:v.boolean()},handler:async(ctx,a):Promise<Id<'bufferPosts'>>=>{if(!a.confirmed)throw new ConvexError('راجع الفيديو والوصف ووافق على النشر أولًا.');config();const {confirmed,...input}=a;void confirmed;const job=await ctx.runMutation(internal.buffer.claim,input);if(job.created)await ctx.scheduler.runAfter(0,internal.buffer.send,{id:job.id});return job.id;}});
export const takeJob=internalMutation({args:{id:v.id('bufferPosts')},handler:async(ctx,a)=>{const p=await ctx.db.get(a.id);if(!p||p.stage!=='preparing')return null;await ctx.db.patch(p._id,{stage:'sending'});return p;}});
export const ownedPost=internalQuery({args:{id:v.id('bufferPosts')},handler:async(ctx,a)=>{const u=await requireCustomer(ctx),p=await ctx.db.get(a.id);if(!p||p.subject!==u.subject)throw new ConvexError('الطلب غير متاح.');return p;}});
export const recordError=internalMutation({args:{id:v.id('bufferPosts'),detail:v.string()},handler:async(ctx,a)=>{await ctx.db.patch(a.id,{providerError:a.detail});}});
export const updateStatus=internalMutation({args:{id:v.id('bufferPosts'),providerId:v.string(),stage:v.union(v.literal('accepted'),v.literal('published'),v.literal('failed')),providerStatus:v.string(),providerError:v.optional(v.string()),externalLink:v.optional(v.string())},handler:async(ctx,a)=>{const p=await ctx.db.get(a.id);if(p?.stage==='accepted'&&p.providerId===a.providerId)await ctx.db.patch(a.id,{stage:a.stage,providerStatus:a.providerStatus,providerError:a.providerError,externalLink:a.externalLink,history:[...(p.history??[]),{status:a.providerStatus,at:Date.now()}].slice(-30)});}});
export const refreshPost=action({args:{id:v.id('bufferPosts')},handler:async(ctx,a):Promise<void>=>{const p=await ctx.runQuery(internal.buffer.ownedPost,a);if(p.stage!=='accepted'||!p.providerId)return;const {token,connection}=await accessToken(ctx,p.subject,p._id);if(connection.revision!==p.revision)throw new ConvexError('تغير حساب Buffer. راجع الطلب من لوحة Buffer.');try{const data=await graph<{post:{id:string;status:string;channelId:string;externalLink?:string;error?:{message:string;rawError?:string}}}>(token,'query Status($input: PostInput!){post(input:$input){id status channelId externalLink error{message rawError}}}',{input:{id:p.providerId}},{ctx,subject:p.subject,postId:p._id,operation:'status'});if(data.post.id!==p.providerId||data.post.channelId!==p.channelId)throw new Error('Wrong post');await ctx.runMutation(internal.buffer.updateStatus,{id:p._id,providerId:p.providerId,stage:data.post.status==='sent'?'published':data.post.status==='error'?'failed':'accepted',providerStatus:data.post.status,externalLink:data.post.externalLink??undefined,providerError:data.post.error?providerDetail(data.post.error,token):undefined});}catch(e){if(e instanceof BufferResponseError)await ctx.runMutation(internal.buffer.recordError,{id:p._id,detail:e.detail});throw new ConvexError('تعذر تحديث الحالة؛ راجع الطلب في Buffer.');}}});
export const phase=internalMutation({args:{id:v.id('bufferPosts'),stage:v.union(v.literal('accepted'),v.literal('published'),v.literal('failed'),v.literal('uncertain')),providerId:v.optional(v.string()),providerStatus:v.optional(v.string()),providerError:v.optional(v.string()),externalLink:v.optional(v.string())},handler:async(ctx,a)=>{const r=await ctx.db.get(a.id);if(r?.stage==='sending')await ctx.db.patch(a.id,{stage:a.stage,providerId:a.providerId,providerStatus:a.providerStatus,providerError:a.providerError,externalLink:a.externalLink,history:[...(r.history??[]),{status:a.providerStatus??a.stage,at:Date.now()}]});}});
export const send=internalAction({args:{id:v.id('bufferPosts')},handler:async(ctx,a)=>{const job=await ctx.runMutation(internal.buffer.takeJob,a);if(!job)return;let submitted=false;try{const {token,connection}=await accessToken(ctx,job.subject,job._id),channel=connection.channels.find(c=>c.id===job.channelId);if(connection.revision!==job.revision||!channel)throw new Error('Connection changed');const live=await graph<{channel:BufferChannel}>(token,'query Channel($input: ChannelInput!){channel(input:$input){id name service organizationId type isDisconnected isLocked}}',{input:{id:channel.id}},{ctx,subject:job.subject,postId:job._id,operation:'preflight'});if(!supportedBufferChannel(live.channel))throw new Error('Channel unavailable');const url=await ctx.storage.getUrl(job.storageId);if(!url)throw new Error('Video unavailable');if(job.dueAt!==undefined&&job.dueAt<Date.now()+30000)throw new Error('Schedule elapsed');submitted=true;const result=await graph<{createPost:{post?:{id:string;status:string;externalLink?:string};message?:string}}>(token,bufferCreateQuery,{input:bufferVideoInput(live.channel,url,job.caption,job.dueAt)},{ctx,subject:job.subject,postId:job._id,operation:'create-post'});if(!result.createPost.post){await ctx.runMutation(internal.buffer.phase,{...a,stage:'failed',providerStatus:'error',providerError:providerDetail(result.createPost.message??'No post returned',token)});return;}const p=result.createPost.post;await ctx.runMutation(internal.buffer.phase,{...a,stage:p.status==='sent'?'published':p.status==='error'?'failed':'accepted',providerId:p.id,providerStatus:p.status,externalLink:p.externalLink??undefined});}catch(e){await ctx.runMutation(internal.buffer.phase,{...a,stage:submitted?'uncertain':'failed',providerError:e instanceof BufferResponseError?e.detail:undefined});}}});
