import {beforeEach,describe,it,expect,vi} from 'vitest';
import {convexTest} from 'convex-test';
import schema from './schema';
import {api,internal} from './_generated/api';
import {availableDuration,validateEdit,type EditSettings} from '../shared/editing';
const modules=import.meta.glob('./**/*.{ts,js}'),owner={subject:'owner',issuer:'https://owner.clerk.accounts.dev'};
beforeEach(()=>{vi.stubEnv('OWNER_SUBJECT',owner.subject);vi.stubEnv('CLERK_JWT_ISSUER_DOMAIN',owner.issuer);vi.stubEnv('WORKER_KEY_SHA256','');});
async function fixture(){const t=convexTest(schema,modules),u=t.withIdentity(owner);const requestId=await u.mutation(api.requests.save,{key:'edit-fixture',form:{name:'قهوة بغداد',address:'بغداد الكرادة',phone:'07700000000',products:'قهوة',prompt:'Coffee',instructions:'',model:'Omni Flash',aspect:'9:16',duration:6,dialect:'العراقية'},clipCount:1,referenceIds:[],submit:true});const storageId=await t.run(ctx=>ctx.storage.store(new Blob(['source contract fixture'],{type:'video/mp4'})));await t.run(ctx=>ctx.db.patch(requestId,{videoId:storageId,results:[{assetId:'known',storageId,duration:6,width:360,height:640}]}));const settings:EditSettings={clips:[{storageId,start:0,end:6}],duration:6,transition:0,fit:'contain',width:720,logo:{enabled:false,position:'top-right',size:18,start:0,end:6},text:{name:true,address:true,phone:true,position:'bottom',color:'#ffffff',background:'#171523'}};return {t,u,requestId,settings,storageId};}
describe('independent montage queue',()=>{
 it('retries a failed export from the owner UI without changing generation or losing its version',async()=>{const {t,u,requestId,settings}=await fixture();const exportId=await u.mutation(api.editing.enqueue,{requestId,settings,key:'retry-owner-ui'});await t.run(ctx=>ctx.db.patch(exportId,{status:'failed',error:'Upload failed'}));await expect(t.mutation(api.editing.retry,{exportId})).rejects.toThrow();await u.mutation(api.editing.retry,{exportId});expect(await t.query(internal.editing.pending,{})).toBe(exportId);expect((await u.query(api.requests.list))[0].runner).toBeUndefined();});
 it('allows an old JPEG logo when disabled, and requires PNG/WebP when enabled',async()=>{const {t,u,requestId,settings}=await fixture();const bytes=new Uint8Array([255,216,255,224,0,16,74,70,73,70,0]),hash=Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',bytes))).map(n=>n.toString(16).padStart(2,'0')).join(''),key=`image:${hash}`;await u.mutation(api.files.begin,{key,kind:'image',name:'old.jpg',type:'image/jpeg',size:bytes.length});const logoId=await t.run(ctx=>ctx.storage.store(new Blob([bytes],{type:'image/jpeg'})));await u.action(api.files.finish,{key,storageId:logoId});await u.mutation(api.editing.save,{requestId,settings,logoId});await expect(u.mutation(api.editing.save,{requestId,settings:{...settings,logo:{...settings.logo,enabled:true}},logoId})).rejects.toThrow('PNG');});
 it('protects owner endpoints and all montage HTTP operations',async()=>{const {t,requestId,settings}=await fixture();await expect(t.query(api.editing.state,{requestId})).rejects.toThrow();await expect(t.mutation(api.editing.enqueue,{requestId,settings,key:'anonymous'})).rejects.toThrow();for(const op of ['editPending','editClaim','editHeartbeat','editProgress','editFile','editUpload','editFinish'])expect((await t.fetch('/runner',{method:'POST',body:JSON.stringify({op,args:{}})})).status).toBe(401);});
 it('deduplicates submission, snapshots settings and phone, and retains original',async()=>{const {t,u,requestId,settings,storageId}=await fixture();const args={requestId,settings,key:'same-click'};const id=await u.mutation(api.editing.enqueue,args);expect(await u.mutation(api.editing.enqueue,args)).toBe(id);const reordered=Object.fromEntries(Object.entries(settings).reverse()) as unknown as EditSettings;expect(await u.mutation(api.editing.enqueue,{...args,settings:reordered})).toBe(id);await expect(u.mutation(api.editing.enqueue,{...args,key:'another-click'})).rejects.toThrow('قيد التنفيذ');await u.mutation(api.editing.save,{requestId,settings:{...settings,duration:5}});const row=await t.run(ctx=>ctx.db.get(id));expect(row!.settings.duration).toBe(6);expect(row!.texts.phone).toBe('07700000000');expect((await u.query(api.requests.list))[0].videoId).toBe(storageId);});
 it('accounts for trims and transitions, rejecting shortfall and foreign clips',async()=>{const {u,requestId,settings}=await fixture();const split={...settings,clips:[{...settings.clips[0],end:3},{...settings.clips[0],start:3}],transition:.25,duration:5.75};expect(availableDuration(split)).toBe(5.75);validateEdit(split);expect(()=>validateEdit({...split,duration:6})).toThrow('النقص');await expect(u.mutation(api.editing.enqueue,{requestId,settings:{...settings,clips:[{storageId:'foreign',start:0,end:6}]},key:'foreign-file'})).rejects.toThrow('مرتبط');await expect(u.mutation(api.editing.enqueue,{requestId,settings:{...settings,clips:[{...settings.clips[0],end:7}]},key:'bad-trimming'})).rejects.toThrow('نهاية القص');});
 it('fences old editors, renews after restart, and never changes generation phase',async()=>{const {t,u,requestId,settings}=await fixture();const exportId=await u.mutation(api.editing.enqueue,{requestId,settings,key:'resume-export'}),a={exportId,workerId:'a',fence:'1'};await t.mutation(internal.editing.claim,a);await expect(t.mutation(internal.editing.claim,{...a,workerId:'b',fence:'2'})).rejects.toThrow('Another editor');await t.mutation(internal.editing.progress,{...a,status:'encoding',percent:38});await t.run(async ctx=>{const r=await ctx.db.get(exportId);await ctx.db.patch(exportId,{lease:{...r!.lease!,until:0}})});const b={...a,workerId:'b',fence:'2'};await t.mutation(internal.editing.claim,b);await expect(t.mutation(internal.editing.progress,{...a,status:'uploading'})).rejects.toThrow('lease lost');await t.mutation(internal.editing.progress,{...b,status:'uploading'});expect((await u.query(api.requests.list))[0].runner).toBeUndefined();await expect(t.mutation(internal.editing.progress,{...b,status:'completed'})).rejects.toThrow('verified');});
 it('retains previous completed output while another version fails',async()=>{const {t,u,requestId,settings}=await fixture();const first=await u.mutation(api.editing.enqueue,{requestId,settings,key:'first-version'});await t.run(ctx=>ctx.db.patch(first,{status:'completed'}));const second=await u.mutation(api.editing.enqueue,{requestId,settings:{...settings,duration:5},key:'second-version'});const a={exportId:second,workerId:'a',fence:'1'};await t.mutation(internal.editing.claim,a);await t.mutation(internal.editing.progress,{...a,status:'failed',error:'Upload interrupted'});const rows=(await u.query(api.editing.state,{requestId})).exports;expect(rows.find(r=>r._id===first)?.status).toBe('completed');expect(rows.find(r=>r._id===second)?.status).toBe('failed');});
});
