import {afterEach,beforeEach,expect,it,vi} from 'vitest';
import {convexTest} from 'convex-test';
import schema from './schema';
import {api,internal} from './_generated/api';
import {filmUsage,parseFilmReply,FILM_PROJECT_BUDGET} from '../shared/film-chat';
const modules=import.meta.glob('./**/*.{ts,js}'),owner={subject:'owner',issuer:'https://owner.clerk.accounts.dev'};
beforeEach(()=>{vi.useFakeTimers();vi.stubEnv('OWNER_SUBJECT',owner.subject);vi.stubEnv('CLERK_JWT_ISSUER_DOMAIN',owner.issuer);vi.stubEnv('OPENAI_API_KEY','sk-fixture-not-a-real-key')});
afterEach(()=>{vi.unstubAllGlobals();vi.unstubAllEnvs();vi.useRealTimers()});
async function setup(){const t=convexTest(schema,modules),u=t.withIdentity(owner);const id=await u.mutation(api.films.create,{key:'new',title:'فيلم كارتوني'});return {t,u,id};}
it('protects conversations and isolates authorized subjects',async()=>{const {t,u,id}=await setup();await expect(t.query(api.films.list,{})).rejects.toThrow();await expect(t.mutation(api.films.send,{projectId:id,key:'x',text:'hello'})).rejects.toThrow();await t.run(ctx=>ctx.db.insert('pointWallets',{subject:'other',publicId:'MS-other',name:'other',balance:0,enabled:true,models:[],maxClips:1,createdAt:1,updatedAt:1}));const other=t.withIdentity({...owner,subject:'other'});expect(await other.query(api.films.list,{})).toEqual([]);await expect(other.query(api.films.state,{projectId:id})).rejects.toThrow('غير متاح');await expect(other.mutation(api.films.send,{projectId:id,key:'x',text:'hello'})).rejects.toThrow('غير متاح');expect((await u.query(api.films.state,{projectId:id})).project.title).toBe('فيلم كارتوني');});
it('deduplicates project creation and message reservation without video jobs or point debits',async()=>{const {t,u,id}=await setup();expect(await u.mutation(api.films.create,{key:'new',title:'فيلم كارتوني'})).toBe(id);const a={projectId:id,key:'same',text:'قصة عن طفلين'};const turn=await u.mutation(api.films.send,a);expect(await u.mutation(api.films.send,a)).toBe(turn);await expect(u.mutation(api.films.send,{...a,text:'تغيير النص'})).rejects.toThrow('مختلف');await expect(u.mutation(api.films.send,{...a,key:'other'})).rejects.toThrow('انتظر');const s=await u.query(api.films.state,{projectId:id});expect(s.turns).toHaveLength(1);expect(s.project.heldMicros).toBeGreaterThan(0);expect(s.project.heldMicros).toBeLessThan(FILM_PROJECT_BUDGET);expect(await t.run(ctx=>ctx.db.query('pointLedger').collect())).toEqual([]);expect(await t.run(ctx=>ctx.db.query('pipelines').collect())).toEqual([]);});
it('enforces server project and global daily budgets before any provider request',async()=>{const {t,u,id}=await setup();await t.run(ctx=>ctx.db.patch(id,{spentMicros:FILM_PROJECT_BUDGET}));await expect(u.mutation(api.films.send,{projectId:id,key:'limit',text:'hello'})).rejects.toThrow('حد كلفة');await t.run(async ctx=>{await ctx.db.patch(id,{spentMicros:0});await ctx.db.insert('filmBudgets',{key:`global:${new Date().toISOString().slice(0,10)}`,usedMicros:250_000})});await expect(u.mutation(api.films.send,{projectId:id,key:'daily',text:'hello'})).rejects.toThrow('اليومي');expect((await u.query(api.films.state,{projectId:id})).turns).toHaveLength(0);});
it('persists a real-provider-shaped reply, agreement and usage and only calls once on replay',async()=>{const {t,u,id}=await setup();const fetchMock=vi.fn().mockResolvedValue(new Response(JSON.stringify({id:'resp-fixture',status:'completed',usage:{input_tokens:1000,output_tokens:500},output:[{content:[{type:'output_text',text:JSON.stringify({reply:'نختار فيلم كارتوني. شنو أعمار الشخصيات؟',brief:'كارتوني، شخصيتان، دون كتابة فوق الصورة.'})}]}]}),{status:200}));vi.stubGlobal('fetch',fetchMock);const turnId=await u.mutation(api.films.send,{projectId:id,key:'reply',text:'كارتوني بشخصيتين'});await t.action(internal.films.respond,{turnId});await t.action(internal.films.respond,{turnId});expect(fetchMock).toHaveBeenCalledTimes(1);const s=await u.query(api.films.state,{projectId:id});expect(s.project.spentMicros).toBe(800);expect(s.project.heldMicros).toBe(0);expect(s.project.brief).toContain('شخصيتان');expect(s.turns[0].status).toBe('completed');expect(s.turns[0]).not.toHaveProperty('responseId');const request=JSON.parse(fetchMock.mock.calls[0][1].body);expect(request.store).toBe(false);expect(request.tools).toBeUndefined();expect(request.max_output_tokens).toBe(1600);});
it('keeps uncertain charges reserved without retrying after a network failure',async()=>{const {t,u,id}=await setup();const fetchMock=vi.fn().mockRejectedValue(new Error('secret-bearing provider detail'));vi.stubGlobal('fetch',fetchMock);const turnId=await u.mutation(api.films.send,{projectId:id,key:'uncertain',text:'قصة'});await t.action(internal.films.respond,{turnId});await t.action(internal.films.respond,{turnId});expect(fetchMock).toHaveBeenCalledTimes(1);const s=await u.query(api.films.state,{projectId:id});expect(s.turns[0].status).toBe('unknown');expect(s.project.spentMicros).toBe(0);expect(s.project.heldMicros).toBeGreaterThan(0);expect(s.turns[0].error).not.toContain('secret-bearing');});
it('does not expose provider errors or internal implementation in replies',async()=>{expect(()=>parseFilmReply('{"reply":"use Google Flow worker","brief":""}')).toThrow();expect(()=>parseFilmReply('{"reply":"sk-secret1234567890","brief":""}')).toThrow();expect(filmUsage(10_000,10_000)).toBe(14_000);const {t,u,id}=await setup();vi.stubGlobal('fetch',vi.fn().mockResolvedValue(new Response('secret provider response',{status:401})));const turnId=await u.mutation(api.films.send,{projectId:id,key:'bad-auth',text:'hello'});await t.action(internal.films.respond,{turnId});const s=await u.query(api.films.state,{projectId:id});expect(s.turns[0].error).not.toContain('secret provider');expect(s.project.heldMicros).toBe(0);expect(s.turns[0].status).toBe('failed');});
it('marks interrupted execution as uncertain after restart without rerunning it',async()=>{const {t,u,id}=await setup();const turnId=await u.mutation(api.films.send,{projectId:id,key:'interrupted',text:'قصة'});await t.mutation(internal.films.claim,{turnId});await t.run(ctx=>ctx.db.patch(turnId,{updatedAt:Date.now()-181_000}));await u.mutation(api.films.checkPending,{projectId:id});const s=await u.query(api.films.state,{projectId:id});expect(s.turns[0].status).toBe('unknown');expect(s.project.heldMicros).toBeGreaterThan(0);const fetchMock=vi.fn();vi.stubGlobal('fetch',fetchMock);await t.action(internal.films.respond,{turnId});expect(fetchMock).not.toHaveBeenCalled();});
it('rejects pasted API secrets and missing configuration without reserving or saving messages',async()=>{const {u,id}=await setup();await expect(u.mutation(api.films.send,{projectId:id,key:'secret',text:'sk-fixture1234567890'})).rejects.toThrow('مفاتيح');vi.stubEnv('OPENAI_API_KEY','');await expect(u.mutation(api.films.send,{projectId:id,key:'missing',text:'hello'})).rejects.toThrow('غير متاح');const s=await u.query(api.films.state,{projectId:id});expect(s.turns).toEqual([]);expect(s.project.heldMicros).toBe(0);});
