import {ConvexError,v} from 'convex/values';
import {mutation,query,internalQuery,internalMutation,internalAction,type MutationCtx,type QueryCtx} from './_generated/server';
import {internal} from './_generated/api';
import type {Id,Doc} from './_generated/dataModel';
import {owned} from './films';
import {requireOwner} from './access';
import {optionValidator} from './pipelineValidators';
import {filmPhase} from './filmProductionValidators';
import {previousPlans} from '../shared/film-plan';
import {productionClips} from '../shared/film-production';
import {canonical} from '../shared/editing';
import {validateFile,validateSignature} from '../shared/validation';
const identity={jobId:v.id('filmProductions'),workerId:v.string(),fence:v.string()};
async function pricing(ctx:QueryCtx|MutationCtx,episodeId:Id<'filmEpisodes'>,option:Doc<'filmProductions'>['option']){
 const episode=await ctx.db.get(episodeId);if(!episode)throw new ConvexError('الحلقة غير متاحة.');const p=await owned(ctx,episode.projectId);
 if(p.productionOption&&canonical(p.productionOption)!==canonical(option))throw new ConvexError('استخدم إعدادات الإنتاج المحفوظة في المناقشة.');
 const versions=await ctx.db.query('filmEpisodes').withIndex('by_project',q=>q.eq('projectId',p._id)).collect();
 if(!episode.approved||versions.some(e=>e.episode===episode.episode&&e.version>episode.version)||episode.referenceRevision!==(p.referenceRevision??0)||episode.brief!==p.brief||(episode.previousPlans??'[]')!==previousPlans(versions,episode.episode))throw new ConvexError('اعتمد النسخة الحالية من الحلقة ومراجعها قبل الإنتاج.');
 let previousFinalId:Id<'_storage'>|undefined;if(episode.episode>1){const previous=versions.filter(e=>e.episode===episode.episode-1).sort((a,b)=>b.version-a.version)[0];const completed=(await ctx.db.query('filmProductions').withIndex('by_project',q=>q.eq('projectId',p._id)).collect()).find(j=>j.episodeId===previous?._id&&j.stage==='completed');if(!completed?.finalId)throw new ConvexError('أكمل إنتاج النسخة المعتمدة من الحلقة السابقة قبل هذه الحلقة.');previousFinalId=completed.finalId;}
 const worker=await ctx.db.query('workers').withIndex('by_key',q=>q.eq('key','pipeline')).unique();if(!worker||Date.now()-worker.observedAt>3600000||!worker.options.some(o=>canonical(o)===canonical(option)))throw new ConvexError('خيارات الإنتاج تحتاج تحديثًا من برنامج التشغيل.');
 const refs=await ctx.db.query('filmReferences').withIndex('by_project',q=>q.eq('projectId',p._id)).collect(),references=refs.map(r=>({_id:r._id,kind:r.kind,name:r.name,description:r.description,fileId:r.fileId}));
 if(episode.plan.scenes.every(s=>s.seconds===8)&&option.seconds!==8||episode.plan.scenes.every(s=>s.seconds===10)&&option.seconds!==10)throw new ConvexError('الموديل المختار مختلف عن خطة الحلقة؛ راجع التخطيط قبل الإنتاج.');
 const clips=productionClips(episode.plan,option,references,p.settings!.style,p.settings!.dialect);const wallet=await ctx.db.query('pointWallets').withIndex('by_subject',q=>q.eq('subject',p.subject)).unique();
 if(!wallet?.enabled||!wallet.models.includes(option.model))throw new ConvexError('المحفظة لا تسمح بهذا الموديل.');if(clips.length>wallet.maxClips)throw new ConvexError('صلاحية إنتاج هذه الحلقة غير متاحة لمحفظتك؛ تواصل مع الإدارة.');
 const rate=await ctx.db.query('pointRates').withIndex('by_key',q=>q.eq('key',`${option.model}:${option.resolution}:${option.seconds}`)).unique();if(!rate||!Number.isSafeInteger(rate.points)||rate.points<0)throw new ConvexError('سعر إنتاج هذا الموديل غير متاح.');
 const total=rate.points*clips.length,stamp=canonical({episodeId,revision:p.referenceRevision,option,unit:rate.points,count:clips.length});
 return {p,episode,clips,references,wallet,previousFinalId,unit:rate.points,total,stamp,workerOnline:worker.filmReady===true&&worker.state==='online'&&Date.now()-worker.seenAt<30000};
}
export const options=query({args:{projectId:v.id('filmProjects')},handler:async(ctx,a)=>{await owned(ctx,a.projectId);const w=await ctx.db.query('workers').withIndex('by_key',q=>q.eq('key','pipeline')).unique();return {manualMergeReady:true,storyPlanningReady:true,options:w&&Date.now()-w.observedAt<=3600000?w.options:[],online:!!w&&w.filmReady===true&&w.state==='online'&&Date.now()-w.seenAt<30000};}});
export const quote=query({args:{episodeId:v.id('filmEpisodes'),option:optionValidator},handler:async(ctx,a)=>{try{const q=await pricing(ctx,a.episodeId,a.option);return {stamp:q.stamp,total:q.total,unit:q.unit,count:q.clips.length,duration:q.p.settings!.seconds,sourceSeconds:q.clips.length*a.option.seconds,balance:q.wallet.balance,sufficient:q.wallet.balance>=q.total,workerOnline:q.workerOnline,error:null};}catch(e){return {error:e instanceof ConvexError?String(e.data):'تعذر عرض سعر الحلقة.'};}}});
export const list=query({args:{projectId:v.id('filmProjects')},handler:async(ctx,a)=>{await owned(ctx,a.projectId);return ctx.db.query('filmProductions').withIndex('by_project',q=>q.eq('projectId',a.projectId)).order('desc').take(10);}});
// Only the owner can explicitly obtain a bearer download link for their completed film.
// Protected customer previews continue to use /film-media.
export const ownerDownload=query({args:{jobId:v.id('filmProductions')},handler:async(ctx,a)=>{
 await requireOwner(ctx);const j=await ctx.db.get(a.jobId);if(!j)throw new ConvexError('الفيديو غير متاح.');await owned(ctx,j.projectId);
 if(j.stage!=='completed'||!j.finalId)throw new ConvexError('انتظر اكتمال تصدير الفيديو.');
 const url=await ctx.storage.getUrl(j.finalId);if(!url)throw new ConvexError('ملف الفيديو غير متاح.');
 return {url,title:j.plan.title,duration:j.media?.duration};
}});
export const assembleExisting=mutation({args:{episodeId:v.id('filmEpisodes'),key:v.string(),manualMerge:v.optional(v.boolean()),parts:v.array(v.object({storageId:v.id('_storage'),start:v.number(),end:v.number()}))},handler:async(ctx,a)=>{
 await requireOwner(ctx);const e=await ctx.db.get(a.episodeId);if(!e)throw new ConvexError('الحلقة غير متاحة.');const p=await owned(ctx,e.projectId),key=`${p._id}:existing:${a.key}`,old=await ctx.db.query('filmProductions').withIndex('by_key',q=>q.eq('key',key)).unique();if(old){if(!!old.manualMerge!==!!a.manualMerge)throw new ConvexError('إعداد دمج مختلف بنفس معرّف المونتاج.');if(canonical(old.clips.map(c=>({storageId:c.storageId,start:c.sourceStart??0,end:(c.sourceStart??0)+c.target})))!==canonical(a.parts))throw new ConvexError('مصادر مختلفة بنفس معرّف المونتاج.');return old._id;}
 if(!e.approved||!a.parts.length||a.parts.length>80||a.key.length>100)throw new ConvexError('اعتمد الحلقة وحدد المقاطع أولًا.');
 const exports=await ctx.db.query('exports').collect(),requests=await ctx.db.query('requests').collect();
 const clips=a.parts.map((part,index)=>{const source=exports.find(x=>x.fileId===part.storageId&&x.status==='completed')?.media??requests.flatMap(r=>r.results??[]).find(r=>r.storageId===part.storageId);if(!source||!Number.isFinite(part.start)||!Number.isFinite(part.end)||part.start<0||part.end-part.start<.5||part.end>source.duration+.04||a.parts.slice(0,index).some(o=>o.storageId===part.storageId&&Math.max(o.start,part.start)<Math.min(o.end,part.end)))throw new ConvexError('مصدر غير متحقق أو قص غير صالح أو تكرار نفس الفترة.');return {index,scene:index,part:0,target:part.end-part.start,prompt:'اختبار تركيب مقاطع محفوظة؛ ليس توليدًا جديدًا.',referenceIds:[],state:'uploaded' as const,assetId:`existing-${index}`,storageId:part.storageId,duration:source.duration,width:source.width,height:source.height,sourceStart:part.start,review:{passed:true,summary:'مقاطع موجودة اختارها المالك للمونتاج؛ لا ادعاء مراجعة توليد جديد.',issues:[]}};});
 const duration=clips.reduce((n,c)=>n+c.target,0);if(Math.abs(duration-(p.settings?.seconds??0))>.04)throw new ConvexError('المقاطع المختارة لا تحقق مدة الحلقة؛ لا تكرار أو تمديد تلقائي.');
 return ctx.db.insert('filmProductions',{projectId:p._id,episodeId:e._id,subject:p.subject,key,mode:'existing',manualMerge:a.manualMerge,mergeRequested:a.manualMerge?false:undefined,option:{model:'existing',actualModel:'مقاطع محفوظة دون توليد',seconds:8,resolution:'720p',aspect:clips[0].width/clips[0].height<1?'9:16':'16:9',cost:0},clips,stage:'queued',paused:false,stopRequested:false,unitPoints:0,reserved:0,spent:0,refund:0,settings:{style:p.settings!.style,dialect:p.settings!.dialect,duration},plan:e.plan,references:[],createdAt:Date.now(),updatedAt:Date.now()});
}});
export const authorize=mutation({args:{episodeId:v.id('filmEpisodes'),option:optionValidator,key:v.string(),stamp:v.string()},handler:async(ctx,a)=>{
 const e=await ctx.db.get(a.episodeId);if(!e)throw new ConvexError('الحلقة غير متاحة.');await owned(ctx,e.projectId);const key=`${e.projectId}:${a.key}`,old=await ctx.db.query('filmProductions').withIndex('by_key',q=>q.eq('key',key)).unique();if(old){if(old.episodeId!==a.episodeId||canonical(old.option)!==canonical(a.option))throw new ConvexError('تفويض مختلف بنفس المعرف.');return old._id;}
 if(!/^[\w-]{8,100}$/.test(a.key))throw new ConvexError('معرف التفويض غير صالح.');const q=await pricing(ctx,a.episodeId,a.option);if(q.stamp!==a.stamp)throw new ConvexError('تغير عرض السعر؛ راجعه قبل الموافقة.');if(q.wallet.balance<q.total)throw new ConvexError('رصيدك لا يكفي؛ اشحن حسابك عبر واتساب.');if(!process.env.OPENAI_API_KEY)throw new ConvexError('مراجعة المشاهد غير متاحة؛ لا يبدأ الإنتاج.');
 const jobs=await ctx.db.query('filmProductions').withIndex('by_project',r=>r.eq('projectId',e.projectId)).collect();if(jobs.some(j=>j.episodeId===e._id))throw new ConvexError('لهذه النسخة تشغيل محفوظ؛ افتحه للاستئناف. لإنتاج جديد عدّل واعتمد نسخة جديدة صراحة.');
 const now=Date.now(),jobId=await ctx.db.insert('filmProductions',{projectId:e.projectId,episodeId:e._id,subject:q.p.subject,previousFinalId:q.previousFinalId,key,mode:'generate',manualMerge:true,mergeRequested:false,option:a.option,clips:q.clips.map((c,index)=>({...c,referenceIds:c.referenceIds as Id<'_storage'>[],index,state:'pending' as const})),stage:'queued',paused:false,stopRequested:false,walletId:q.wallet._id,unitPoints:q.unit,reserved:q.total,spent:0,refund:0,settings:{style:q.p.settings!.style,dialect:q.p.settings!.dialect,duration:q.p.settings!.seconds},plan:e.plan,references:q.references,createdAt:now,updatedAt:now});
 await ctx.db.patch(q.wallet._id,{balance:q.wallet.balance-q.total,updatedAt:now});await ctx.db.insert('pointLedger',{key:`film-reserve-${jobId}`,walletId:q.wallet._id,kind:'reserve',amount:-q.total,balanceAfter:q.wallet.balance-q.total,note:`حجز إنتاج الحلقة ${e.episode} — ليس صرفًا مؤكدًا أو استهلاك Flow`,actor:q.p.subject,createdAt:now});return jobId;
}});
async function ownJob(ctx:MutationCtx,id:Id<'filmProductions'>){const j=await ctx.db.get(id);if(!j)throw new ConvexError('الإنتاج غير متاح.');await owned(ctx,j.projectId);return j;}
export const merge=mutation({args:{jobId:v.id('filmProductions')},handler:async(ctx,a)=>{const j=await ownJob(ctx,a.jobId);if(j.stage==='completed'||j.mergeRequested)return j._id;if(j.clips.some(c=>c.state!=='uploaded'||!c.storageId||!c.review?.passed))throw new ConvexError('أكمل المقاطع ومراجعتها قبل الدمج.');if(j.lease&&j.lease.until>Date.now())throw new ConvexError('انتظر حفظ آخر خطوة ثم أعد المحاولة.');await ctx.db.patch(j._id,{manualMerge:true,mergeRequested:true,stage:'queued',paused:false,stopRequested:false,error:undefined,percent:undefined,updatedAt:Date.now()});return j._id;}});
export const stop=mutation({args:{jobId:v.id('filmProductions')},handler:async(ctx,a)=>{const j=await ownJob(ctx,a.jobId);if(j.stage==='completed')return;const remaining=j.reserved-j.spent-j.refund;if(remaining>0&&j.walletId){const w=await ctx.db.get(j.walletId);if(!w)throw new ConvexError('المحفظة غير متاحة.');await ctx.db.patch(w._id,{balance:w.balance+remaining,updatedAt:Date.now()});await ctx.db.insert('pointLedger',{key:`film-refund-${j._id}-${j.refund}`,walletId:w._id,kind:'refund',amount:remaining,balanceAfter:w.balance+remaining,note:'إعادة الجزء الذي لم يبدأ إرساله من حجز الحلقة',actor:j.subject,createdAt:Date.now()});}await ctx.db.patch(j._id,{refund:j.refund+remaining,stage:'stopped',stopRequested:true,paused:true,error:'الإيقاف يمنع الخطوات اللاحقة؛ المهمة التي أُرسلت قد تستمر ولا تُسترد نقاطها.',updatedAt:Date.now()});}});
export const resume=mutation({args:{jobId:v.id('filmProductions'),reserveAgain:v.boolean()},handler:async(ctx,a)=>{const j=await ownJob(ctx,a.jobId);if(j.stage==='completed')return;if(j.manualMerge&&!j.mergeRequested&&j.clips.every(c=>c.state==='uploaded'&&c.review?.passed)){await ctx.db.patch(j._id,{stage:'ready',paused:false,stopRequested:false,error:undefined,updatedAt:Date.now()});return;}const required=j.clips.filter(c=>c.state==='pending').length*j.unitPoints,held=j.reserved-j.spent-j.refund,extra=Math.max(0,required-held);if(extra){if(!a.reserveAgain||!j.walletId)throw new ConvexError('استكمال المقاطع الباقية يحتاج موافقة جديدة على حجز نقاطها.');const w=await ctx.db.get(j.walletId);if(!w?.enabled||!w.models.includes(j.option.model)||w.balance<extra)throw new ConvexError('الرصيد أو الصلاحية لا تكفي للاستكمال.');await ctx.db.patch(w._id,{balance:w.balance-extra,updatedAt:Date.now()});await ctx.db.insert('pointLedger',{key:`film-resume-${j._id}-${j.reserved}`,walletId:w._id,kind:'reserve',amount:-extra,balanceAfter:w.balance-extra,note:'حجز المقاطع التي لم تبدأ فقط؛ لا إعادة توليد المقاطع السابقة',actor:j.subject,createdAt:Date.now()});}if(j.clips.some(c=>c.review&&!c.review.passed))throw new ConvexError('المشهد لم يجتز المراجعة؛ راجعه قبل المتابعة.');await ctx.db.patch(j._id,{reserved:j.reserved+extra,paused:false,stopRequested:false,stage:'queued',error:undefined,updatedAt:Date.now()});}});
export const acceptReview=mutation({args:{jobId:v.id('filmProductions'),index:v.number()},handler:async(ctx,a)=>{const j=await ownJob(ctx,a.jobId),c=j.clips[a.index];if(!c?.storageId||c.review?.passed)throw new ConvexError('لا توجد مراجعة مرفوضة لهذا المقطع.');const clips=[...j.clips];clips[a.index]={...c,reviewState:'completed',review:{passed:true,issues:c.review?.issues??[],summary:'قبول يدوي صريح بعد مراجعة المستخدم؛ '+(c.review?.summary??'المراجعة الآلية غير محسومة.')}};await ctx.db.patch(j._id,{clips,updatedAt:Date.now()});}});
export const next=internalQuery({args:{},handler:async ctx=>{if((await ctx.db.query('pipelines').collect()).some(j=>j.lease&&j.lease.until>Date.now())||(await ctx.db.query('imageJobs').collect()).some(j=>j.lease&&j.lease.until>Date.now())||(await ctx.db.query('filmProductions').collect()).some(j=>j.lease&&j.lease.until>Date.now()))return null;return (await ctx.db.query('filmProductions').collect()).find(j=>!j.paused&&!j.stopRequested&&j.stage!=='completed'&&j.stage!=='ready')?._id??null;}});
export const get=internalQuery({args:{jobId:v.id('filmProductions')},handler:(ctx,a)=>ctx.db.get(a.jobId)});
async function locked(ctx:MutationCtx,a:{jobId:Id<'filmProductions'>;workerId:string;fence:string}){const j=await ctx.db.get(a.jobId);if(!j||j.lease?.workerId!==a.workerId||j.lease.fence!==a.fence||j.lease.until<Date.now())throw new ConvexError('Film lease lost');return j;}
export const claim=internalMutation({args:identity,handler:async(ctx,a)=>{const j=await ctx.db.get(a.jobId);if(!j||j.paused||j.stopRequested||(j.stage==='completed'||j.stage==='ready'))throw new ConvexError('Film paused');for(const table of ['pipelines','imageJobs','filmProductions'] as const){if((await ctx.db.query(table).collect()).some(p=>p.lease&&p.lease.until>Date.now()&&(p._id!==j._id||p.lease.workerId!==a.workerId||p.lease.fence!==a.fence)))throw new ConvexError('Another Worker owns execution');}await ctx.db.patch(j._id,{lease:{workerId:a.workerId,fence:a.fence,until:Date.now()+60000}});return j;}});
export const heartbeat=internalMutation({args:identity,handler:async(ctx,a)=>{const j=await locked(ctx,a);await ctx.db.patch(j._id,{lease:{workerId:a.workerId,fence:a.fence,until:Date.now()+60000}});return {stop:j.stopRequested||j.paused};}});
export const release=internalMutation({args:identity,handler:async(ctx,a)=>{const j=await locked(ctx,a);await ctx.db.patch(j._id,{lease:{...j.lease!,until:0}});}});
export const progress=internalMutation({args:{...identity,stage:filmPhase,percent:v.optional(v.number()),error:v.optional(v.string())},handler:async(ctx,a)=>{const j=await locked(ctx,a);if(j.stage==='completed'||a.stage==='completed'||(a.error?.length??0)>1000||a.percent!==undefined&&(!Number.isFinite(a.percent)||a.percent<0||a.percent>99||a.stage!=='montage'))throw new ConvexError('Invalid film progress');if(a.stage==='ready'&&(!j.manualMerge||j.mergeRequested||j.clips.some(c=>c.state!=='uploaded'||!c.storageId||!c.review?.passed)))throw new ConvexError('Film clips are not ready');if(a.stage==='montage'&&j.manualMerge&&!j.mergeRequested)throw new ConvexError('Merge requires user request');await ctx.db.patch(j._id,{stage:j.stopRequested?'stopped':a.stage,percent:a.percent===undefined?undefined:Math.max(a.percent,j.stage==='montage'?(j.percent??0):0),error:a.error,paused:j.paused||['failed','login','uncertain','stopped'].includes(a.stage),updatedAt:Date.now()});}});
export const clip=internalMutation({args:{...identity,index:v.number(),state:v.union(v.literal('intent'),v.literal('submitted'),v.literal('unknown'),v.literal('downloaded')),projectPath:v.optional(v.string()),assetId:v.optional(v.string()),percent:v.optional(v.number())},handler:async(ctx,a)=>{
 const j=await locked(ctx,a),c=j.clips[a.index];if(!c||!Number.isInteger(a.index))throw new ConvexError('Invalid film clip');const transitions:Record<string,string[]>={pending:['intent'],intent:['submitted','unknown'],submitted:['submitted','unknown','downloaded'],unknown:['submitted','unknown','downloaded'],downloaded:['downloaded'],uploaded:[]};if(!transitions[c.state]?.includes(a.state))throw new ConvexError('Never resubmit a film intent');
 if(a.projectPath&&!/^\/project\/[\w-]+$/.test(a.projectPath)||a.assetId&&!/^[\w-]{1,200}$/.test(a.assetId)||a.percent!==undefined&&(!Number.isFinite(a.percent)||a.percent<0||a.percent>99||a.state!=='submitted'))throw new ConvexError('Invalid film asset identity');
 if(a.state==='intent'){if(j.mode!=='generate'||j.paused||j.stopRequested||!a.projectPath||j.clips.slice(0,a.index).some(p=>p.state!=='uploaded'||!p.review?.passed)||!j.walletId||j.reserved-j.spent-j.refund<j.unitPoints)throw new ConvexError('No paid film authorization');const w=await ctx.db.get(j.walletId);if(!w?.enabled||!w.models.includes(j.option.model))throw new ConvexError('Wallet permission revoked');await ctx.db.insert('pointLedger',{key:`film-spend-${j._id}-${a.index}`,walletId:w._id,kind:'debit',amount:-j.unitPoints,balanceAfter:w.balance,note:'تحويل جزء من حجز الحلقة إلى صرف عند نية الإرسال؛ ليس إثبات استهلاك Flow',actor:j.subject,createdAt:Date.now()});await ctx.db.patch(j._id,{spent:j.spent+j.unitPoints});}
 const clips=[...j.clips];clips[a.index]={...c,state:a.state,projectPath:a.projectPath??c.projectPath,assetId:a.assetId??c.assetId,percent:a.percent};await ctx.db.patch(j._id,{clips,updatedAt:Date.now()});
}});
export const upload=internalMutation({args:{...identity,index:v.number(),purpose:v.union(v.literal('source'),v.literal('frame'),v.literal('final')),key:v.string(),size:v.number(),type:v.string()},handler:async(ctx,a)=>{const j=await locked(ctx,a);if(j.stopRequested||j.paused)throw new ConvexError('Film stopped');if(a.purpose==='source'&&j.clips[a.index]?.state!=='downloaded'||a.purpose==='frame'&&j.clips[a.index]?.state!=='uploaded'||a.purpose==='final'&&(j.manualMerge&&!j.mergeRequested||j.clips.some(c=>!c.review?.passed)))throw new ConvexError('Film source incomplete');const kind=a.purpose==='frame'?'image':'video';validateFile(a.type,a.size,kind);if(a.type!==(kind==='image'?'image/jpeg':'video/mp4')||!new RegExp(`^${kind}:[a-f0-9]{64}$`).test(a.key))throw new ConvexError('Invalid film file');const old=await ctx.db.query('uploads').withIndex('by_key',q=>q.eq('key',a.key)).unique();if(old&&(old.size!==a.size||old.type!==a.type))throw new ConvexError('File conflict');if(!old)await ctx.db.insert('uploads',{key:a.key,kind,type:a.type,size:a.size,name:`film-${j._id}.`+(kind==='image'?'jpg':'mp4'),createdAt:Date.now()});return {storageId:old?.storageId,url:old?.storageId?null:await ctx.storage.generateUploadUrl()};}});
const finishArgs={...identity,index:v.number(),purpose:v.union(v.literal('source'),v.literal('frame'),v.literal('final')),key:v.string(),storageId:v.id('_storage'),duration:v.optional(v.number()),width:v.optional(v.number()),height:v.optional(v.number()),audio:v.optional(v.boolean()),frameSlot:v.optional(v.number())};
export const finish=internalAction({args:finishArgs,handler:async(ctx,a):Promise<void>=>{const f=await ctx.runQuery(internal.files.ticket,{key:a.key}),blob=await ctx.storage.get(a.storageId);if(!f||!blob||blob.size!==f.size||blob.type!==f.type)throw new ConvexError('Invalid film file');validateSignature(new Uint8Array(await blob.slice(0,32).arrayBuffer()),blob.type);const m=await ctx.runQuery(internal.runner.metadata,{storageId:a.storageId});if(a.key!==`${f.kind}:${m?.hash}`)throw new ConvexError('Hash mismatch');await ctx.runMutation(internal.files.register,{key:a.key,storageId:a.storageId});await ctx.runMutation(internal.filmProduction.register,a);}});
export const register=internalMutation({args:finishArgs,handler:async(ctx,a)=>{const j=await locked(ctx,a),clips=[...j.clips],c=clips[a.index];if(j.stage==='completed'){if(a.purpose==='final'&&j.finalId===a.storageId)return;throw new ConvexError('Completed film is immutable');}if(j.stopRequested||j.paused)throw new ConvexError('Film stopped');const file=await ctx.db.query('uploads').withIndex('by_storage',q=>q.eq('storageId',a.storageId)).unique();if(file?.key!==a.key)throw new ConvexError('Unverified file');
 if(a.purpose==='frame'){const slot=a.frameSlot,frames=[...(c?.reviewFrames??[])];if(!c?.storageId||file.kind!=='image'||slot===undefined||!Number.isInteger(slot)||slot<0||slot>3||slot>frames.length||frames[slot]&&frames[slot]!==a.storageId||c.reviewState)throw new ConvexError('Invalid review frame');frames[slot]=a.storageId;clips[a.index]={...c,reviewFrames:frames};}
 else{if(!a.duration||!a.width||!a.height||!Number.isFinite(a.duration)||![a.width,a.height].every(n=>Number.isSafeInteger(n)&&n>0&&n<=8192)||file.kind!=='video')throw new ConvexError('Invalid film metadata');if(a.purpose==='source'){if(!c?.assetId||!['downloaded','uploaded'].includes(c.state)||a.duration<j.option.seconds-.04||c.storageId&&c.storageId!==a.storageId)throw new ConvexError('Short or conflicting film clip');clips[a.index]={...c,state:'uploaded',storageId:a.storageId,duration:a.duration,width:a.width,height:a.height};}else{if(j.manualMerge&&!j.mergeRequested||j.clips.some(c=>!c.review?.passed)||Math.abs(a.duration-j.settings.duration)>.1||Math.abs(a.width/a.height-(j.option.aspect==='9:16'?9/16:16/9))>.02)throw new ConvexError('Final film does not match approved duration');await ctx.db.patch(j._id,{stage:'completed',finalId:a.storageId,media:{duration:a.duration,width:a.width,height:a.height,size:file.size,audio:a.audio??false,sources:j.clips.map(c=>({storageId:c.storageId!,width:c.width!,height:c.height!,duration:c.duration!}))},percent:undefined,error:undefined,updatedAt:Date.now()});return;}}
 await ctx.db.patch(j._id,{clips,updatedAt:Date.now()});
}});
export const fileAccess=internalQuery({args:{jobId:v.id('filmProductions'),storageId:v.id('_storage')},handler:async(ctx,a)=>{const j=await ctx.db.get(a.jobId);return !!j&&(j.previousFinalId===a.storageId||j.finalId===a.storageId||j.clips.some(c=>c.storageId===a.storageId||c.referenceIds.includes(a.storageId)||c.reviewFrames?.includes(a.storageId)));}});
export const media=internalQuery({args:{jobId:v.id('filmProductions'),storageId:v.id('_storage')},handler:async(ctx,a)=>{const j=await ctx.db.get(a.jobId);if(!j)return null;await owned(ctx,j.projectId);if(j.finalId!==a.storageId&&!j.clips.some(c=>c.storageId===a.storageId))return null;const f=await ctx.db.query('uploads').withIndex('by_storage',q=>q.eq('storageId',a.storageId)).unique();return f?{size:f.size,type:f.type}:null;}});
