import {v,ConvexError} from 'convex/values';
import {query,mutation,internalQuery,internalMutation,internalAction,type MutationCtx} from './_generated/server';
import {internal} from './_generated/api';
import {requireOwner} from './access';
import {imageOptionValidator,imageStatusValidator,validateImageOption,imagePoints} from '../shared/images';
import {validateFile,validateSignature} from '../shared/validation';
import {canonical} from '../shared/editing';
import type {Id} from './_generated/dataModel';
const identity={jobId:v.id('imageJobs'),workerId:v.string(),fence:v.string()};
async function locked(ctx:MutationCtx,a:{jobId:Id<'imageJobs'>;workerId:string;fence:string}){const j=await ctx.db.get(a.jobId);if(!j||j.lease?.workerId!==a.workerId||j.lease.fence!==a.fence||j.lease.until<Date.now())throw new ConvexError('Image lease lost');return j;}
export const list=query({args:{},handler:async ctx=>{const i=await requireOwner(ctx);return ctx.db.query('imageJobs').withIndex('by_subject',q=>q.eq('subject',i.subject)).order('desc').take(100);}});
export const authorize=mutation({args:{key:v.string(),prompt:v.string(),referenceIds:v.array(v.id('_storage')),option:imageOptionValidator},handler:async(ctx,a)=>{
 const i=await requireOwner(ctx);validateImageOption(a.option);if(!/^[a-zA-Z0-9-]{8,100}$/.test(a.key)||!a.prompt.trim()||a.prompt.length>10000||a.referenceIds.length>8||new Set(a.referenceIds).size!==a.referenceIds.length)throw new ConvexError('طلب الصورة غير صالح.');
 const old=await ctx.db.query('imageJobs').withIndex('by_key',q=>q.eq('key',a.key)).unique();if(old){if(old.subject!==i.subject||old.prompt!==a.prompt.trim()||canonical(old.option)!==canonical(a.option)||canonical(old.referenceIds)!==canonical(a.referenceIds))throw new ConvexError('معرف المحاولة مرتبط بإعدادات مختلفة.');return old._id;}
 const w=await ctx.db.query('workers').withIndex('by_key',q=>q.eq('key','pipeline')).unique();if(!w?.imageObservedAt||Date.now()-w.imageObservedAt>3600000||!w.imageOptions?.some(o=>canonical(o)===canonical(a.option)))throw new ConvexError('خيارات الصور أو كلفتها تحتاج قراءة حديثة من Flow.');
 for(const storageId of a.referenceIds){const f=await ctx.db.query('uploads').withIndex('by_storage',q=>q.eq('storageId',storageId)).unique();if(!f||f.kind!=='image')throw new ConvexError('الصورة المرجعية غير مصرح لها.');}
 const wallet=await ctx.db.query('pointWallets').withIndex('by_subject',q=>q.eq('subject',i.subject)).unique(),rate=await ctx.db.query('pointRates').withIndex('by_key',q=>q.eq('key',`${a.option.model}:original:0`)).unique(),points=imagePoints(rate??undefined);
 if(!wallet?.enabled||!wallet.models.includes(a.option.model))throw new ConvexError('فعّل صلاحية موديل الصور لهذه المحفظة من الأدمن.');if(wallet.balance<=0||wallet.balance<points)throw new ConvexError('رصيدك غير كافٍ؛ اشحن عبر واتساب.');
 return ctx.db.insert('imageJobs',{...a,prompt:a.prompt.trim(),subject:i.subject,walletId:wallet._id,points,status:'queued',paused:false,stopRequested:false,createdAt:Date.now(),updatedAt:Date.now()});
}});
export const stop=mutation({args:{jobId:v.id('imageJobs')},handler:async(ctx,a)=>{const i=await requireOwner(ctx),j=await ctx.db.get(a.jobId);if(!j||j.subject!==i.subject)throw new ConvexError('Unauthorized image');if(j.status==='completed')return;await ctx.db.patch(j._id,{paused:true,stopRequested:true,status:'stopped',updatedAt:Date.now()});}});
export const resume=mutation({args:{jobId:v.id('imageJobs')},handler:async(ctx,a)=>{const i=await requireOwner(ctx),j=await ctx.db.get(a.jobId);if(!j||j.subject!==i.subject)throw new ConvexError('Unauthorized image');if(j.status==='completed')return;await ctx.db.patch(j._id,{paused:false,stopRequested:false,status:j.intentAt?'generating':'queued',error:undefined,updatedAt:Date.now()});}});
export const presence=internalMutation({args:{options:v.array(imageOptionValidator),observedAt:v.number(),error:v.optional(v.string())},handler:async(ctx,a)=>{for(const o of a.options)validateImageOption(o);if(a.options.length>30||a.observedAt>Date.now()+1000)throw new ConvexError('Invalid image presence');const w=await ctx.db.query('workers').withIndex('by_key',q=>q.eq('key','pipeline')).unique();if(w)await ctx.db.patch(w._id,{imageOptions:a.options,imageObservedAt:a.observedAt,imageError:a.error});}});
export const next=internalQuery({args:{},handler:async ctx=>(await ctx.db.query('imageJobs').collect()).filter(j=>!j.paused&&!j.stopRequested&&j.status!=='completed'&&(!j.lease||j.lease.until<Date.now())).sort((a,b)=>a.createdAt-b.createdAt)[0]?._id??null});
export const get=internalQuery({args:{jobId:v.id('imageJobs')},handler:async(ctx,a)=>ctx.db.get(a.jobId)});
export const claim=internalMutation({args:identity,handler:async(ctx,a)=>{const j=await ctx.db.get(a.jobId);if(!j||j.paused||j.stopRequested||j.status==='completed')throw new ConvexError('Image paused or complete');const now=Date.now();if((await ctx.db.query('pipelines').collect()).some(p=>p.lease&&p.lease.until>now)||(await ctx.db.query('imageJobs').collect()).some(p=>p.lease&&p.lease.until>now&&(p._id!==j._id||p.lease.workerId!==a.workerId||p.lease.fence!==a.fence)))throw new ConvexError('Another Worker owns execution');await ctx.db.patch(j._id,{lease:{workerId:a.workerId,fence:a.fence,until:now+60000}});return j;}});
export const heartbeat=internalMutation({args:identity,handler:async(ctx,a)=>{const j=await locked(ctx,a);await ctx.db.patch(j._id,{lease:{...j.lease!,until:Date.now()+60000}});return {stop:j.stopRequested,paused:j.paused};}});
export const release=internalMutation({args:identity,handler:async(ctx,a)=>{const j=await locked(ctx,a);await ctx.db.patch(j._id,{lease:{...j.lease!,until:0}});}});
export const progress=internalMutation({args:{...identity,status:imageStatusValidator,error:v.optional(v.string()),pause:v.optional(v.boolean()),projectPath:v.optional(v.string()),assetId:v.optional(v.string()),baselineIds:v.optional(v.array(v.string())),intent:v.optional(v.boolean()),submitted:v.optional(v.boolean())},handler:async(ctx,a)=>{
 const j=await locked(ctx,a);if(j.status==='completed'||a.status==='completed')throw new ConvexError('Use verified image finish');if((a.error?.length??0)>1000)throw new ConvexError('Invalid error');
 if(a.projectPath&&(!/^\/project\/[a-zA-Z0-9-]+$/.test(a.projectPath)||j.projectPath&&a.projectPath!==j.projectPath))throw new ConvexError('Image project identity mismatch');if(a.assetId&&(!/^[a-zA-Z0-9-]{16,100}$/.test(a.assetId)||j.assetId&&a.assetId!==j.assetId))throw new ConvexError('Image asset identity mismatch');
 if(a.baselineIds&&(a.baselineIds.length>50||a.baselineIds.some(id=>!/^[a-zA-Z0-9-]{16,100}$/.test(id))||j.intentAt))throw new ConvexError('Invalid immutable image baseline');
 if(a.intent){if(j.intentAt||j.paused||j.stopRequested||!a.projectPath)throw new ConvexError('Image intent already sent or stopped');const wallet=await ctx.db.get(j.walletId);if(!wallet?.enabled||!wallet.models.includes(j.option.model)||wallet.balance<=0||wallet.balance<j.points)throw new ConvexError('رصيدك غير كافٍ أو الموديل غير مصرح.');const key=`image-${j._id}`;if(await ctx.db.query('pointLedger').withIndex('by_key',q=>q.eq('key',key)).unique())throw new ConvexError('Already billed');const balance=wallet.balance-j.points;await ctx.db.patch(wallet._id,{balance,updatedAt:Date.now()});await ctx.db.insert('pointLedger',{key,walletId:wallet._id,kind:'debit',amount:-j.points,balanceAfter:balance,note:`صورة ${j.option.model}؛ نقاط مشهد، لا تؤكد استهلاك Flow`,actor:'image-worker',createdAt:Date.now()});}
 if(a.submitted&&!j.intentAt)throw new ConvexError('No authorized image intent');await ctx.db.patch(j._id,{status:j.stopRequested?'stopped':a.status,error:a.error,paused:a.pause??j.paused,updatedAt:Date.now(),...(a.baselineIds?{baselineIds:a.baselineIds}:{}),...(a.intent?{intentAt:Date.now()}:{}),...(a.submitted?{submittedAt:j.submittedAt??Date.now()}:{}),...(a.projectPath?{projectPath:a.projectPath}:{}),...(a.assetId?{assetId:a.assetId}:{})});
}});
export const fileAccess=internalQuery({args:{jobId:v.id('imageJobs'),storageId:v.id('_storage')},handler:async(ctx,a)=>{const j=await ctx.db.get(a.jobId);return !!j?.referenceIds.includes(a.storageId);}});
export const upload=internalMutation({args:{...identity,key:v.string(),type:v.string(),size:v.number()},handler:async(ctx,a)=>{const j=await locked(ctx,a);if(!j.intentAt||!j.assetId||j.stopRequested||j.paused)throw new ConvexError('Image upload not ready');validateFile(a.type,a.size,'image');if(!/^image:[a-f0-9]{64}$/.test(a.key))throw new ConvexError('Invalid image hash');const old=await ctx.db.query('uploads').withIndex('by_key',q=>q.eq('key',a.key)).unique();if(old&&(old.size!==a.size||old.type!==a.type||old.kind!=='image'))throw new ConvexError('Image upload conflict');if(old?.storageId)return {storageId:old.storageId,url:null};if(!old)await ctx.db.insert('uploads',{key:a.key,kind:'image',name:`flow-${j._id}`,type:a.type,size:a.size,createdAt:Date.now()});return {storageId:null,url:await ctx.storage.generateUploadUrl()};}});
export const commit=internalMutation({args:{...identity,storageId:v.id('_storage'),type:v.string(),width:v.number(),height:v.number(),size:v.number()},handler:async(ctx,a)=>{const j=await locked(ctx,a);if(j.stopRequested||j.paused||!j.intentAt||!j.assetId)throw new ConvexError('Image completion refused');for(const n of [a.width,a.height])if(!Number.isInteger(n)||n<1||n>20000)throw new ConvexError('Invalid image dimensions');await ctx.db.patch(j._id,{fileId:a.storageId,fileType:a.type,width:a.width,height:a.height,size:a.size,status:'completed',error:undefined,updatedAt:Date.now()});return a.storageId;}});
export const finish=internalAction({args:{...identity,key:v.string(),storageId:v.id('_storage'),width:v.number(),height:v.number()},handler:async(ctx,a):Promise<Id<'_storage'>>=>{const row=await ctx.runQuery(internal.files.ticket,{key:a.key});if(!row||row.kind!=='image')throw new ConvexError('Image upload ticket missing');const blob=await ctx.storage.get(a.storageId);if(!blob)throw new ConvexError('Image missing');validateFile(blob.type,blob.size,'image');validateSignature(new Uint8Array(await blob.slice(0,32).arrayBuffer()),blob.type);const m=await ctx.runQuery(internal.runner.metadata,{storageId:a.storageId});if(a.key!==`image:${m?.hash}`||row.size!==blob.size||row.type!==blob.type)throw new ConvexError('Image content mismatch');const storageId=await ctx.runMutation(internal.files.register,{key:a.key,storageId:a.storageId});return ctx.runMutation(internal.images.commit,{jobId:a.jobId,workerId:a.workerId,fence:a.fence,storageId,type:blob.type,width:a.width,height:a.height,size:blob.size});}});
