import {beforeEach,it,expect,vi} from 'vitest';
import {convexTest} from 'convex-test';
import schema from './schema';
import {api,internal} from './_generated/api';
const modules=import.meta.glob('./**/*.{ts,js}'),owner={subject:'owner',issuer:'https://owner.clerk.accounts.dev'},option={model:'Nano Banana 2',aspect:'9:16',cost:2};
beforeEach(()=>{vi.stubEnv('OWNER_SUBJECT',owner.subject);vi.stubEnv('CLERK_JWT_ISSUER_DOMAIN',owner.issuer);vi.stubEnv('WORKER_KEY_SHA256','');});
async function fixture(){const t=convexTest(schema,modules),u=t.withIdentity(owner);const walletId=await t.run(async ctx=>{await ctx.db.insert('workers',{key:'pipeline',workerId:'w',state:'online',seenAt:Date.now(),observedAt:Date.now(),options:[],imageOptions:[option],imageObservedAt:Date.now()});return ctx.db.insert('pointWallets',{subject:owner.subject,publicId:'MS-fixture',name:'owner',balance:10,enabled:true,models:[option.model],maxClips:1,createdAt:1,updatedAt:1})});return {t,u,walletId,args:{key:'image-fixture',prompt:'A modern Iraqi office',referenceIds:[],option}};}
it('protects owner queries, mutations and image runner operations',async()=>{const {t,args}=await fixture();await expect(t.query(api.images.list,{})).rejects.toThrow();await expect(t.mutation(api.images.authorize,args)).rejects.toThrow();await expect(t.withIdentity({subject:'other',issuer:owner.issuer}).query(api.images.list,{})).rejects.toThrow();for(const op of ['imagePresence','imageNext','imageClaim','imageProgress','imageFile','imageUpload','imageFinish'])expect((await t.fetch('/runner',{method:'POST',body:JSON.stringify({op,args:{}})})).status).toBe(401);});
it('deduplicates authorization without billing and rejects stale cost or unauthorized references',async()=>{const {t,u,args,walletId}=await fixture();const id=await u.mutation(api.images.authorize,args);expect(await u.mutation(api.images.authorize,args)).toBe(id);expect((await t.run(ctx=>ctx.db.get(walletId)))?.balance).toBe(10);await expect(u.mutation(api.images.authorize,{...args,prompt:'changed'})).rejects.toThrow('مختلفة');await expect(u.mutation(api.images.authorize,{...args,key:'changed-cost',option:{...option,cost:0}})).rejects.toThrow('كلفتها');const other=await t.run(ctx=>ctx.storage.store(new Blob(['not registered'],{type:'image/png'})));await expect(u.mutation(api.images.authorize,{...args,key:'unknown-reference',referenceIds:[other]})).rejects.toThrow('مصرح');await t.run(async ctx=>{const w=await ctx.db.query('workers').first();await ctx.db.patch(w!._id,{imageObservedAt:Date.now()-3600001})});await expect(u.mutation(api.images.authorize,{...args,key:'stale-request'})).rejects.toThrow('حديثة');});
it('rejects empty balance even when Flow image cost is zero; preserves model permissions',async()=>{const {t,u,args,walletId}=await fixture();await t.run(async ctx=>{const w=await ctx.db.query('workers').first();await ctx.db.patch(w!._id,{imageOptions:[{...option,cost:0}]});await ctx.db.patch(walletId,{balance:0})});await expect(u.mutation(api.images.authorize,{...args,option:{...option,cost:0}})).rejects.toThrow('اشحن');await t.run(ctx=>ctx.db.patch(walletId,{balance:10,models:[]}));await expect(u.mutation(api.images.authorize,{...args,option:{...option,cost:0}})).rejects.toThrow('صلاحية');});
it('bills image intent once and fences a restarted worker without resubmitting',async()=>{const {t,u,args,walletId}=await fixture(),jobId=await u.mutation(api.images.authorize,args),a={jobId,workerId:'first',fence:'1'};await t.mutation(internal.images.claim,a);await expect(t.mutation(internal.images.claim,{...a,workerId:'second',fence:'2'})).rejects.toThrow('owns execution');await t.mutation(internal.images.progress,{...a,status:'generating',intent:true,projectPath:'/project/original',baselineIds:['reference-image-id']});expect((await t.run(ctx=>ctx.db.get(walletId)))?.balance).toBe(9);await expect(t.mutation(internal.images.progress,{...a,status:'generating',intent:true,projectPath:'/project/original'})).rejects.toThrow('already');await u.mutation(api.images.stop,{jobId});await u.mutation(api.images.resume,{jobId});await t.run(async ctx=>{const j=await ctx.db.get(jobId);await ctx.db.patch(jobId,{lease:{...j!.lease!,until:0}})});const b={...a,workerId:'second',fence:'2'};await t.mutation(internal.images.claim,b);await expect(t.mutation(internal.images.progress,{...a,status:'downloading'})).rejects.toThrow('lease');await t.mutation(internal.images.progress,{...b,status:'downloading',assetId:'actual-image-asset-id'});await expect(t.mutation(internal.images.progress,{...b,status:'downloading',assetId:'other-image-asset-id'})).rejects.toThrow('identity');expect((await t.run(ctx=>ctx.db.get(jobId)))?.projectPath).toBe('/project/original');expect(await t.run(ctx=>ctx.db.query('pointLedger').collect())).toHaveLength(1);});
it('validates uploaded bytes/hash and resumes an upload without another debit',async()=>{const {t,u,args,walletId}=await fixture(),jobId=await u.mutation(api.images.authorize,args),a={jobId,workerId:'w',fence:'f'};await t.mutation(internal.images.claim,a);await t.mutation(internal.images.progress,{...a,status:'generating',intent:true,projectPath:'/project/image'});await t.mutation(internal.images.progress,{...a,status:'uploading',assetId:'actual-image-asset-id'});const bytes=new Uint8Array([137,80,78,71,13,10,26,10,1,2,3]);const hash=Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',bytes))).map(n=>n.toString(16).padStart(2,'0')).join(''),key=`image:${hash}`;await t.mutation(internal.images.upload,{...a,key,type:'image/png',size:bytes.length});const storageId=await t.run(ctx=>ctx.storage.store(new Blob([bytes],{type:'image/png'})));await t.mutation(internal.images.progress,{...a,status:'failed',error:'upload failed',pause:true});await u.mutation(api.images.resume,{jobId});await t.action(internal.images.finish,{...a,key,storageId,width:720,height:1280});const j=await t.run(ctx=>ctx.db.get(jobId));expect(j?.fileId).toBe(storageId);expect(j?.status).toBe('completed');expect((await t.run(ctx=>ctx.db.get(walletId)))?.balance).toBe(9);expect(await t.run(ctx=>ctx.db.query('pointLedger').collect())).toHaveLength(1);});


it('charges one Mashhad point regardless of the observed Flow estimate',async()=>{for(const cost of [0,2,20]){const {t,u,args,walletId}=await fixture();await t.run(async ctx=>{const worker=await ctx.db.query('workers').first();await ctx.db.patch(worker!._id,{imageOptions:[{...option,cost}]});await ctx.db.insert('pointRates',{key:`${option.model}:original:0`,model:option.model,resolution:'original',seconds:0,points:cost,source:'flow',updatedAt:Date.now()})});const jobId=await u.mutation(api.images.authorize,{...args,option:{...option,cost}}),a={jobId,workerId:'pricing',fence:'once'};expect((await t.run(ctx=>ctx.db.get(jobId)))?.points).toBe(1);expect((await t.run(ctx=>ctx.db.get(jobId)))?.option.cost).toBe(cost);await t.mutation(internal.images.claim,a);await t.mutation(internal.images.progress,{...a,status:'generating',intent:true,projectPath:'/project/pricing'});expect((await t.run(ctx=>ctx.db.get(walletId)))?.balance).toBe(9);await u.mutation(api.images.resume,{jobId});expect((await t.run(ctx=>ctx.db.get(walletId)))?.balance).toBe(9);}});
