import {beforeEach,describe,it,expect,vi} from 'vitest';
import {convexTest} from 'convex-test';
import schema from './schema';
import {api,internal} from './_generated/api';
import {defaultTemplate,checkPlan,clipPrompts} from '../shared/pipeline';
const modules=import.meta.glob('./**/*.{ts,js}'),owner={subject:'owner',issuer:'https://owner.clerk.accounts.dev'};
const form={name:'قهوة بغداد',address:'بغداد الكرادة',phone:'07700000000',products:'قهوة',prompt:'Coffee',continuationPrompts:['Pour the coffee into the cup'],instructions:'',model:'Omni Flash',aspect:'9:16',duration:12,dialect:'العراقية'};
const option={model:'Omni Flash',actualModel:'Omni 1.1 Flash',seconds:6,resolution:'360p' as const,aspect:'9:16',cost:5};
beforeEach(()=>{vi.stubEnv('OWNER_SUBJECT',owner.subject);vi.stubEnv('CLERK_JWT_ISSUER_DOMAIN',owner.issuer);vi.stubEnv('WORKER_KEY_SHA256','');});
async function fixture(){const t=convexTest(schema,modules),u=t.withIdentity(owner);await t.run(async ctx=>{await ctx.db.insert('pointWallets',{subject:owner.subject,publicId:'MS-fixture',name:'owner fixture',balance:100,enabled:true,models:[option.model],maxClips:20,createdAt:1,updatedAt:1});await ctx.db.insert('pointRates',{key:`${option.model}:${option.resolution}:${option.seconds}`,model:option.model,resolution:option.resolution,seconds:option.seconds,points:5,updatedAt:1})});const requestId=await u.mutation(api.requests.save,{key:'pipeline-fixture',form,clipCount:2,referenceIds:[],submit:true});await t.mutation(internal.pipeline.presence,{workerId:'w',state:'online',options:[option],observedAt:Date.now()});const args={requestId,key:'authorized-click',option,count:2,template:defaultTemplate(form)};return {t,u,args};}
describe('per-request authorized pipeline (no browser or paid calls)',()=>{
 it('prepends the saved original to a continuation export without billing it or trimming it to the new unit',async()=>{
  const {t,u,args}=await fixture();
  const original=await t.run(async ctx=>{const storageId=await ctx.storage.store(new Blob(['original fixture'],{type:'video/mp4'}));await ctx.db.insert('uploads',{key:`video:${'a'.repeat(64)}`,storageId,name:'original.mp4',kind:'video',type:'video/mp4',size:16,createdAt:1});await ctx.db.insert('exports',{requestId:args.requestId,key:'prior-export',settings:{...args.template,clips:[{storageId,start:0,end:8}],duration:8,transition:0},texts:{name:'',address:'',phone:''},status:'completed',fileId:storageId,media:{duration:8,width:360,height:640,size:16,audio:true,sources:[{storageId,duration:8,width:360,height:640}]},createdAt:1,updatedAt:1});return storageId;});
  await t.run(ctx=>ctx.db.patch(args.requestId,{form:{...form,continuationSourceId:original}}));
  const jobId=await u.mutation(api.pipeline.authorize,args),a={jobId,workerId:'w',fence:'continuation'};
  await t.run(async ctx=>{const job=await ctx.db.get(jobId);await ctx.db.patch(jobId,{clips:job!.clips.map(c=>({...c,state:'uploaded' as const,storageId:original,duration:6,width:360,height:640}))});});
  await t.mutation(internal.pipeline.claim,a);const exportId=await t.mutation(internal.pipeline.startExport,a),output=await t.run(ctx=>ctx.db.get(exportId));
  expect(output!.settings.duration).toBe(20);expect(output!.settings.clips.map(c=>c.end)).toEqual([8,6,6]);
  expect(await t.mutation(internal.pipeline.startExport,a)).toBe(exportId);
  expect(await t.run(ctx=>ctx.db.query('pointLedger').collect())).toHaveLength(0);
  // A pre-fix completed job can be repaired by montage alone; preserve its prior final.
  await t.run(async ctx=>{await ctx.db.patch(exportId,{status:'completed',fileId:original});await ctx.db.patch(jobId,{stage:'completed'});await ctx.db.patch(args.requestId,{status:'مكتمل'});});
  const repaired=await u.mutation(api.pipeline.repairContinuation,{requestId:args.requestId});expect(await u.mutation(api.pipeline.repairContinuation,{requestId:args.requestId})).toBe(repaired);
  expect((await t.run(ctx=>ctx.db.get(repaired)))!.settings.duration).toBe(20);
  expect((await t.run(ctx=>ctx.db.get(exportId)))!.fileId).toBe(original);expect(await t.query(internal.pipeline.next,{})).toBeNull();
  expect(await t.query(internal.editing.pending,{})).toBe(repaired);expect(await t.run(ctx=>ctx.db.query('pointLedger').collect())).toHaveLength(0);
  await expect(t.mutation(api.pipeline.repairContinuation,{requestId:args.requestId})).rejects.toThrow();
 });
 it('refuses unknown original duration before authorizing any paid continuation',async()=>{
  const {t,u,args}=await fixture();const id=await t.run(async ctx=>{const storageId=await ctx.storage.store(new Blob(['unverified'],{type:'video/mp4'}));await ctx.db.insert('uploads',{key:`video:${'b'.repeat(64)}`,storageId,name:'unverified.mp4',kind:'video',type:'video/mp4',size:10,createdAt:1});return storageId});await t.run(ctx=>ctx.db.patch(args.requestId,{form:{...form,continuationSourceId:id}}));
  await expect(u.mutation(api.pipeline.authorize,args)).rejects.toThrow('غير متحققة');expect(await u.query(api.pipeline.state,{requestId:args.requestId})).toHaveLength(0);expect(await t.run(ctx=>ctx.db.query('pointLedger').collect())).toHaveLength(0);
 });
 it('uses verified model units and unique coherent prompts',()=>{checkPlan(option,2,12);expect(()=>checkPlan(option,2,16)).toThrow();expect(()=>checkPlan({...option,cost:NaN},2,12)).toThrow();const prompts=clipPrompts({...form,continuationPrompts:['Pour the coffee','Show the finished cup']},3);expect(new Set(prompts).size).toBe(3);expect(prompts[1]).not.toContain('Coffee');expect(prompts[2]).toContain('Show the finished cup');expect(()=>clipPrompts({...form,continuationPrompts:[]},2)).toThrow('مستقل');expect(()=>clipPrompts({...form,continuationPrompts:['Coffee']},2)).toThrow('يختلف');});
 it('rejects missing or repeated continuation before creating a paid job',async()=>{const {t,u,args}=await fixture();await t.run(ctx=>ctx.db.patch(args.requestId,{form:{...form,continuationPrompts:[]}}));await expect(u.mutation(api.pipeline.authorize,args)).rejects.toThrow('مستقل');await t.run(ctx=>ctx.db.patch(args.requestId,{form:{...form,continuationPrompts:[form.prompt]}}));await expect(u.mutation(api.pipeline.authorize,args)).rejects.toThrow('يختلف');expect(await u.query(api.pipeline.state,{requestId:args.requestId})).toHaveLength(0);});
 it('protects every owner operation and HTTP worker capability',async()=>{const {t,args}=await fixture();await expect(t.mutation(api.pipeline.authorize,args)).rejects.toThrow();await expect(t.query(api.pipeline.worker,{})).rejects.toThrow();for(const op of ['pipePresence','pipeNext','pipeClaim','pipeStage','pipeFile','pipeUpload','pipeComplete'])expect((await t.fetch('/runner',{method:'POST',body:JSON.stringify({op,args:{}})})).status).toBe(401);});
 it('deduplicates a retry and rejects unverified prices or a second active job',async()=>{const {t,u,args}=await fixture();const id=await u.mutation(api.pipeline.authorize,args);expect(await u.mutation(api.pipeline.authorize,args)).toBe(id);await expect(u.mutation(api.pipeline.authorize,{...args,key:'another-click'})).rejects.toThrow('يوجد تشغيل');await expect(u.mutation(api.pipeline.authorize,{...args,key:'wrong-cost',option:{...option,cost:1}})).rejects.toThrow('الكلفة');expect((await u.query(api.pipeline.state,{requestId:args.requestId})).length).toBe(1);expect((await t.run(ctx=>ctx.db.get(id)))?.form.phone).toBe('07700000000');});
 it('allows queued offline authorization with a recent quote; refuses stale options',async()=>{const {t,u,args}=await fixture();await t.mutation(internal.pipeline.presence,{workerId:'w',state:'offline'});const id=await u.mutation(api.pipeline.authorize,args);expect((await t.run(ctx=>ctx.db.get(id)))?.stage).toBe('queued');await t.run(async ctx=>{const w=await ctx.db.query('workers').first();await ctx.db.patch(w!._id,{observedAt:Date.now()-3600001})});await expect(u.mutation(api.pipeline.authorize,{...args,key:'stale-click'})).rejects.toThrow('حديثًا');});
 it('fences a restarted worker and never resets an uncertain paid intent',async()=>{const {t,u,args}=await fixture();const jobId=await u.mutation(api.pipeline.authorize,args),a={jobId,workerId:'one',fence:'1'};await t.mutation(internal.pipeline.claim,a);await t.mutation(internal.pipeline.clip,{...a,index:0,state:'intent',projectPath:'/project/original'});await expect(t.mutation(internal.pipeline.claim,{...a,workerId:'two',fence:'2'})).rejects.toThrow('owns execution');await t.run(async ctx=>{const j=await ctx.db.get(jobId);await ctx.db.patch(jobId,{lease:{...j!.lease!,until:0}})});const b={...a,workerId:'two',fence:'2'};await t.mutation(internal.pipeline.claim,b);await expect(t.mutation(internal.pipeline.clip,{...a,index:0,state:'submitted'})).rejects.toThrow('lease lost');await t.mutation(internal.pipeline.clip,{...b,index:0,state:'unknown'});await expect(t.mutation(internal.pipeline.clip,{...b,index:0,state:'intent',projectPath:'/project/new'})).rejects.toThrow('never resubmit');await expect(t.mutation(internal.pipeline.clip,{...b,index:1,state:'intent',projectPath:'/project/next'})).rejects.toThrow('authorization');});
 it('stop prevents later paid clicks; resume retains the original task identity',async()=>{const {t,u,args}=await fixture();const jobId=await u.mutation(api.pipeline.authorize,args),a={jobId,workerId:'w',fence:'1'};await t.mutation(internal.pipeline.claim,a);await u.mutation(api.pipeline.stop,{jobId});expect((await t.mutation(internal.pipeline.heartbeat,a)).stop).toBe(true);await expect(t.mutation(internal.pipeline.clip,{...a,index:0,state:'intent',projectPath:'/project/stopped'})).rejects.toThrow();await u.mutation(api.pipeline.resume,{jobId});await t.mutation(internal.pipeline.clip,{...a,index:0,state:'intent',projectPath:'/project/original'});await t.mutation(internal.pipeline.clip,{...a,index:0,state:'submitted',assetId:'actual-id'});await u.mutation(api.pipeline.stop,{jobId});await u.mutation(api.pipeline.resume,{jobId});const j=await t.run(ctx=>ctx.db.get(jobId));expect(j!.clips[0].assetId).toBe('actual-id');expect(j!.clips[0].state).toBe('submitted');});
 it('montage-only mode cannot create paid intents and failure keeps sources for upload/export retry',async()=>{const {t,u,args}=await fixture();const storageId=await t.run(ctx=>ctx.storage.store(new Blob(['contract fixture'],{type:'video/mp4'})));await t.run(ctx=>ctx.db.patch(args.requestId,{results:[{assetId:'original',storageId,duration:12,width:360,height:640}]}));const request={requestId:args.requestId,key:'existing-clips',template:args.template};const jobId=await u.mutation(api.pipeline.assembleExisting,request);expect(await u.mutation(api.pipeline.assembleExisting,request)).toBe(jobId);const a={jobId,workerId:'w',fence:'1'};await t.mutation(internal.pipeline.claim,a);await expect(t.mutation(internal.pipeline.clip,{...a,index:0,state:'intent',projectPath:'/project/never'})).rejects.toThrow();const exportId=await t.mutation(internal.pipeline.startExport,a);await t.mutation(internal.pipeline.stage,{...a,stage:'failed',pause:true,error:'upload failed'});await u.mutation(api.pipeline.resume,{jobId});expect(await t.mutation(internal.pipeline.startExport,a)).toBe(exportId);const j=await t.run(ctx=>ctx.db.get(jobId));expect(j!.clips[0].storageId).toBe(storageId);expect(j!.clips[0].state).toBe('uploaded');await expect(t.mutation(internal.pipeline.complete,a)).rejects.toThrow('unverified');});
 it('a stopped pipeline export cannot leak into the independent montage queue',async()=>{const {t,u,args}=await fixture();const storageId=await t.run(ctx=>ctx.storage.store(new Blob(['contract fixture'],{type:'video/mp4'})));await t.run(ctx=>ctx.db.patch(args.requestId,{results:[{assetId:'original',storageId,duration:12,width:360,height:640}]}));const jobId=await u.mutation(api.pipeline.assembleExisting,{requestId:args.requestId,key:'stop-isolation',template:args.template}),a={jobId,workerId:'w',fence:'1'};await t.mutation(internal.pipeline.claim,a);const exportId=await t.mutation(internal.pipeline.startExport,a);await u.mutation(api.pipeline.stop,{jobId});expect(await t.query(internal.editing.pending,{})).toBeNull();await expect(u.mutation(api.editing.retry,{exportId})).rejects.toThrow('التشغيل الكامل');});
});

it('blocks empty wallets and bills each paid intent once, preserving balance on authorization retries',async()=>{const {t,u,args}=await fixture();const wallet=await t.run(ctx=>ctx.db.query('pointWallets').first());await t.run(ctx=>ctx.db.patch(wallet!._id,{balance:0}));await expect(u.mutation(api.pipeline.authorize,args)).rejects.toThrow('اشحن');expect(await u.query(api.pipeline.state,{requestId:args.requestId})).toHaveLength(0);await t.run(ctx=>ctx.db.patch(wallet!._id,{balance:10}));const jobId=await u.mutation(api.pipeline.authorize,args);await u.mutation(api.pipeline.authorize,args);expect((await t.run(ctx=>ctx.db.get(wallet!._id)))?.balance).toBe(10);const a={jobId,workerId:'bill',fence:'bill'};await t.mutation(internal.pipeline.claim,a);await t.run(ctx=>ctx.db.patch(wallet!._id,{balance:0}));await expect(t.mutation(internal.pipeline.clip,{...a,index:0,state:'intent',projectPath:'/project/billing'})).rejects.toThrow('اشحن');expect(await t.run(ctx=>ctx.db.query('pointLedger').collect())).toHaveLength(0);await t.run(ctx=>ctx.db.patch(wallet!._id,{balance:10}));await t.mutation(internal.pipeline.clip,{...a,index:0,state:'intent',projectPath:'/project/billing'});expect((await t.run(ctx=>ctx.db.get(wallet!._id)))?.balance).toBe(5);await expect(t.mutation(internal.pipeline.clip,{...a,index:0,state:'intent',projectPath:'/project/billing'})).rejects.toThrow();await u.mutation(api.pipeline.stop,{jobId});await u.mutation(api.pipeline.resume,{jobId});expect((await t.run(ctx=>ctx.db.get(wallet!._id)))?.balance).toBe(5);expect(await t.run(ctx=>ctx.db.query('pointLedger').collect())).toHaveLength(1);});
