import {v,ConvexError} from 'convex/values';
import {flowConcurrency} from '../shared/concurrency';
import {query,mutation,internalQuery,internalMutation,internalAction} from './_generated/server';
import type {MutationCtx} from './_generated/server';
import type {Id} from './_generated/dataModel';
import {internal} from './_generated/api';
import {requireCustomer,ownedRequest} from './access';
import {walletPlan,chargeClip} from './walletBilling';
import {optionValidator,templateValidator,stageValidator,clipStateValidator} from './pipelineValidators';
import {checkPlan,clipPrompts} from '../shared/pipeline';
import {canonical,validateEdit} from '../shared/editing';
import {validateFile,validateSignature} from '../shared/validation';
import {continuationSource,continuationEdit} from './continuation';
const identity={jobId:v.id('pipelines'),workerId:v.string(),fence:v.string()};
export const worker=query({args:{},handler:async ctx=>{await requireCustomer(ctx);const w=await ctx.db.query('workers').withIndex('by_key',q=>q.eq('key','pipeline')).unique();if(!w)return null;return {state:w.state,seenAt:w.seenAt,observedAt:w.observedAt,options:w.options,filmReady:w.filmReady,imageOptions:w.imageOptions,imageObservedAt:w.imageObservedAt,imageError:w.imageError,error:w.error};}});
export const state=query({args:{requestId:v.id('requests')},handler:async(ctx,a)=>{await ownedRequest(ctx,a.requestId);return ctx.db.query('pipelines').withIndex('by_request',q=>q.eq('requestId',a.requestId)).order('desc').collect();}});
export const authorize=mutation({args:{requestId:v.id('requests'),key:v.string(),option:optionValidator,count:v.number(),template:templateValidator},handler:async(ctx,a)=>{
 const owner=await requireCustomer(ctx);await ownedRequest(ctx,a.requestId);const old=await ctx.db.query('pipelines').withIndex('by_key',q=>q.eq('key',a.key)).unique();if(old){if(old.requestId!==a.requestId||canonical(old.option)!==canonical(a.option)||old.clips.length!==a.count||canonical(old.template)!==canonical(a.template))throw new ConvexError('مفتاح المحاولة مرتبط بإعدادات مختلفة.');return old._id;}
 if(!/^[a-zA-Z0-9-]{8,100}$/.test(a.key))throw new ConvexError('Invalid attempt key');
 const r=await ctx.db.get(a.requestId);if(!r)throw new ConvexError('الطلب غير موجود.');checkPlan(a.option,a.count,r.form.duration);const source=await continuationSource(ctx,r.form.continuationSourceId,r.form.aspect,r.subject??process.env.OWNER_SUBJECT);continuationEdit(a.template,[{storageId:'planned',start:0,end:r.form.duration}],r.form.duration,source);
 const w=await ctx.db.query('workers').withIndex('by_key',q=>q.eq('key','pipeline')).unique();if(!w||Date.now()-w.observedAt>3600000||!w.options.some(o=>canonical(o)===canonical(a.option)))throw new ConvexError('الخيارات أو الكلفة غير متحققة حديثًا؛ شغّل Worker لتحديثها.');
 if(a.option.model!==r.form.model||a.option.aspect!==r.form.aspect||(a.template.aspect??'9:16')!==r.form.aspect)throw new ConvexError('إعدادات الموديل والمقاس لا تطابق الطلب.');
 validateEdit({...a.template,clips:[{storageId:'planned',start:0,end:r.form.duration}],duration:r.form.duration,transition:0});
 if(a.template.logo.enabled){const f=r.logoId?await ctx.db.query('uploads').withIndex('by_storage',q=>q.eq('storageId',r.logoId)).unique():null;if(!f||!['image/png','image/webp'].includes(f.type))throw new ConvexError('اختر شعار PNG/WebP شفافًا أو عطّل الشعار.');}
 const jobs=await ctx.db.query('pipelines').withIndex('by_request',q=>q.eq('requestId',r._id)).collect();if(jobs.some(j=>!j.paused&&!['completed','failed','stopped'].includes(j.stage)))throw new ConvexError('يوجد تشغيل لهذا الطلب؛ لا ترسله مرتين.');
 const billing=await walletPlan(ctx,owner.subject,a.option,a.count);
 const id=await ctx.db.insert('pipelines',{billing,continuationSource:source,key:a.key,requestId:r._id,mode:'generate',form:r.form,logoId:r.logoId,referenceIds:r.referenceIds,option:a.option,template:a.template,clips:clipPrompts(r.form,a.count).map((prompt,index)=>({index,prompt,state:'pending' as const})),stage:'queued',authorizedAt:Date.now(),updatedAt:Date.now(),stopRequested:false,paused:false});
 await ctx.db.patch(r._id,{status:'بانتظار التشغيل',estimatedPoints:a.option.cost*a.count,error:undefined,updatedAt:Date.now()});return id;
}});
export const assembleExisting=mutation({args:{requestId:v.id('requests'),key:v.string(),template:templateValidator},handler:async(ctx,a)=>{
 await ownedRequest(ctx,a.requestId);const old=await ctx.db.query('pipelines').withIndex('by_key',q=>q.eq('key',a.key)).unique();if(old){if(old.requestId!==a.requestId||canonical(old.template)!==canonical(a.template))throw new ConvexError('Key conflict');return old._id;}
 if(!/^[a-zA-Z0-9-]{8,100}$/.test(a.key))throw new ConvexError('Invalid attempt key');const active=await ctx.db.query('pipelines').withIndex('by_request',q=>q.eq('requestId',a.requestId)).collect();if(active.some(j=>!j.paused&&j.stage!=='completed'))throw new ConvexError('يوجد تشغيل لهذا الطلب.');const r=await ctx.db.get(a.requestId);if(!r?.results?.length)throw new ConvexError('لا توجد مقاطع متحققة لهذا الطلب.');const parts=r.results;const option={model:r.form.model,actualModel:'مقاطع محفوظة — دون توليد',seconds:r.form.duration/parts.length,resolution:'360p' as const,aspect:r.form.aspect,cost:0};
 const source=await continuationSource(ctx,r.form.continuationSourceId,r.form.aspect,r.subject??process.env.OWNER_SUBJECT);continuationEdit(a.template,parts.map(p=>({storageId:p.storageId,start:0,end:Math.min(option.seconds,p.duration)})),r.form.duration,source);
 return ctx.db.insert('pipelines',{continuationSource:source,key:a.key,requestId:r._id,mode:'existing',form:r.form,logoId:(await ctx.db.query('edits').withIndex('by_request',q=>q.eq('requestId',r._id)).unique())?.logoId??r.logoId,referenceIds:[],option,template:a.template,clips:parts.map((p,index)=>({index,prompt:'مقطع محفوظ؛ لا توليد في هذا الاختبار',state:'uploaded' as const,assetId:p.assetId,storageId:p.storageId,duration:p.duration,width:p.width,height:p.height})),stage:'queued',authorizedAt:Date.now(),updatedAt:Date.now(),stopRequested:false,paused:false});
}});
// Repair old completed continuation-only exports. This queues montage only and never touches paid intents.
export const repairContinuation=mutation({args:{requestId:v.id('requests')},handler:async(ctx,a)=>{
 const r=await ownedRequest(ctx,a.requestId);if(!r?.form.continuationSourceId||r.status!=='مكتمل')throw new ConvexError('لا توجد تكملة مكتملة قابلة للدمج.');
 const jobs=await ctx.db.query('pipelines').withIndex('by_request',q=>q.eq('requestId',r._id)).order('desc').collect(),job=jobs.find(j=>j.stage==='completed');
 if(!job||jobs.some(j=>!j.paused&&!['completed','failed','stopped'].includes(j.stage))||job.clips.some(c=>c.state!=='uploaded'||!c.storageId||!c.duration))throw new ConvexError('المقاطع غير جاهزة للدمج.');
 const key=`continuation-repair-${r._id}`,previous=await ctx.db.query('exports').withIndex('by_key',q=>q.eq('key',key)).unique();if(previous)return previous._id;
 const active=await ctx.db.query('exports').withIndex('by_request',q=>q.eq('requestId',r._id)).collect();if(active.some(e=>!['completed','failed'].includes(e.status)))throw new ConvexError('هناك مونتاج قيد التنفيذ.');
 const source=job.continuationSource??await continuationSource(ctx,r.form.continuationSourceId,r.form.aspect,r.subject??process.env.OWNER_SUBJECT),settings=continuationEdit(job.template,job.clips.map(c=>({storageId:c.storageId!,start:0,end:Math.min(job.option.seconds,c.duration!)})),job.form.duration,source);
 return ctx.db.insert('exports',{key,requestId:r._id,settings,logoId:job.logoId,texts:{name:r.form.name,address:r.form.address,phone:r.form.phone},status:'queued',history:[{status:'queued',at:Date.now()}],createdAt:Date.now(),updatedAt:Date.now()});
}});
export const stop=mutation({args:{jobId:v.id('pipelines')},handler:async(ctx,a)=>{const j=await ctx.db.get(a.jobId);if(j)await ownedRequest(ctx,j.requestId);else await requireCustomer(ctx);if(!j||j.stage==='completed')return;await ctx.db.patch(j._id,{stopRequested:true,paused:true,stage:'stopped',updatedAt:Date.now(),error:'الإيقاف يمنع الخطوات اللاحقة؛ لا يضمن إلغاء مهمة Flow أو استرجاع النقاط.'});await ctx.db.patch(j.requestId,{status:'متوقف',updatedAt:Date.now()});}});
export const resume=mutation({args:{jobId:v.id('pipelines')},handler:async(ctx,a)=>{const j=await ctx.db.get(a.jobId);if(j)await ownedRequest(ctx,j.requestId);else await requireCustomer(ctx);if(!j||j.stage==='completed')return;const others=await ctx.db.query('pipelines').withIndex('by_request',q=>q.eq('requestId',j.requestId)).collect();if(others.some(p=>p._id!==j._id&&!p.paused&&p.stage!=='completed'))throw new ConvexError('يوجد تشغيل آخر لهذا الطلب.');await ctx.db.patch(j._id,{stopRequested:false,paused:false,stage:'queued',error:undefined,updatedAt:Date.now()});await ctx.db.patch(j.requestId,{status:'بانتظار التشغيل',updatedAt:Date.now()});}});
export const presence=internalMutation({args:{workerId:v.string(),state:v.string(),filmReady:v.optional(v.boolean()),flowBalance:v.optional(v.object({credits:v.optional(v.number()),at:v.number(),error:v.optional(v.string())})),options:v.optional(v.array(optionValidator)),observedAt:v.optional(v.number()),error:v.optional(v.string())},handler:async(ctx,a)=>{if(!['online','offline','login','inspecting'].includes(a.state)||(a.error?.length??0)>1200)throw new ConvexError('Invalid worker state');if(a.options)for(const o of a.options)checkPlan(o,1,o.seconds);const w=await ctx.db.query('workers').withIndex('by_key',q=>q.eq('key','pipeline')).unique();if(w&&Date.now()-w.seenAt<30000&&w.workerId!==a.workerId&&w.state!=='offline')throw new ConvexError('Another Worker is online');if(a.flowBalance&&(!Number.isSafeInteger(a.flowBalance.at)||a.flowBalance.at>Date.now()+60000||a.flowBalance.at<Date.now()-3600000||a.flowBalance.credits!==undefined&&(!Number.isSafeInteger(a.flowBalance.credits)||a.flowBalance.credits<0)||(a.flowBalance.error?.length??0)>500))throw new ConvexError('Invalid balance observation');const data={flowBalance:a.flowBalance??w?.flowBalance,filmReady:a.filmReady??false,key:'pipeline',workerId:a.workerId,state:a.state,seenAt:Date.now(),observedAt:a.observedAt??w?.observedAt??0,options:a.options??w?.options??[],error:a.error};if(w)await ctx.db.patch(w._id,data);else await ctx.db.insert('workers',data);}});
export const next=internalQuery({args:{},handler:async ctx=>{
 const jobs=await ctx.db.query('pipelines').collect(),now=Date.now(),active=jobs.filter(j=>j.lease&&j.lease.until>now);
 if(active.length>=flowConcurrency(process.env.FLOW_CONCURRENCY)||(await ctx.db.query('filmProductions').collect()).some(j=>j.lease&&j.lease.until>now)||(await ctx.db.query('imageJobs').collect()).some(j=>j.lease&&j.lease.until>now))return null;
 const requests=await ctx.db.query('requests').collect(),subject=(id:Id<'requests'>)=>requests.find(r=>r._id===id)?.subject??process.env.OWNER_SUBJECT;
 return jobs.find(j=>!j.paused&&!j.stopRequested&&j.stage!=='completed'&&(!j.lease||j.lease.until<=now)&&!active.some(p=>subject(p.requestId)===subject(j.requestId)))?._id??null;
}});
export const get=internalQuery({args:{jobId:v.id('pipelines')},handler:async(ctx,a)=>ctx.db.get(a.jobId)});
async function locked(ctx:MutationCtx,a:{jobId:Id<'pipelines'>;workerId:string;fence:string}){const j=await ctx.db.get(a.jobId);if(!j||j.lease?.workerId!==a.workerId||j.lease.fence!==a.fence||j.lease.until<Date.now())throw new ConvexError('Pipeline lease lost');return j;}
export const claim=internalMutation({args:identity,handler:async(ctx,a)=>{
 const j=await ctx.db.get(a.jobId),now=Date.now();if(!j||j.paused||j.stopRequested||j.stage==='completed')throw new ConvexError('Request paused or complete');
 if(j.lease&&j.lease.until>now){if(j.lease.workerId===a.workerId&&j.lease.fence===a.fence)return j;throw new ConvexError('Another Worker owns execution');}
 const active=(await ctx.db.query('pipelines').collect()).filter(p=>p.lease&&p.lease.until>now),r=await ctx.db.get(j.requestId);
 for(const p of active){const other=await ctx.db.get(p.requestId);if((other?.subject??process.env.OWNER_SUBJECT)===(r?.subject??process.env.OWNER_SUBJECT))throw new ConvexError('Another request for this customer owns execution');}
 if(active.length>=flowConcurrency(process.env.FLOW_CONCURRENCY)||(await ctx.db.query('filmProductions').collect()).some(p=>p.lease&&p.lease.until>now)||(await ctx.db.query('imageJobs').collect()).some(p=>p.lease&&p.lease.until>now))throw new ConvexError('Another Worker owns execution');
 await ctx.db.patch(j._id,{lease:{workerId:a.workerId,fence:a.fence,until:now+60000}});return j;
}});
export const heartbeat=internalMutation({args:identity,handler:async(ctx,a)=>{const j=await locked(ctx,a);await ctx.db.patch(j._id,{lease:{workerId:a.workerId,fence:a.fence,until:Date.now()+60000}});return {stop:j.stopRequested,paused:j.paused};}});
export const release=internalMutation({args:identity,handler:async(ctx,a)=>{const j=await locked(ctx,a);await ctx.db.patch(j._id,{lease:{...j.lease!,until:0}});}});
export const stage=internalMutation({args:{...identity,stage:stageValidator,error:v.optional(v.string()),pause:v.optional(v.boolean())},handler:async(ctx,a)=>{const j=await locked(ctx,a);if(a.stage==='completed'||j.stage==='completed')throw new ConvexError('Use final verified export');if((a.error?.length??0)>1200)throw new ConvexError('Invalid diagnostic');const phase=j.stopRequested?'stopped':a.stage;await ctx.db.patch(j._id,{stage:phase,error:a.error,paused:a.pause??j.paused,updatedAt:Date.now()});const statuses={queued:'بانتظار التشغيل',generating:'قيد التوليد',downloading:'قيد التنزيل',montage:'قيد المونتاج',uploading:'قيد الرفع',failed:'فشل',stopped:'متوقف',login:'يحتاج تسجيل دخول',uncertain:'النتيجة غير محسومة'} as const;await ctx.db.patch(j.requestId,{status:statuses[phase],error:a.error,updatedAt:Date.now()});}});
export const clip=internalMutation({args:{...identity,index:v.number(),percent:v.optional(v.number()),state:clipStateValidator,projectPath:v.optional(v.string()),assetId:v.optional(v.string()),error:v.optional(v.string())},handler:async(ctx,a)=>{
 if(a.percent!==undefined&&(!Number.isFinite(a.percent)||a.percent<0||a.percent>99||a.state!=='submitted'))throw new ConvexError('Invalid observed progress');
 const j=await locked(ctx,a),c=j.clips[a.index];if(!c||!Number.isSafeInteger(a.index))throw new ConvexError('Invalid clip');
 if(a.projectPath&&!/^\/project\/[a-zA-Z0-9-]+$/.test(a.projectPath)||a.assetId&&!/^[a-zA-Z0-9_-]{1,200}$/.test(a.assetId)||(a.error?.length??0)>1200)throw new ConvexError('Invalid identity');
 const allowed:Record<string,string[]>={pending:['intent'],intent:['submitted','unknown'],unknown:['submitted','unknown','downloaded'],submitted:['submitted','unknown','downloaded'],downloaded:['downloaded'],uploaded:['uploaded'],failed:[]};if(!allowed[c.state].includes(a.state))throw new ConvexError('Unsafe clip transition; never resubmit intent');
 if(a.state==='intent'&&(j.mode!=='generate'||j.stopRequested||j.paused||!a.projectPath||j.clips.slice(0,a.index).some(p=>p.state!=='uploaded')))throw new ConvexError('No paid authorization for this clip');
 if(a.state==='intent')await chargeClip(ctx,j,a.index);
 const clips=[...j.clips];clips[a.index]={...c,percent:a.percent??c.percent,state:a.state,projectPath:a.projectPath??c.projectPath,assetId:a.assetId??c.assetId,error:a.error,...(a.state==='intent'?{submittedAt:Date.now()}:{})};await ctx.db.patch(j._id,{clips,updatedAt:Date.now()});
}});
export const fileAccess=internalQuery({args:{jobId:v.id('pipelines'),storageId:v.id('_storage')},handler:async(ctx,a)=>{const j=await ctx.db.get(a.jobId);return !!j&&(j.form.continuationSourceId===a.storageId||j.logoId===a.storageId||j.referenceIds.includes(a.storageId)||j.clips.some(c=>c.storageId===a.storageId)||j.finalId===a.storageId);}});
export const upload=internalMutation({args:{...identity,index:v.number(),key:v.string(),size:v.number()},handler:async(ctx,a)=>{const j=await locked(ctx,a);if(j.stopRequested||j.paused||j.clips[a.index]?.state!=='downloaded')throw new ConvexError('Source is not ready for upload');validateFile('video/mp4',a.size,'video');if(!/^video:[a-f0-9]{64}$/.test(a.key))throw new ConvexError('Invalid hash');const f=await ctx.db.query('uploads').withIndex('by_key',q=>q.eq('key',a.key)).unique();if(f?.storageId)return {storageId:f.storageId,url:null};if(!f)await ctx.db.insert('uploads',{key:a.key,name:`${j._id}-${a.index}.mp4`,kind:'video',type:'video/mp4',size:a.size,createdAt:Date.now()});return {storageId:null,url:await ctx.storage.generateUploadUrl()};}});
const sourceArgs={...identity,index:v.number(),key:v.string(),storageId:v.id('_storage'),duration:v.number(),width:v.number(),height:v.number()};
export const finish=internalAction({args:sourceArgs,handler:async(ctx,a):Promise<void>=>{const f=await ctx.runQuery(internal.files.ticket,{key:a.key}),blob=await ctx.storage.get(a.storageId);if(!f||!blob||blob.type!=='video/mp4'||blob.size!==f.size)throw new ConvexError('Invalid source');validateFile(blob.type,blob.size,'video');validateSignature(new Uint8Array(await blob.slice(0,32).arrayBuffer()),blob.type);const m=await ctx.runQuery(internal.runner.metadata,{storageId:a.storageId});if(a.key!==`video:${m?.hash}`)throw new ConvexError('Hash mismatch');const storageId=await ctx.runMutation(internal.files.register,{key:a.key,storageId:a.storageId});await ctx.runMutation(internal.pipeline.source,{...a,storageId});}});
export const source=internalMutation({args:sourceArgs,handler:async(ctx,a)=>{const j=await locked(ctx,a),c=j.clips[a.index],f=await ctx.db.query('uploads').withIndex('by_storage',q=>q.eq('storageId',a.storageId)).unique();if(!c||!['downloaded','uploaded'].includes(c.state)||!c.assetId||f?.key!==a.key||!Number.isFinite(a.duration)||a.duration<=0||![a.width,a.height].every(n=>Number.isSafeInteger(n)&&n>0&&n<=8192))throw new ConvexError('Unverified source');if(c.storageId&&c.storageId!==a.storageId)throw new ConvexError('Source conflict');const clips=[...j.clips];clips[a.index]={...c,state:'uploaded',storageId:a.storageId,duration:a.duration,width:a.width,height:a.height};await ctx.db.patch(j._id,{clips,updatedAt:Date.now()});const r=await ctx.db.get(j.requestId);const results=r!.results??[];if(!results.some(p=>p.assetId===c.assetId))results.push({assetId:c.assetId,storageId:a.storageId,duration:a.duration,width:a.width,height:a.height});await ctx.db.patch(j.requestId,{results,videoId:r!.videoId??a.storageId,videoSource:r!.videoSource??'runner',updatedAt:Date.now()});}});
export const startExport=internalMutation({args:identity,handler:async(ctx,a)=>{const j=await locked(ctx,a);if(j.stopRequested||j.paused||j.clips.some(c=>c.state!=='uploaded'||!c.storageId||!c.duration))throw new ConvexError('Sources incomplete');if(j.exportId)return j.exportId;const source=j.continuationSource??await continuationSource(ctx,j.form.continuationSourceId,j.form.aspect);const settings=continuationEdit(j.template,j.clips.map(c=>({storageId:c.storageId!,start:0,end:Math.min(j.option.seconds,c.duration!)})),j.form.duration,source);const exportId=await ctx.db.insert('exports',{key:`pipeline-${j._id}`,requestId:j.requestId,settings,logoId:j.logoId,texts:{name:j.form.name,address:j.form.address,phone:j.form.phone},status:'queued',history:[{status:'queued',at:Date.now()}],createdAt:Date.now(),updatedAt:Date.now()});await ctx.db.patch(j._id,{exportId,stage:'montage',updatedAt:Date.now()});return exportId;}});
export const exportState=internalQuery({args:{jobId:v.id('pipelines')},handler:async(ctx,a)=>{const j=await ctx.db.get(a.jobId);return j?.exportId?ctx.db.get(j.exportId):null;}});
export const complete=internalMutation({args:identity,handler:async(ctx,a)=>{const j=await locked(ctx,a),e=j.exportId?await ctx.db.get(j.exportId):null;if(e?.status!=='completed'||!e.fileId||e.requestId!==j.requestId)throw new ConvexError('Final output unverified');await ctx.db.patch(j._id,{finalId:e.fileId,stage:j.stopRequested?'stopped':'completed',error:undefined,updatedAt:Date.now()});if(!j.stopRequested)await ctx.db.patch(j.requestId,{status:'مكتمل',error:undefined,updatedAt:Date.now()});}});
