import { beforeEach,describe,it,expect,vi } from 'vitest';
import { convexTest } from 'convex-test';
import schema from './schema';
import { api,internal } from './_generated/api';
const modules=import.meta.glob('./**/*.{ts,js}');
const owner={subject:'owner',issuer:'https://owner.clerk.accounts.dev'};
const input={key:'runner-test',form:{name:'Test',address:'Test',phone:'077',products:'Coffee',prompt:'Coffee',instructions:'',model:'Omni Flash',aspect:'9:16',duration:6,dialect:'العراقية'},clipCount:1,referenceIds:[],submit:true};
beforeEach(()=>{vi.stubEnv('OWNER_SUBJECT',owner.subject);vi.stubEnv('CLERK_JWT_ISSUER_DOMAIN',owner.issuer);vi.stubEnv('WORKER_KEY_SHA256','');});
describe('runner concurrency and recovery',()=>{
 it('requires worker authentication for every HTTP operation',async()=>{const t=convexTest(schema,modules);for(const op of ['claim','progress','get','upload','finish','file'])expect((await t.fetch('/runner',{method:'POST',body:JSON.stringify({op,args:{}})})).status).toBe(401);});
 it('permits one worker, rejects a second and fences stale writes',async()=>{const t=convexTest(schema,modules),u=t.withIdentity(owner);const requestId=await u.mutation(api.requests.save,input);const a={requestId,workerId:'a',fence:'1'};await t.mutation(internal.runner.claim,a);await expect(t.mutation(internal.runner.claim,{requestId,workerId:'b',fence:'2'})).rejects.toThrow('Another worker');await expect(t.mutation(internal.runner.progress,{...a,fence:'wrong',phase:'intent',status:'قيد التوليد'})).rejects.toThrow('lease lost');});
 it('retains ambiguous intent after a crash and never allows resubmission',async()=>{const t=convexTest(schema,modules),u=t.withIdentity(owner);const requestId=await u.mutation(api.requests.save,input),a={requestId,workerId:'a',fence:'1'};await t.mutation(internal.runner.claim,a);await t.mutation(internal.runner.progress,{...a,phase:'intent',status:'قيد التوليد'});await t.run(async ctx=>{const row=await ctx.db.get(requestId);await ctx.db.patch(requestId,{runner:{...row!.runner!,leaseUntil:0}})});const next={requestId,workerId:'b',fence:'2'};const row=await t.mutation(internal.runner.claim,next);expect(row.runner.phase).toBe('intent');await expect(t.mutation(internal.runner.progress,{...next,phase:'intent',status:'قيد التوليد'})).rejects.toThrow('already attempted');await expect(t.mutation(internal.runner.heartbeat,a)).rejects.toThrow('lease lost');await t.mutation(internal.runner.progress,{...next,phase:'unknown',status:'قيد التوليد',error:'Manual verification needed'});expect((await u.query(api.requests.list))[0].runner?.phase).toBe('unknown');});
 it('cannot complete with an unverified file or without generation',async()=>{const t=convexTest(schema,modules),u=t.withIdentity(owner);const requestId=await u.mutation(api.requests.save,input),a={requestId,workerId:'a',fence:'1'};await t.mutation(internal.runner.claim,a);await expect(t.mutation(internal.runner.progress,{...a,phase:'prepared',status:'مكتمل'})).rejects.toThrow('verified result');const storageId=await t.run(ctx=>ctx.storage.store(new Blob(['fake'],{type:'video/mp4'})));await expect(t.mutation(internal.runner.result,{...a,key:'video:fake',storageId,assetId:'asset',duration:6,width:360,height:640})).rejects.toThrow('No submitted job');});
 it('blocks spending on another request after the single trial intent',async()=>{const t=convexTest(schema,modules),u=t.withIdentity(owner);const first=await u.mutation(api.requests.save,input);const second=await u.mutation(api.requests.save,{...input,key:'second'});const a={requestId:first,workerId:'a',fence:'1'},b={requestId:second,workerId:'a',fence:'2'};await t.mutation(internal.runner.claim,a);await t.mutation(internal.runner.progress,{...a,phase:'intent',status:'قيد التوليد'});await t.mutation(internal.runner.claim,b);await expect(t.mutation(internal.runner.progress,{...b,phase:'intent',status:'قيد التوليد'})).rejects.toThrow('single authorized trial');});
 it('stores separate verified results idempotently and does not call one clip a complete multi-clip request',async()=>{
 const t=convexTest(schema,modules),u=t.withIdentity(owner);const requestId=await u.mutation(api.requests.save,{...input,clipCount:2});const a={requestId,workerId:'a',fence:'1'};await t.mutation(internal.runner.claim,a);await t.mutation(internal.runner.progress,{...a,phase:'intent',status:'قيد التوليد',requiredClips:2});await t.mutation(internal.runner.progress,{...a,phase:'submitted',status:'قيد التوليد'});
 for(let i=0;i<2;i++){const bytes=new Uint8Array([0,0,0,24,102,116,121,112,105,115,111,109,0,0,0,i]);const hash=Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',bytes))).map(n=>n.toString(16).padStart(2,'0')).join(''),key=`video:${hash}`;await u.mutation(api.files.begin,{key,kind:'video',name:'test.mp4',type:'video/mp4',size:bytes.length});const storageId=await t.run(ctx=>ctx.storage.store(new Blob([bytes],{type:'video/mp4'})));await u.action(api.files.finish,{key,storageId});const args={...a,key,storageId,assetId:`asset-${i}`,duration:6,width:360,height:640};await t.mutation(internal.runner.result,args);await t.mutation(internal.runner.result,args);const row=(await u.query(api.requests.list))[0];expect(row.results).toHaveLength(i+1);expect(row.status).toBe(i===0?'قيد التنزيل':'مكتمل');}
 await expect(t.mutation(internal.runner.progress,{...a,phase:'uploaded',status:'قيد التوليد'})).rejects.toThrow('immutable');
 });
 it('serves large media as authenticated bounded chunks',async()=>{
 const t=convexTest(schema,modules),u=t.withIdentity(owner);const bytes=new Uint8Array(20*1024*1024);bytes.set([0,0,0,24,102,116,121,112,105,115,111,109]);bytes[8*1024*1024]=42;bytes[16*1024*1024]=99;const hash=Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',bytes))).map(n=>n.toString(16).padStart(2,'0')).join(''),key=`video:${hash}`;
 await u.mutation(api.files.begin,{key,kind:'video',name:'storage-contract.mp4',type:'video/mp4',size:bytes.length});const storageId=await t.run(ctx=>ctx.storage.store(new Blob([bytes],{type:'video/mp4'})));await u.action(api.files.finish,{key,storageId});expect((await u.fetch(`/files?id=${storageId}`)).status).toBe(413);expect((await t.fetch(`/files?id=${storageId}&metadata=1`)).status).toBe(401);expect((await t.fetch(`/files?id=${storageId}&offset=0`)).status).toBe(401);
 for(let i=0;i<3;i++){const r=await u.fetch(`/files?id=${storageId}&offset=${i*8*1024*1024}`);const part=new Uint8Array(await r.arrayBuffer());expect(part.length).toBe((i===2?4:8)*1024*1024);expect(part[0]).toBe([0,42,99][i]);}
 });
});
