import { defineSchema, defineTable } from 'convex/server';
import { v } from 'convex/values';
import { formValidator, kindValidator, statusValidator } from './validators';
import {editValidator,exportStatus,mediaValidator} from './editValidators';
import {optionValidator,templateValidator,stageValidator,clipValidator} from './pipelineValidators';
import {imageOptionValidator,imageStatusValidator} from '../shared/images';
import {filmClip,filmPhase} from './filmProductionValidators';
import {filmSettings,filmPlan} from './filmValidators';
const runner=v.object({workerId:v.string(),fence:v.string(),leaseUntil:v.number(),phase:v.union(v.literal('prepared'),v.literal('intent'),v.literal('submitted'),v.literal('unknown'),v.literal('downloaded'),v.literal('uploaded')),projectPath:v.optional(v.string()),clipSeconds:v.optional(v.number()),requiredClips:v.optional(v.number())});
export default defineSchema({
 socialDeletionReceipts:defineTable({code:v.string(),completedAt:v.number()}).index('by_code',['code']),
 socialAuth:defineTable({subject:v.string(),platform:v.union(v.literal('facebook'),v.literal('instagram')),stateHash:v.string(),returnOrigin:v.string(),expiresAt:v.number()}).index('by_state',['stateHash']).index('by_subject',['subject']),
 socialAccounts:defineTable({subject:v.string(),platform:v.union(v.literal('facebook'),v.literal('instagram')),providerUserId:v.string(),accountId:v.string(),name:v.string(),pageId:v.string(),token:v.string(),selected:v.boolean(),connectedAt:v.number()}).index('by_subject',['subject']).index('by_provider_user',['providerUserId']),
 socialPosts:defineTable({subject:v.string(),key:v.string(),accountId:v.id('socialAccounts'),platform:v.union(v.literal('facebook'),v.literal('instagram')),storageId:v.id('_storage'),caption:v.string(),stage:v.union(v.literal('preparing'),v.literal('processing'),v.literal('publishing'),v.literal('accepted'),v.literal('published'),v.literal('failed'),v.literal('uncertain')),containerId:v.optional(v.string()),providerId:v.optional(v.string()),error:v.optional(v.string()),createdAt:v.number()}).index('by_key',['key']).index('by_subject',['subject']),
 aiWallets:defineTable({subject:v.string(),walletId:v.id('pointWallets'),balanceMicros:v.number(),heldMicros:v.number(),spentMicros:v.number(),updatedAt:v.number()}).index('by_subject',['subject']).index('by_wallet',['walletId']),
 aiLedger:defineTable({key:v.string(),walletId:v.id('aiWallets'),kind:v.union(v.literal('credit'),v.literal('debit'),v.literal('reserve'),v.literal('settle')),amountMicros:v.number(),balanceAfter:v.number(),heldAfter:v.number(),note:v.string(),actor:v.string(),createdAt:v.number()}).index('by_key',['key']).index('by_wallet',['walletId']),
 filmProductions:defineTable({manualMerge:v.optional(v.boolean()),mergeRequested:v.optional(v.boolean()),previousFinalId:v.optional(v.id('_storage')),projectId:v.id('filmProjects'),episodeId:v.id('filmEpisodes'),subject:v.string(),key:v.string(),mode:v.union(v.literal('generate'),v.literal('existing')),option:optionValidator,clips:v.array(filmClip),stage:filmPhase,paused:v.boolean(),stopRequested:v.boolean(),walletId:v.optional(v.id('pointWallets')),unitPoints:v.number(),reserved:v.number(),spent:v.number(),refund:v.number(),settings:v.object({style:v.string(),dialect:v.string(),duration:v.number()}),plan:filmPlan,references:v.array(v.object({_id:v.string(),kind:v.string(),name:v.string(),description:v.string(),fileId:v.optional(v.id('_storage'))})),createdAt:v.number(),updatedAt:v.number(),finalId:v.optional(v.id('_storage')),media:v.optional(mediaValidator),percent:v.optional(v.number()),error:v.optional(v.string()),lease:v.optional(v.object({workerId:v.string(),fence:v.string(),until:v.number()}))}).index('by_project',['projectId']).index('by_key',['key']),
 filmProjects:defineTable({productionOption:v.optional(optionValidator),settings:v.optional(filmSettings),referenceRevision:v.optional(v.number()),subject:v.string(),key:v.string(),title:v.string(),brief:v.string(),budgetMicros:v.number(),spentMicros:v.number(),heldMicros:v.number(),createdAt:v.number(),updatedAt:v.number()}).index('by_subject',['subject']).index('by_key',['key']),
 filmTurns:defineTable({aiWalletId:v.optional(v.id('aiWallets')),planRequest:v.optional(v.object({previousPlans:v.optional(v.string()),episode:v.number(),seconds:v.number(),snapshot:v.string(),revision:v.number(),brief:v.string()})),projectId:v.id('filmProjects'),subject:v.string(),key:v.string(),userText:v.string(),status:v.union(v.literal('queued'),v.literal('running'),v.literal('completed'),v.literal('failed'),v.literal('unknown')),reply:v.optional(v.string()),brief:v.optional(v.string()),error:v.optional(v.string()),reserveMicros:v.number(),dailyKey:v.string(),costMicros:v.optional(v.number()),inputTokens:v.optional(v.number()),outputTokens:v.optional(v.number()),responseId:v.optional(v.string()),createdAt:v.number(),updatedAt:v.number()}).index('by_project',['projectId']).index('by_key',['key']),
 filmReferences:defineTable({projectId:v.id('filmProjects'),key:v.string(),kind:v.union(v.literal('character'),v.literal('place')),name:v.string(),description:v.string(),fileId:v.optional(v.id('_storage')),updatedAt:v.number()}).index('by_project',['projectId']).index('by_key',['key']),
 filmEpisodes:defineTable({previousPlans:v.optional(v.string()),projectId:v.id('filmProjects'),episode:v.number(),version:v.number(),plan:filmPlan,referenceRevision:v.number(),brief:v.string(),approved:v.boolean(),createdAt:v.number()}).index('by_project',['projectId']),
 filmUploads:defineTable({projectId:v.id('filmProjects'),key:v.string(),type:v.string(),size:v.number(),fileId:v.optional(v.id('_storage'))}).index('by_key',['key']).index('by_file',['fileId']),
 filmBudgets:defineTable({key:v.string(),usedMicros:v.number()}).index('by_key',['key']),
 imageJobs:defineTable({subject:v.string(),key:v.string(),prompt:v.string(),referenceIds:v.array(v.id('_storage')),option:imageOptionValidator,points:v.number(),walletId:v.id('pointWallets'),status:imageStatusValidator,createdAt:v.number(),updatedAt:v.number(),paused:v.boolean(),stopRequested:v.boolean(),intentAt:v.optional(v.number()),submittedAt:v.optional(v.number()),baselineIds:v.optional(v.array(v.string())),projectPath:v.optional(v.string()),assetId:v.optional(v.string()),fileId:v.optional(v.id('_storage')),fileType:v.optional(v.string()),width:v.optional(v.number()),height:v.optional(v.number()),size:v.optional(v.number()),error:v.optional(v.string()),lease:v.optional(v.object({workerId:v.string(),fence:v.string(),until:v.number()}))}).index('by_key',['key']).index('by_subject',['subject']),
 adminGates:defineTable({subject:v.string(),expiresAt:v.number(),attempts:v.number(),windowStart:v.number(),lockedUntil:v.number(),version:v.string()}).index('by_subject',['subject']),
 branding:defineTable({generationLanguage:v.optional(v.object({language:v.union(v.literal('ar'),v.literal('en')),dialect:v.string()})),key:v.string(),name:v.string(),address:v.string(),phone:v.string(),logoId:v.optional(v.id('_storage')),logoEnabled:v.boolean(),references:v.optional(v.array(v.object({slot:v.number(),aspect:v.optional(v.union(v.literal('9:16'),v.literal('16:9'))),storageId:v.id('_storage')}))),referenceNotes:v.optional(v.object({portrait:v.string(),landscape:v.string()})),updatedAt:v.number()}).index('by_key',['key']),
 signupSettings:defineTable({key:v.string(),points:v.number(),updatedAt:v.number(),actor:v.string()}).index('by_key',['key']),
 pointWallets:defineTable({onboardedAt:v.optional(v.number()),subject:v.string(),publicId:v.string(),name:v.string(),balance:v.number(),enabled:v.boolean(),models:v.array(v.string()),maxClips:v.number(),createdAt:v.number(),updatedAt:v.number()}).index('by_subject',['subject']).index('by_publicId',['publicId']),
 pointLedger:defineTable({key:v.string(),walletId:v.id('pointWallets'),kind:v.union(v.literal('credit'),v.literal('debit'),v.literal('permissions'),v.literal('reserve'),v.literal('refund')),amount:v.number(),balanceAfter:v.number(),note:v.string(),actor:v.string(),createdAt:v.number()}).index('by_key',['key']).index('by_wallet',['walletId']),
 pointRates:defineTable({key:v.string(),model:v.string(),resolution:v.string(),seconds:v.number(),points:v.number(),source:v.optional(v.union(v.literal('flow'),v.literal('manual'))),observedAt:v.optional(v.number()),updatedAt:v.number()}).index('by_key',['key']),
 workers:defineTable({flowBalance:v.optional(v.object({credits:v.optional(v.number()),at:v.number(),error:v.optional(v.string())})),filmReady:v.optional(v.boolean()),key:v.string(),workerId:v.string(),state:v.string(),seenAt:v.number(),observedAt:v.number(),options:v.array(optionValidator),imageOptions:v.optional(v.array(imageOptionValidator)),imageObservedAt:v.optional(v.number()),imageError:v.optional(v.string()),error:v.optional(v.string())}).index('by_key',['key']),
 pipelines:defineTable({continuationSource:v.optional(v.object({storageId:v.string(),duration:v.number(),width:v.number(),height:v.number()})),billing:v.optional(v.object({walletId:v.id('pointWallets'),unitPoints:v.number()})),mode:v.union(v.literal('generate'),v.literal('existing')),key:v.string(),requestId:v.id('requests'),form:formValidator,logoId:v.optional(v.id('_storage')),referenceIds:v.array(v.id('_storage')),option:optionValidator,template:templateValidator,clips:v.array(clipValidator),stage:stageValidator,authorizedAt:v.number(),updatedAt:v.number(),stopRequested:v.boolean(),paused:v.boolean(),error:v.optional(v.string()),exportId:v.optional(v.id('exports')),finalId:v.optional(v.id('_storage')),lease:v.optional(v.object({workerId:v.string(),fence:v.string(),until:v.number()}))}).index('by_key',['key']).index('by_request',['requestId']),
 edits:defineTable({requestId:v.id('requests'),settings:editValidator,logoId:v.optional(v.id('_storage')),updatedAt:v.number()}).index('by_request',['requestId']),
 exports:defineTable({key:v.string(),requestId:v.id('requests'),settings:editValidator,logoId:v.optional(v.id('_storage')),texts:v.object({name:v.string(),address:v.string(),phone:v.string()}),status:exportStatus,history:v.optional(v.array(v.object({status:exportStatus,at:v.number()}))),createdAt:v.number(),updatedAt:v.number(),startedAt:v.optional(v.number()),endedAt:v.optional(v.number()),error:v.optional(v.string()),percent:v.optional(v.number()),fileId:v.optional(v.id('_storage')),media:v.optional(mediaValidator),lease:v.optional(v.object({workerId:v.string(),fence:v.string(),until:v.number()}))}).index('by_key',['key']).index('by_request',['requestId']).index('by_status',['status']),
 requests: defineTable({promptPreparation:v.optional(v.object({state:v.union(v.literal('running'),v.literal('completed'),v.literal('failed')),snapshot:v.string(),prompts:v.optional(v.array(v.string())),inputTokens:v.optional(v.number()),outputTokens:v.optional(v.number()),error:v.optional(v.string()),startedAt:v.number()})),subject:v.optional(v.string()),runner:v.optional(runner),results:v.optional(v.array(v.object({assetId:v.string(),storageId:v.id('_storage'),duration:v.number(),width:v.number(),height:v.number()}))),key:v.string(),form:formValidator,clipCount:v.number(),logoId:v.optional(v.id('_storage')),referenceIds:v.array(v.id('_storage')),createdAt:v.number(),updatedAt:v.number(),status:statusValidator,error:v.optional(v.string()),externalTaskId:v.optional(v.string()),externalVideoUrl:v.optional(v.string()),videoId:v.optional(v.id('_storage')),videoSource:v.optional(v.union(v.literal('manual'),v.literal('runner'))),estimatedPoints:v.optional(v.number()),actualPoints:v.optional(v.number())}).index('by_key',['key']),
 uploads: defineTable({subject:v.optional(v.string()),key:v.string(),kind:kindValidator,name:v.string(),type:v.string(),size:v.number(),createdAt:v.number(),storageId:v.optional(v.id('_storage'))}).index('by_key',['key']).index('by_storage',['storageId']),
});
