import { defineSchema, defineTable } from 'convex/server';
import { v } from 'convex/values';
import { formValidator, kindValidator, statusValidator } from './validators';
import {editValidator,exportStatus,mediaValidator} from './editValidators';
import {optionValidator,templateValidator,stageValidator,clipValidator} from './pipelineValidators';
const runner=v.object({workerId:v.string(),fence:v.string(),leaseUntil:v.number(),phase:v.union(v.literal('prepared'),v.literal('intent'),v.literal('submitted'),v.literal('unknown'),v.literal('downloaded'),v.literal('uploaded')),projectPath:v.optional(v.string()),clipSeconds:v.optional(v.number()),requiredClips:v.optional(v.number())});
export default defineSchema({
 workers:defineTable({key:v.string(),workerId:v.string(),state:v.string(),seenAt:v.number(),observedAt:v.number(),options:v.array(optionValidator),error:v.optional(v.string())}).index('by_key',['key']),
 pipelines:defineTable({mode:v.union(v.literal('generate'),v.literal('existing')),key:v.string(),requestId:v.id('requests'),form:formValidator,logoId:v.optional(v.id('_storage')),referenceIds:v.array(v.id('_storage')),option:optionValidator,template:templateValidator,clips:v.array(clipValidator),stage:stageValidator,authorizedAt:v.number(),updatedAt:v.number(),stopRequested:v.boolean(),paused:v.boolean(),error:v.optional(v.string()),exportId:v.optional(v.id('exports')),finalId:v.optional(v.id('_storage')),lease:v.optional(v.object({workerId:v.string(),fence:v.string(),until:v.number()}))}).index('by_key',['key']).index('by_request',['requestId']),
 edits:defineTable({requestId:v.id('requests'),settings:editValidator,logoId:v.optional(v.id('_storage')),updatedAt:v.number()}).index('by_request',['requestId']),
 exports:defineTable({key:v.string(),requestId:v.id('requests'),settings:editValidator,logoId:v.optional(v.id('_storage')),texts:v.object({name:v.string(),address:v.string(),phone:v.string()}),status:exportStatus,history:v.optional(v.array(v.object({status:exportStatus,at:v.number()}))),createdAt:v.number(),updatedAt:v.number(),startedAt:v.optional(v.number()),endedAt:v.optional(v.number()),error:v.optional(v.string()),percent:v.optional(v.number()),fileId:v.optional(v.id('_storage')),media:v.optional(mediaValidator),lease:v.optional(v.object({workerId:v.string(),fence:v.string(),until:v.number()}))}).index('by_key',['key']).index('by_request',['requestId']).index('by_status',['status']),
 requests: defineTable({runner:v.optional(runner),results:v.optional(v.array(v.object({assetId:v.string(),storageId:v.id('_storage'),duration:v.number(),width:v.number(),height:v.number()}))),key:v.string(),form:formValidator,clipCount:v.number(),logoId:v.optional(v.id('_storage')),referenceIds:v.array(v.id('_storage')),createdAt:v.number(),updatedAt:v.number(),status:statusValidator,error:v.optional(v.string()),externalTaskId:v.optional(v.string()),externalVideoUrl:v.optional(v.string()),videoId:v.optional(v.id('_storage')),videoSource:v.optional(v.union(v.literal('manual'),v.literal('runner'))),estimatedPoints:v.optional(v.number()),actualPoints:v.optional(v.number())}).index('by_key',['key']),
 uploads: defineTable({key:v.string(),kind:kindValidator,name:v.string(),type:v.string(),size:v.number(),createdAt:v.number(),storageId:v.optional(v.id('_storage'))}).index('by_key',['key']).index('by_storage',['storageId']),
});
