import {httpAction} from './_generated/server';
import type {HttpRouter} from 'convex/server';
import {internal} from './_generated/api';
import {verifyMetaRequest,stateHash} from '../shared/meta';
export function socialRoutes(http:HttpRouter){
 http.route({path:'/social/callback',method:'GET',handler:httpAction(async(ctx,r)=>{const u=new URL(r.url),state=u.searchParams.get('state');if(!state||state.length>200)return new Response('Invalid state',{status:400});const url=await ctx.runAction(internal.social.callback,{state,code:u.searchParams.get('code')??undefined});return new Response(null,{status:303,headers:{Location:url,'Cache-Control':'no-store','Referrer-Policy':'no-referrer'}});})});
 for(const path of ['/social/deauthorize','/social/delete'])http.route({path,method:'POST',handler:httpAction(async(ctx,r)=>{try{if(Number(r.headers.get('Content-Length')??0)>8192)return new Response('Too large',{status:413});const form=new URLSearchParams(await r.text()),signed=form.get('signed_request'),secret=process.env.META_APP_SECRET;if(!signed||!secret)throw new Error('Missing');const user=await verifyMetaRequest(signed,secret);await ctx.runMutation(internal.social.erase,{providerUserId:user});const confirmation=await stateHash(signed);await ctx.runMutation(internal.social.receipt,{code:confirmation});return Response.json(path.endsWith('delete')?{url:`${process.env.CONVEX_SITE_URL}/social/deletion-status?code=${confirmation}`,confirmation_code:confirmation}:{success:true},{headers:{'Cache-Control':'no-store'}});}catch{return new Response('Invalid signed request',{status:400});}})});
 http.route({path:'/social/deletion-status',method:'GET',handler:httpAction(async(ctx,r)=>{const code=new URL(r.url).searchParams.get('code');if(!code||!/^[a-f0-9]{64}$/.test(code)||!await ctx.runQuery(internal.social.receiptExists,{code}))return new Response('Invalid receipt',{status:400});return new Response('تم تنفيذ حذف بيانات ربط Meta من قاعدة البيانات النشطة في مشهد. الفيديوهات وحساب مشهد لم يُحذفا. احتفظ برمز التأكيد الصادر عن طلب حذف البيانات.',{headers:{'Content-Type':'text/plain; charset=utf-8','Cache-Control':'no-store','X-Content-Type-Options':'nosniff'}});})});
}
