import {beforeEach,expect,it,vi} from 'vitest';
import {convexTest} from 'convex-test';
import schema from './schema';
import {api,internal} from './_generated/api';
import {defaultTemplate} from '../shared/pipeline';
const modules=import.meta.glob('./**/*.{ts,js}'),owner={subject:'owner',issuer:'https://owner.clerk.accounts.dev'};
const form={name:'الشركة',address:'العراق',phone:'07700000000',products:'تطبيقات',prompt:'First scene',instructions:'',model:'Veo 3.1 Fast',aspect:'9:16',duration:8,dialect:'العراقية'};
beforeEach(()=>{vi.stubEnv('OWNER_SUBJECT',owner.subject);vi.stubEnv('CLERK_JWT_ISSUER_DOMAIN',owner.issuer)});
async function funded(){const t=convexTest(schema,modules);await t.run(async ctx=>{await ctx.db.insert('pointWallets',{subject:owner.subject,publicId:'MS-test',name:'owner fixture',balance:100,enabled:true,models:['Veo 3.1 Fast'],maxClips:20,createdAt:1,updatedAt:1});await ctx.db.insert('pointRates',{key:'Veo 3.1 Fast:720p:8',model:'Veo 3.1 Fast',resolution:'720p',seconds:8,points:20,updatedAt:1})});return t;}
async function image(t:ReturnType<typeof convexTest>,key='image'){return t.run(async ctx=>{const storageId=await ctx.storage.store(new Blob(['fixture'],{type:'image/png'}));await ctx.db.insert('uploads',{key,storageId,name:key,kind:'image',type:'image/png',size:7,createdAt:Date.now()});return storageId});}
it('protects branding, gallery and photo settings from anonymous and other users',async()=>{const t=await funded();for(const user of [t,t.withIdentity({...owner,subject:'other'})]){await expect(user.query(api.studio.branding,{})).rejects.toThrow();await expect(user.query(api.studio.gallery,{})).rejects.toThrow();await expect(user.mutation(api.studio.savePhotos,{references:[]})).rejects.toThrow();await expect(user.mutation(api.studio.saveBranding,{name:'',address:'',phone:'',logoEnabled:false})).rejects.toThrow();}});
it('persists the owner logo and ordered views without clearing company details',async()=>{const t=await funded(),u=t.withIdentity(owner),logoId=await image(t);await u.mutation(api.studio.saveBranding,{name:'المحل',address:'البصرة',phone:'07701234567',logoId,logoEnabled:true});await u.mutation(api.studio.savePhotos,{references:[{slot:0,storageId:logoId},{slot:7,storageId:logoId}]});const b=await u.query(api.studio.branding,{});expect(b?.phone).toBe('07701234567');expect(b?.logoEnabled).toBe(true);expect(b?.references?.map(r=>r.slot)).toEqual([0,7]);await expect(u.mutation(api.studio.savePhotos,{references:[{slot:8,storageId:logoId}]})).rejects.toThrow('خانة');await expect(u.mutation(api.studio.savePhotos,{references:[{slot:1,storageId:logoId},{slot:1,storageId:logoId}]})).rejects.toThrow('مختلفة');});
it('returns the last successful final while retaining originals and excluding unfinished requests',async()=>{const t=await funded(),u=t.withIdentity(owner);const requestId=await u.mutation(api.requests.save,{key:'gallery',form,clipCount:1,referenceIds:[],submit:false});const fileId=await t.run(ctx=>ctx.storage.store(new Blob(['video'],{type:'video/mp4'})));const settings={...defaultTemplate(form),duration:8,transition:0,clips:[{storageId:fileId,start:0,end:8}]};await t.run(async ctx=>{await ctx.db.patch(requestId,{status:'مكتمل',videoId:fileId});await ctx.db.insert('exports',{key:'success',requestId,settings,texts:{name:'المحل',address:'',phone:''},status:'completed',createdAt:1,updatedAt:2,fileId,media:{duration:8,width:720,height:1280,size:10,audio:true,sources:[]}});await ctx.db.insert('exports',{key:'failed-new',requestId,settings,texts:{name:'المحل',address:'',phone:''},status:'failed',createdAt:3,updatedAt:4});});await u.mutation(api.requests.save,{key:'unfinished',form,clipCount:1,referenceIds:[],submit:true});const gallery=await u.query(api.studio.gallery,{});expect(gallery).toHaveLength(1);expect(gallery[0]).toMatchObject({storageId:fileId,final:true,duration:8});});
it('allows continuation only from a registered video and limits runner access to the chosen source',async()=>{const t=await funded(),u=t.withIdentity(owner),picture=await image(t);await expect(u.mutation(api.requests.save,{key:'bad-source',form:{...form,continuationSourceId:picture},clipCount:1,referenceIds:[],submit:false})).rejects.toThrow('نوعه');const storageId=await t.run(async ctx=>{const id=await ctx.storage.store(new Blob(['video'],{type:'video/mp4'}));await ctx.db.insert('uploads',{key:'video',name:'v',storageId:id,kind:'video',type:'video/mp4',size:5,createdAt:1});return id});const requestId=await u.mutation(api.requests.save,{key:'continue-original',form:{...form,continuationSourceId:storageId},clipCount:1,referenceIds:[],submit:true});const option={model:form.model,actualModel:'Veo 3.1 - Fast',seconds:8,resolution:'720p' as const,aspect:'9:16',cost:20};await t.mutation(internal.pipeline.presence,{workerId:'w',state:'online',options:[option],observedAt:Date.now()});const jobId=await u.mutation(api.pipeline.authorize,{requestId,key:'new-continuation',option,count:1,template:defaultTemplate(form)});expect(await t.query(internal.pipeline.fileAccess,{jobId,storageId})).toBe(true);expect(await t.query(internal.pipeline.fileAccess,{jobId,storageId:picture})).toBe(false);expect((await u.query(api.pipeline.state,{requestId}))[0].clips[0].prompt).toContain('إطار البداية المرفق');});
it('accepts observed progress only within the leased submitted clip',async()=>{const t=await funded(),u=t.withIdentity(owner),requestId=await u.mutation(api.requests.save,{key:'real-progress',form,clipCount:1,referenceIds:[],submit:true}),option={model:form.model,actualModel:'Veo 3.1 - Fast',seconds:8,resolution:'720p' as const,aspect:'9:16',cost:20};await t.mutation(internal.pipeline.presence,{workerId:'w',state:'online',options:[option],observedAt:Date.now()});const jobId=await u.mutation(api.pipeline.authorize,{requestId,key:'progress-job',option,count:1,template:defaultTemplate(form)}),identity={jobId,workerId:'w',fence:'f'};await t.mutation(internal.pipeline.claim,identity);await t.mutation(internal.pipeline.clip,{...identity,index:0,state:'intent',projectPath:'/project/known'});await t.mutation(internal.pipeline.clip,{...identity,index:0,state:'submitted',percent:37});expect((await u.query(api.pipeline.state,{requestId}))[0].clips[0].percent).toBe(37);await expect(t.mutation(internal.pipeline.clip,{...identity,index:0,state:'submitted',percent:101})).rejects.toThrow('progress');await expect(t.mutation(internal.pipeline.clip,{...identity,fence:'wrong',index:0,state:'submitted',percent:40})).rejects.toThrow('lease');});

it('keeps eight slots per orientation and their separate notes without accepting duplicate orientation slots',async()=>{const t=await funded(),u=t.withIdentity(owner),storageId=await image(t);const references=Array.from({length:16},(_,i)=>({slot:i%8,aspect:i<8?'9:16' as const:'16:9' as const,storageId}));await u.mutation(api.studio.savePhotos,{references,referenceNotes:{portrait:'صور المحل العمودية',landscape:'صور المحل الأفقية'}});const b=await u.query(api.studio.branding,{});expect(b?.references).toHaveLength(16);expect(b?.referenceNotes?.landscape).toBe('صور المحل الأفقية');await u.mutation(api.studio.saveBranding,{name:'الشركة',address:'',phone:'077000',logoEnabled:false});expect((await u.query(api.studio.branding,{}))?.referenceNotes).toEqual(b?.referenceNotes);await expect(u.mutation(api.studio.savePhotos,{references:[references[0],references[0]]})).rejects.toThrow('مختلفة');await expect(u.mutation(api.studio.savePhotos,{references:[],referenceNotes:{portrait:'x'.repeat(4001),landscape:''}})).rejects.toThrow('طويل');});
