import {beforeEach,afterEach,expect,it,vi} from 'vitest';
import {convexTest} from 'convex-test';
import schema from './schema';
import {api,internal} from './_generated/api';
import {defaultTemplate} from '../shared/pipeline';
const modules=import.meta.glob('./**/*.{ts,js}'),owner={subject:'owner',issuer:'https://owner.clerk.accounts.dev'},other={...owner,subject:'other'};
const option={model:'Omni Flash',actualModel:'Omni 1.1 Flash',seconds:10,resolution:'360p' as const,aspect:'9:16',cost:7};
const form={name:'نور',address:'غير مذكور',phone:'غير مذكور',products:'فيديو',prompt:'نور تقول "هسه شلونك؟"',instructions:'',model:option.model,aspect:option.aspect,duration:10,dialect:'العراقية',productionLanguage:'en' as const};
beforeEach(()=>{vi.stubEnv('OWNER_SUBJECT',owner.subject);vi.stubEnv('CLERK_JWT_ISSUER_DOMAIN',owner.issuer);vi.stubEnv('OPENAI_API_KEY','fixture-only');});
afterEach(()=>{vi.unstubAllGlobals();vi.unstubAllEnvs()});
async function setup(){const t=convexTest(schema,modules);await t.run(async ctx=>{for(const user of [owner,other])await ctx.db.insert('pointWallets',{subject:user.subject,publicId:'MS-'+user.subject,name:user.subject,balance:100,enabled:true,models:[option.model],maxClips:20,createdAt:1,updatedAt:1});await ctx.db.insert('pointRates',{key:'Omni Flash:360p:10',model:option.model,resolution:'360p',seconds:10,points:7,updatedAt:1});});await t.mutation(internal.pipeline.presence,{workerId:'w',state:'online',options:[option],observedAt:Date.now()});const user=t.withIdentity(owner),requestId=await user.mutation(api.requests.save,{key:'language-fixture',form,clipCount:1,referenceIds:[],submit:true});return {t,user,requestId};}
it('requires cached preparation before authorization, retains exact speech and calls provider only once',async()=>{const {t,user,requestId}=await setup();await expect(user.mutation(api.pipeline.authorize,{requestId,key:'language-job',option,count:1,template:defaultTemplate(form)})).rejects.toThrow('تجهيز');const mock=vi.fn(async()=>new Response(JSON.stringify({status:'completed',usage:{input_tokens:200,output_tokens:80},output:[{content:[{type:'output_text',text:JSON.stringify({scenes:[{visual:'Noor stands near a window in soft light.',dialogue:'نور: هسه شلونك؟'}]})}]}]}),{status:200}));vi.stubGlobal('fetch',mock);await user.action(api.videoLanguage.prepare,{requestId,option});await user.action(api.videoLanguage.prepare,{requestId,option});expect(mock).toHaveBeenCalledTimes(1);await user.mutation(api.pipeline.authorize,{requestId,key:'language-job',option,count:1,template:defaultTemplate(form)});const job=(await user.query(api.pipeline.state,{requestId}))[0];expect(job.clips[0].prompt).toContain('Noor stands');expect(job.clips[0].prompt).toContain('نور: هسه شلونك؟');expect(await t.run(ctx=>ctx.db.query('pointLedger').collect())).toHaveLength(0);});
it('blocks cross-customer preparation and duplicate dispatch after a provider timeout',async()=>{const {t,user,requestId}=await setup();const mock=vi.fn(async()=>{throw new Error('timeout')});vi.stubGlobal('fetch',mock);await expect(t.withIdentity(other).action(api.videoLanguage.prepare,{requestId,option})).rejects.toThrow('مصرح');expect(mock).not.toHaveBeenCalled();await expect(user.action(api.videoLanguage.prepare,{requestId,option})).rejects.toThrow('لم يبدأ');await expect(user.action(api.videoLanguage.prepare,{requestId,option})).rejects.toThrow('أنشئ طلبًا');expect(mock).toHaveBeenCalledTimes(1);});
it('stores account language independently and invalidates old film approval when dialect changes',async()=>{const {t,user}=await setup();const projectId=await user.mutation(api.films.create,{key:'language-film',title:'نور'});await user.mutation(api.filmWorkshop.settings,{projectId,settings:{style:'واقعي',dialect:'العراقية',episodes:1,seconds:60}});await user.mutation(api.studio.saveBranding,{name:'',address:'',phone:'',logoEnabled:false,generationLanguage:{language:'en',dialect:'English'}});expect((await user.query(api.studio.branding,{}))?.generationLanguage?.language).toBe('en');expect(await t.withIdentity(owner).query(internal.films.language,{projectId})).toBe('English');expect((await t.run(ctx=>ctx.db.get(projectId)))?.referenceRevision).toBe(2);expect(await t.withIdentity(other).query(api.studio.branding,{})).toBeNull();await user.mutation(api.studio.saveBranding,{name:'new',address:'',phone:'',logoEnabled:false});expect((await user.query(api.studio.branding,{}))?.generationLanguage?.language).toBe('en');});
it('applies the first saved Iraqi preference to prior foreign-dialect films and leaves authorized job snapshots intact',async()=>{const {t,user}=await setup();const projectId=await user.mutation(api.films.create,{key:'prior-film',title:'نور'});await user.mutation(api.filmWorkshop.settings,{projectId,settings:{style:'واقعي',dialect:'المصرية',episodes:1,seconds:60}});const requestId=await user.mutation(api.requests.save,{key:'old-language',form:{...form,productionLanguage:undefined,dialect:'المصرية'},clipCount:1,referenceIds:[],submit:true});await user.mutation(api.pipeline.authorize,{requestId,key:'old-snapshot-job',option,count:1,template:defaultTemplate(form)});const before=(await user.query(api.pipeline.state,{requestId}))[0];await user.mutation(api.studio.saveBranding,{name:'',address:'',phone:'',logoEnabled:false,generationLanguage:{language:'ar',dialect:'العراقية'}});expect(await t.withIdentity(owner).query(internal.films.language,{projectId})).toBe('العراقية');expect((await user.query(api.pipeline.state,{requestId}))[0]).toEqual(before);});
