import {v,ConvexError} from 'convex/values';
import {query,mutation,type QueryCtx,type MutationCtx} from './_generated/server';
import {requireWalletAdmin} from './adminGate';
import {IMAGE_DEFAULT_POINTS,imageModels,imagePoints} from '../shared/images';
function imageRates<T extends {model:string;resolution:string;seconds:number;points:number;source?:string}>(rows:T[]){const result=rows.map(r=>r.seconds===0&&imageModels.some(m=>m===r.model)?{...r,points:imagePoints(r)}:r);return [...result,...imageModels.filter(model=>!rows.some(r=>r.model===model&&r.resolution==='original'&&r.seconds===0)).map(model=>({key:model+':original:0',model,resolution:'original',seconds:0,points:IMAGE_DEFAULT_POINTS,source:'manual' as const,updatedAt:0}))];}
const models=['Omni Flash','Veo 3.1 Fast','Veo 3.1 Quality','Nano Banana Pro','Nano Banana 2','Nano Banana 2 Lite'];
async function signed(ctx:QueryCtx|MutationCtx){const i=await ctx.auth.getUserIdentity();if(!i||!process.env.CLERK_JWT_ISSUER_DOMAIN||i.issuer!==process.env.CLERK_JWT_ISSUER_DOMAIN)throw new ConvexError('سجّل الدخول للوصول إلى محفظتك.');return i;}
export const mine=query({args:{},handler:async ctx=>{const i=await signed(ctx),wallet=await ctx.db.query('pointWallets').withIndex('by_subject',q=>q.eq('subject',i.subject)).unique();if(!wallet)return null;const ledger=await ctx.db.query('pointLedger').withIndex('by_wallet',q=>q.eq('walletId',wallet._id)).order('desc').take(100);return {wallet,ledger:ledger.map(({kind,amount,balanceAfter,note,createdAt})=>({kind,amount,balanceAfter,note,createdAt}))};}});
export const register=mutation({args:{name:v.string()},handler:async(ctx,a)=>{const i=await signed(ctx);if(!a.name.trim()||a.name.trim().length>120)throw new ConvexError('اكتب الاسم ضمن 120 حرفًا.');const old=await ctx.db.query('pointWallets').withIndex('by_subject',q=>q.eq('subject',i.subject)).unique();if(old)return old._id;const now=Date.now(),id=await ctx.db.insert('pointWallets',{subject:i.subject,publicId:'pending',name:a.name.trim(),balance:0,enabled:false,models:[],maxClips:1,createdAt:now,updatedAt:now});await ctx.db.patch(id,{publicId:`MS-${id}`});return id;}});
export const adminState=query({args:{},handler:async ctx=>{await requireWalletAdmin(ctx);const wallets=await ctx.db.query('pointWallets').order('desc').take(200),ledger=await ctx.db.query('pointLedger').order('desc').take(100),rates=imageRates(await ctx.db.query('pointRates').collect()),worker=await ctx.db.query('workers').withIndex('by_key',q=>q.eq('key','pipeline')).unique();return {wallets,ledger,rates,flowBalance:worker?.flowBalance??null,options:[...(worker?.options??[]),...(worker?.imageOptions??[]).map(o=>({...o,actualModel:o.model,resolution:'original',seconds:0}))],observedAt:worker?.observedAt??0};}});
export const adjust=mutation({args:{walletId:v.id('pointWallets'),key:v.string(),amount:v.number(),note:v.string()},handler:async(ctx,a)=>{const i=await requireWalletAdmin(ctx);if(!/^[a-zA-Z0-9-]{8,100}$/.test(a.key)||!Number.isSafeInteger(a.amount)||!a.amount||Math.abs(a.amount)>1000000||!a.note.trim()||a.note.length>500)throw new ConvexError('اختر عددًا صحيحًا من 1 إلى مليون نقطة واكتب سبب الحركة.');const old=await ctx.db.query('pointLedger').withIndex('by_key',q=>q.eq('key',a.key)).unique();if(old){if(old.walletId!==a.walletId||old.amount!==a.amount||old.note!==a.note.trim())throw new ConvexError('مفتاح الحركة مرتبط ببيانات مختلفة.');return old._id;}const w=await ctx.db.get(a.walletId);if(!w)throw new ConvexError('المحفظة غير موجودة.');const balance=w.balance+a.amount;if(balance<0||!Number.isSafeInteger(balance)||balance>1000000000)throw new ConvexError('الرصيد لا يسمح بهذه الحركة.');const now=Date.now();await ctx.db.patch(w._id,{balance,updatedAt:now});return ctx.db.insert('pointLedger',{key:a.key,walletId:w._id,kind:a.amount>0?'credit':'debit',amount:a.amount,balanceAfter:balance,note:a.note.trim(),actor:i.subject,createdAt:now});}});
export const permissions=mutation({args:{walletId:v.id('pointWallets'),enabled:v.boolean(),models:v.array(v.string()),maxClips:v.number()},handler:async(ctx,a)=>{const i=await requireWalletAdmin(ctx);if(a.models.some(m=>!models.includes(m))||new Set(a.models).size!==a.models.length||!Number.isInteger(a.maxClips)||a.maxClips<1||a.maxClips>80)throw new ConvexError('صلاحيات غير صالحة.');const w=await ctx.db.get(a.walletId);if(!w)throw new ConvexError('المحفظة غير موجودة.');const next={enabled:a.enabled,models:a.models,maxClips:a.maxClips};if(w.enabled===a.enabled&&w.maxClips===a.maxClips&&JSON.stringify(w.models)===JSON.stringify(a.models))return;const now=Date.now();await ctx.db.patch(w._id,{...next,updatedAt:now});await ctx.db.insert('pointLedger',{key:`permissions-${w._id}-${now}`,walletId:w._id,kind:'permissions',amount:0,balanceAfter:w.balance,note:`${a.enabled?'تفعيل':'تعطيل'} استخدام النقاط؛ الموديلات: ${a.models.join('، ')||'لا يوجد'}؛ الحد: ${a.maxClips} مقطع`,actor:i.subject,createdAt:now});}});
export const saveRate=mutation({args:{model:v.string(),resolution:v.string(),seconds:v.number(),points:v.number()},handler:async(ctx,a)=>{await requireWalletAdmin(ctx);if(!models.includes(a.model)||!(a.model.startsWith('Nano Banana')?a.resolution==='original'&&a.seconds===0:['360p','720p'].includes(a.resolution)&&Number.isInteger(a.seconds)&&a.seconds>=1&&a.seconds<=30)||!Number.isSafeInteger(a.points)||a.points<0||a.points>1000000)throw new ConvexError('تسعير غير صالح.');const key=`${a.model}:${a.resolution}:${a.seconds}`,old=await ctx.db.query('pointRates').withIndex('by_key',q=>q.eq('key',key)).unique(),value={...a,key,source:'manual' as const,updatedAt:Date.now()};if(old)await ctx.db.patch(old._id,value);else await ctx.db.insert('pointRates',value);}});
export const quote=query({args:{model:v.string(),resolution:v.string(),seconds:v.number(),count:v.number()},handler:async(ctx,a)=>{const i=await signed(ctx),w=await ctx.db.query('pointWallets').withIndex('by_subject',q=>q.eq('subject',i.subject)).unique();if(!w?.enabled||!w.models.includes(a.model)||!Number.isInteger(a.count)||a.count<1||a.count>w.maxClips)throw new ConvexError('هذه الخطة غير مصرح بها لمحفظتك.');const rate=await ctx.db.query('pointRates').withIndex('by_key',q=>q.eq('key',`${a.model}:${a.resolution}:${a.seconds}`)).unique();if(!rate&&!imageModels.some(m=>m===a.model))throw new ConvexError('سعر الموديل لم يحدده الأدمن بعد.');const unit=imageModels.some(m=>m===a.model)?imagePoints(rate??undefined):rate!.points;return {unit,total:unit*a.count,balance:w.balance,sufficient:w.balance>=unit*a.count,currency:'نقاط مشهد',flowConsumptionConfirmed:false};}});

export const importObserved=mutation({args:{},handler:async ctx=>{await requireWalletAdmin(ctx);const w=await ctx.db.query('workers').withIndex('by_key',q=>q.eq('key','pipeline')).unique();if(!w||Date.now()-w.observedAt>3600000)throw new ConvexError('شغّل Worker لقراءة كلفة حديثة من Flow أولًا.');const options=[...w.options,...(w.imageOptions??[]).map(o=>({...o,resolution:'original',seconds:0}))];const prices=new Map<string,(typeof options)[number]>();for(const o of options){if(!Number.isSafeInteger(o.cost)||o.cost<0||o.cost>1000000)throw new ConvexError('الكلفة المرصودة غير صالحة.');const key=`${o.model}:${o.resolution}:${o.seconds}`,other=prices.get(key);if(other&&other.cost!==o.cost)throw new ConvexError('الكلفة تختلف حسب المقاس؛ يلزم مراجعة التسعير.');prices.set(key,o);}if(!prices.size)throw new ConvexError('لا توجد خيارات مرصودة.');let imported=0;for(const [key,o] of prices){const old=await ctx.db.query('pointRates').withIndex('by_key',q=>q.eq('key',key)).unique();if(old?.source==='manual')continue;const value={key,model:o.model,resolution:o.resolution,seconds:o.seconds,points:o.seconds===0?IMAGE_DEFAULT_POINTS:o.cost,source:o.seconds===0?'manual' as const:'flow' as const,observedAt:w.observedAt,updatedAt:Date.now()};if(old)await ctx.db.patch(old._id,value);else await ctx.db.insert('pointRates',value);imported++;}return imported;}});

export const pricing=query({args:{},handler:async ctx=>{await signed(ctx);return imageRates(await ctx.db.query('pointRates').collect());}});
