import {beforeEach,expect,it,vi} from 'vitest';
import {convexTest} from 'convex-test';
import schema from './schema';
import {api,internal} from './_generated/api';
const modules=import.meta.glob('./**/*.{ts,js}'),owner={subject:'owner',issuer:'https://owner.clerk.accounts.dev'},customer={...owner,subject:'customer'};
beforeEach(()=>{vi.stubEnv('ADMIN_CODE_VERIFIER','test');vi.stubEnv('ADMIN_CODE_VERSION','1');vi.stubEnv('OWNER_SUBJECT',owner.subject);vi.stubEnv('CLERK_JWT_ISSUER_DOMAIN',owner.issuer)});
async function fixture(){const t=convexTest(schema,modules),a=t.withIdentity(owner),u=t.withIdentity(customer),id=await u.mutation(api.wallets.register,{name:'زبون اختبار'});await t.run(ctx=>ctx.db.insert('adminGates',{subject:owner.subject,expiresAt:Date.now()+1800000,attempts:0,windowStart:Date.now(),lockedUntil:0,version:'1'}));return {t,a,u,id};}
it('denies anonymous, wrong issuer and customer admin operations',async()=>{const {t,u,id}=await fixture();for(const actor of [t,u,t.withIdentity({...owner,issuer:'https://wrong.example'})]){await expect(actor.query(api.wallets.adminState,{})).rejects.toThrow();await expect(actor.mutation(api.wallets.adjust,{walletId:id,key:'denied-123',amount:100,note:'test'})).rejects.toThrow();}await expect(t.query(api.wallets.mine,{})).rejects.toThrow();await expect(t.withIdentity({...customer,issuer:'wrong'}).mutation(api.wallets.register,{name:'x'})).rejects.toThrow();});
it('creates a stable disabled wallet and isolates balances and owner video data',async()=>{const {t,u,id}=await fixture();expect(await u.mutation(api.wallets.register,{name:'different'})).toBe(id);expect((await u.query(api.wallets.mine,{}))?.wallet).toMatchObject({publicId:`MS-${id}`,balance:0,enabled:false,models:[]});expect(await t.withIdentity({...owner,subject:'other'}).query(api.wallets.mine,{})).toBeNull();await expect(u.query(api.studio.gallery,{})).rejects.toThrow();});
it('applies repeated and concurrent adjustments once and rejects key reuse',async()=>{const {a,u,id}=await fixture(),args={walletId:id,key:'movement-123',amount:100,note:'test credit'};const entries=await Promise.all([a.mutation(api.wallets.adjust,args),a.mutation(api.wallets.adjust,args)]);expect(entries[0]).toBe(entries[1]);const mine=await u.query(api.wallets.mine,{});expect(mine?.wallet.balance).toBe(100);expect(mine?.ledger).toHaveLength(1);await expect(a.mutation(api.wallets.adjust,{...args,amount:50})).rejects.toThrow();});
it('rejects overdrafts and invalid numbers atomically',async()=>{const {a,u,id}=await fixture();for(const amount of [-1,1.5,1000001,0])await expect(a.mutation(api.wallets.adjust,{walletId:id,key:'invalid-123',amount,note:'test'})).rejects.toThrow();expect((await u.query(api.wallets.mine,{}))?.wallet.balance).toBe(0);expect((await u.query(api.wallets.mine,{}))?.ledger).toHaveLength(0);});
it('enforces model and clip permissions without debiting quotes',async()=>{const {a,u,id}=await fixture();await a.mutation(api.wallets.saveRate,{model:'Veo 3.1 Fast',resolution:'720p',seconds:8,points:20});await expect(u.query(api.wallets.quote,{model:'Veo 3.1 Fast',resolution:'720p',seconds:8,count:1})).rejects.toThrow();await a.mutation(api.wallets.permissions,{walletId:id,enabled:true,models:['Veo 3.1 Fast'],maxClips:2});const q=await u.query(api.wallets.quote,{model:'Veo 3.1 Fast',resolution:'720p',seconds:8,count:2});expect(q).toMatchObject({total:40,sufficient:false,flowConsumptionConfirmed:false});await expect(u.query(api.wallets.quote,{model:'Veo 3.1 Fast',resolution:'720p',seconds:8,count:3})).rejects.toThrow();await expect(u.query(api.wallets.quote,{model:'Veo 3.1 Quality',resolution:'720p',seconds:8,count:1})).rejects.toThrow();expect((await u.query(api.wallets.mine,{}))?.wallet.balance).toBe(0);});
it('imports actual observed cost and preserves manual prices, refusing stale readings',async()=>{const {t,a}=await fixture(),option={model:'Veo 3.1 Fast',actualModel:'Veo 3.1 - Fast',seconds:8,resolution:'720p' as const,aspect:'9:16',cost:20};await t.mutation(internal.pipeline.presence,{workerId:'w',state:'online',options:[option],observedAt:Date.now()});expect(await a.mutation(api.wallets.importObserved,{})).toBe(1);expect((await a.query(api.wallets.adminState,{})).rates[0]).toMatchObject({points:20,source:'flow'});await a.mutation(api.wallets.saveRate,{model:option.model,resolution:option.resolution,seconds:8,points:25});expect(await a.mutation(api.wallets.importObserved,{})).toBe(0);await t.run(async ctx=>{const w=await ctx.db.query('workers').first();await ctx.db.patch(w!._id,{observedAt:Date.now()-3600001})});await expect(a.mutation(api.wallets.importObserved,{})).rejects.toThrow();});
