import {expect,it} from 'vitest';
import {episodeDuration,filmOptions} from './film-experience';
import {validateEpisodeSegments,type FilmPlan} from './film-plan';
import {productionClips} from './film-production';
import {parseFilmProposal} from './film-chat';
const refs=[{_id:'noor',kind:'character',name:'نور',description:'ثوب أزرق',fileId:'noor-image'},{_id:'street',kind:'place',name:'الشارع',description:'عراقي'}];
function plan(seconds:number,unit:number):FilmPlan{return {title:'البداية',synopsis:'مغامرة نور',ending:'يجد الطريق',scenes:Array.from({length:seconds/unit},(_,i)=>({seconds:unit,description:'نور يتقدم في القصة '+i,dialogue:'',cast:['noor'],place:'street',continuity:'يكمل حركة الخطوة السابقة'}))};}
it('produces a full minute as six Omni parts and 64 seconds as eight Veo parts',()=>{for(const [model,unit,count,duration,price] of [['Omni Flash',10,6,60,7],['Veo 3.1 Fast',8,8,64,20]] as const){expect(episodeDuration(60,unit)).toBe(duration);const p=plan(duration,unit);expect(()=>validateEpisodeSegments(p,duration,unit)).not.toThrow();const clips=productionClips(p,{model,actualModel:model,seconds:unit,resolution:'360p',aspect:'9:16',cost:price},refs,'واقعي','عراقي');expect(clips).toHaveLength(count);expect(clips.reduce((n,c)=>n+c.target,0)).toBe(duration);expect(clips.length*price).toBe(model==='Omni Flash'?42:160);expect(clips[0].referenceIds).toEqual(['noor-image']);expect(clips[0].prompt).toContain('1: نور');expect(clips.slice(1).every(c=>c.prompt.includes('استمر مباشرة من آخر إطار'))).toBe(true);}});
it('rejects invalid or incomplete episode division',()=>{expect(()=>validateEpisodeSegments(plan(60,10),64,8)).toThrow();expect(()=>episodeDuration(300,8)).toThrow();expect(()=>episodeDuration(60,6)).toThrow();});
it('only offers the requested observed Omni and Veo Fast configurations',()=>{const base={actualModel:'fixture',resolution:'720p' as const,aspect:'9:16',cost:1};expect(filmOptions([{...base,model:'Omni Flash',seconds:10},{...base,model:'Omni Flash',seconds:8},{...base,model:'Veo 3.1 Fast',seconds:8},{...base,model:'Veo 3.1 Quality',seconds:8}]).map(o=>o.model)).toEqual(['Omni Flash','Veo 3.1 Fast']);});

it('carries the agreed episode duration from discussion without treating it as payment approval',()=>{expect(parseFilmProposal(JSON.stringify({proposal:{style:'واقعي',dialect:'العراقية',episodes:3,seconds:60}}))).toEqual({style:'واقعي',dialect:'العراقية',episodes:3,seconds:60});expect(parseFilmProposal('{"proposal":null}')).toBeUndefined();expect(()=>parseFilmProposal(JSON.stringify({proposal:{style:'واقعي',dialect:'العراقية',episodes:3,seconds:0}}))).toThrow();});
