export type FilmScene={seconds:number;description:string;dialogue:string;cast:string[];place:string;continuity:string};
export type FilmPlan={title:string;synopsis:string;ending:string;scenes:FilmScene[]};
export function previousPlans(episodes:{episode:number;version:number;plan:FilmPlan}[],before:number){return JSON.stringify(episodes.filter(e=>e.episode<before&&!episodes.some(o=>o.episode===e.episode&&o.version>e.version)).sort((a,b)=>a.episode-b.episode).map(e=>({episode:e.episode,plan:e.plan})));}
export const PLAN_INSTRUCTIONS=`أنت كاتب سيناريو مشهد. اصنع الحلقة المطلوبة من الاتفاق والمراجع والحلقات السابقة المعتمدة فقط. لا تغير قرارات المستخدم ولا تضف شخصية غير مسجلة. حافظ على الملامح والملابس والأماكن وتسلسل القصة؛ اذكر استمرارية كل مشهد. حوار صوتي فقط، دون كتابة أو شعار أو ترجمة فوق الصورة. لا تذكر أدوات الخدمة أو كلفة أو توليد. أرجع خطة درامية قابلة للمراجعة، لا فيديو. مدة المشاهد مجموعها يساوي المدة المطلوبة تمامًا. بين 1 و12 مشهدًا؛ المشهد وحدة سردية وليس وحدة توليد. cast وplace معرّفات من سجل المراجع المرفق. اكتب وصفًا واضحًا للأفعال وحركة الكاميرا وطاقم المشهد ومن يتحدث؛ تجنب ظهور رأس أو شخص عابر غير مطلوب. ending يحدد نقطة الاستمرار للحلقة التالية.`;
export const planSchema={type:'object',properties:{title:{type:'string'},synopsis:{type:'string'},ending:{type:'string'},scenes:{type:'array',items:{type:'object',properties:{seconds:{type:'integer'},description:{type:'string'},dialogue:{type:'string'},cast:{type:'array',items:{type:'string'}},place:{type:'string'},continuity:{type:'string'}},required:['seconds','description','dialogue','cast','place','continuity'],additionalProperties:false}}},required:['title','synopsis','ending','scenes'],additionalProperties:false};
export function validatePlan(plan:FilmPlan,seconds:number,refs:{_id:string;kind:string}[]){
 const bounded=(s:unknown,max:number)=>typeof s==='string'&&s.length<=max;
 if(!bounded(plan.title,120)||!plan.title.trim()||!bounded(plan.synopsis,3000)||!bounded(plan.ending,1500)||!Array.isArray(plan.scenes)||plan.scenes.length<1||plan.scenes.length>12)throw new Error('الخطة غير صالحة؛ يجب أن تحتوي من 1 إلى 12 مشهدًا.');
 for(const s of plan.scenes){if(!Number.isSafeInteger(s.seconds)||s.seconds<1||!bounded(s.description,2000)||!s.description.trim()||!bounded(s.dialogue,1500)||!bounded(s.continuity,1000)||!Array.isArray(s.cast)||s.cast.length>12||new Set(s.cast).size!==s.cast.length||s.cast.some(id=>!refs.some(r=>r._id===id&&r.kind==='character'))||!refs.some(r=>r._id===s.place&&r.kind==='place'))throw new Error('تحقق من مدة المشهد وشخصياته ومكانه المسجل.');}
 if(plan.scenes.reduce((n,s)=>n+s.seconds,0)!==seconds)throw new Error('مجموع مدد المشاهد يجب أن يساوي مدة الحلقة المطلوبة.');
 if(/sk-[\w-]{12,}|OPENAI_API_KEY|google flow|\bworker\b|\bconvex\b/i.test(JSON.stringify(plan)))throw new Error('الخطة تحتوي بيانات غير مناسبة.');
 return plan;
}
