// Separate production instructions from the dialogue the audience hears.
export function isIraqiDialect(value:string){return /عراق|بغداد|iraqi/i.test(value.normalize('NFKC').replace(/[\u064b-\u065f\u0670]/g,''));}
export const IRAQI_STORY_GUIDE=`اللهجة العراقية: احكِ مع الزبون بعراقي طبيعي وواضح، وبغدادي مفهوم كخيار افتراضي عندما لم تُحدد منطقة. احترم لهجة المحافظة إذا حددها صاحب القصة، ولا تخلطها بلهجة أخرى. استعمل المفردات حسب المعنى، مثل: شنو، شلون، ليش، هسه، شكد، أكو، ماكو، أريد، راح، إي، زين. لا تحشر هذه الكلمات بكل جملة ولا تقلّد اللهجة بصورة ساخرة. اضبط مخاطبة الرجل والمرأة والمفرد والجمع؛ مثل إنتَ/إنتِ حسب الشخصية، وخلي كلام الأطفال مناسبًا لعمرهم. قدّم رأيك وناقش منطق الأحداث والتوتر الدرامي، مو مجرد موافقة. حافظ على تفاصيل العراق المذكورة من صاحب القصة؛ لا تفترض بغداد أو عشيرة أو دين أو زيًا نمطيًا إذا لم يُطلب.`;
export const IRAQI_PLAN_GUIDE=`عند اختيار العراقية: اكتب وصف الأحداث وحركة الكاميرا والاستمرارية بالإنكليزية الواضحة، واكتب dialogue وحده باللهجة العراقية الطبيعية والمنطوقة. سمِّ المتكلم في كل دور، واجعل لكل شخصية نبرة ثابتة مرتبطة بعمرها وشخصيتها، ولا تغيّر مفرداتها أو لهجتها بين المقاطع. راجع الحوار لغويًا قبل إخراج الخطة؛ صحح خلط المصرية أو الشامية أو الخليجية بالفصحى في الكلام المنطوق، مع الحفاظ على المعنى والأسماء. استخدم عراقيًا مفهومًا افتراضيًا، أو لهجة المنطقة التي اتُّفق عليها. الكلمات العامة مثل «تعال» و«شكرًا» مقبولة؛ لا تفرض كلمات عامية مصطنعة. اكتب حوارًا قصيرًا قابلًا للنطق بزمن المشهد مع وقفات طبيعية، ولا تملأ كل ثانية بالكلام. لا تضف شرحًا فنيًا أو اسم المتكلم إلى الكلام المسموع.`;
export function discussionLanguage(dialect:string){return isIraqiDialect(dialect)?IRAQI_STORY_GUIDE+'\nاختيار اللهجة المحفوظ هو العراقية؛ التزم به، إلا إذا طلب الزبون في النقاش تغيير اللهجة صراحةً.':`اختيار اللهجة المحفوظ: ${JSON.stringify(dialect)}. ناقش القصة بهذه اللهجة؛ لا تفرض العراقية. اتبع أي تغيير صريح يطلبه الزبون.`;}
export function voiceDirection(dialect:string){return isIraqiDialect(dialect)?`لغة تعليمات الصورة: العربية الفصحى. لغة الكلام المسموع: العربية باللهجة العراقية، بلكنة عراقية طبيعية ثابتة. التعليمات الفنية ليست حوارًا ولا تُقرأ بصوت. انطق الحوار المعتمد بمعناه وكلماته العراقية؛ لا تحوّله إلى الفصحى أو المصرية أو الشامية أو الخليجية أو الإنجليزية. لا تنطق أسماء المتكلمين أو عناوين الأقسام. حافظ على صوت كل شخصية ولهجتها في التكملة من آخر لقطة، واضبط حركة الفم مع الكلام. لا تضع ترجمة أو كلامًا مكتوبًا على الفيديو. إذا لم يوجد حوار معتمد، لا تضف كلامًا.`:`اللهجة المنطوقة المطلوبة: ${JSON.stringify(dialect)}. التعليمات الفنية ليست حوارًا؛ التزم بالكلام المعتمد دون تبديل اللهجة أو إضافة كتابة على الفيديو.`;}
export function assertIraqiDialogue(dialogue:string,dialect:string){if(!isIraqiDialect(dialect)||!dialogue.trim())return;const spoken=dialogue.normalize('NFKC').replace(/[\u064b-\u065f\u0670]/g,'').replace(/^[^:\n]{1,100}:\s*/gm,'');if(/(?:^|[^\p{L}])(?:إزاي|ازاي|عايز|عاوز|عايزة|عاوزة|هلق|هلأ|بدي|أبغى|ابغى|تبغى|تبي|شو)(?=$|[^\p{L}])/u.test(spoken))throw new Error('الحوار يحتوي مفردات من لهجة أخرى؛ راجع صياغته باللهجة العراقية.');}

export function filmVoiceDirection(dialect:string){return isIraqiDialect(dialect)?'Production instructions are in English; spoken dialogue must be natural Iraqi Arabic, with a consistent Iraqi accent. Speak only the approved Iraqi words verbatim. Never translate dialogue into English, formal Arabic, or another dialect. Speaker labels identify who speaks and must never be read aloud. Preserve each character voice and synchronize lip movement. No subtitles, captions, logos or on-screen text. If no dialogue is supplied, add no speech.':`Speak only the approved dialogue verbatim in the selected dialect: ${JSON.stringify(dialect)}. English production instructions and speaker labels must not be spoken. Preserve each character voice, synchronize lips, and add no subtitles or on-screen text.`; }
