export type SocialPlatform='facebook'|'instagram';
export const socialNames={facebook:'فيسبوك',instagram:'إنستغرام'};
export function socialCaption(value:string){if(value.length>2200)throw new Error('الوصف يجب ألا يتجاوز 2200 حرف.');return value.trim();}
export async function stateHash(value:string){return Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(value)))).map(n=>n.toString(16).padStart(2,'0')).join('');}
function bytes(value:string){return Uint8Array.from(atob(value),c=>c.charCodeAt(0));}
function base64(value:Uint8Array){return btoa(String.fromCharCode(...value));}
async function encryptionKey(key:string){const data=bytes(key);if(data.length!==32)throw new Error('Social encryption key unavailable');return crypto.subtle.importKey('raw',data,'AES-GCM',false,['encrypt','decrypt']);}
export async function sealToken(value:string,key:string,subject:string){const iv=crypto.getRandomValues(new Uint8Array(12)),data=await crypto.subtle.encrypt({name:'AES-GCM',iv,additionalData:new TextEncoder().encode(subject)},await encryptionKey(key),new TextEncoder().encode(value));return base64(iv)+'.'+base64(new Uint8Array(data));}
export async function openToken(value:string,key:string,subject:string){const [iv,data]=value.split('.');return new TextDecoder().decode(await crypto.subtle.decrypt({name:'AES-GCM',iv:bytes(iv),additionalData:new TextEncoder().encode(subject)},await encryptionKey(key),bytes(data)));}
export async function verifyMetaRequest(value:string,secret:string){const parts=value.split('.');if(parts.length!==2)throw new Error('Invalid signed request');const decode=(v:string)=>bytes(v.replace(/-/g,'+').replace(/_/g,'/').padEnd(Math.ceil(v.length/4)*4,'='));const key=await crypto.subtle.importKey('raw',new TextEncoder().encode(secret),{name:'HMAC',hash:'SHA-256'},false,['verify']);if(!await crypto.subtle.verify('HMAC',key,decode(parts[0]),new TextEncoder().encode(parts[1])))throw new Error('Invalid signature');const payload=JSON.parse(new TextDecoder().decode(decode(parts[1]))) as {algorithm?:string;user_id?:string};if(payload.algorithm?.toUpperCase()!=='HMAC-SHA256'||!payload.user_id||!/^\d+$/.test(payload.user_id))throw new Error('Invalid signed request');return payload.user_id;}
