import type {Page,BrowserContext} from 'playwright';
import {workspace} from './browser';
import {openSettings,attachments} from './flow';
import {sleep} from './runtime';
import {imageModels,imageAspects,type ImageOption} from '../shared/images';
import {validateFile,validateSignature} from '../shared/validation';
import {writeFile} from 'node:fs/promises';
export type ImageAsset={id:string;url:string;width:number;height:number};
async function choose(page:Page,text:string){const radio=page.getByRole('radio').filter({hasText:text});if(await radio.count()!==1||!await radio.isEnabled())throw new Error(`IMAGE_OPTION_UNSUPPORTED: ${text}`);await radio.click();const deadline=Date.now()+5000;while(Date.now()<deadline){if(await radio.getAttribute('aria-checked')==='true')return;await sleep(100);}throw new Error(`IMAGE_OPTION_NOT_SELECTED: ${text}`);}
export async function configureImage(page:Page,model:string,aspect:string):Promise<ImageOption>{await workspace(page);if(new URL(page.url()).pathname.includes('/edit/'))throw new Error('IMAGE_EDITOR_NOT_WORKSPACE');await openSettings(page);await choose(page,'صورة');await page.getByRole('button',{name:'اختيار فئة النماذج',exact:true}).click();if(!imageModels.some(m=>m===model))throw new Error('IMAGE_MODEL_UNSUPPORTED');const selection=page.getByRole('menuitem').filter({hasText:new RegExp(`${model}\\s*$`)});if(await selection.count()!==1)throw new Error('IMAGE_MODEL_UNAVAILABLE');await selection.click();await choose(page,aspect);await choose(page,'x1');await sleep(150);const text=await page.locator('body').innerText(),cost=text.match(/ستستهلك عملية الإنشاء\s+([0-9]+)\s+من الوحدات/);if(!cost)throw new Error('IMAGE_COST_UNKNOWN');await page.keyboard.press('Escape');return {model,aspect,cost:Number(cost[1])};}
// Settings inspection only: no generation button in this module's capability reader.
export async function imageCapabilities(page:Page){const result:ImageOption[]=[];for(const model of imageModels)for(const aspect of imageAspects)result.push(await configureImage(page,model,aspect));return result;}
export async function imageAssets(page:Page):Promise<ImageAsset[]>{return page.locator('flow-image-tile img[data-media-id]').evaluateAll(nodes=>nodes.flatMap(node=>{const im=node as HTMLImageElement,id=im.getAttribute('data-media-id')??'';return /^[a-zA-Z0-9-]{16,100}$/.test(id)&&im.complete&&im.naturalWidth>0&&im.naturalHeight>0&&/^https:\/\//.test(im.src)?[{id,url:im.src,width:im.naturalWidth,height:im.naturalHeight}]:[]}));}
export async function attachImageReferences(page:Page,files:string[]){await attachments(page,files);}
export async function waitImage(page:Page,baseline:string[],id:string|undefined,stopped:()=>boolean):Promise<ImageAsset>{const deadline=Date.now()+10*60*1000;while(Date.now()<deadline){if(stopped())throw new Error('STOPPED: image follow-up saved');await workspace(page);const body=(await page.locator('body').innerText()).slice(-12000);if(/تعذّر الإنشاء|فشل الإنشاء|غير متاحة.*بلد|وحدات غير كافية|generation failed|unusual traffic/i.test(body))throw new Error('FLOW_IMAGE_BLOCKED');const candidates=(await imageAssets(page)).filter(a=>id?a.id===id:!baseline.includes(a.id));if(candidates.length===1)return candidates[0];if(candidates.length>1)throw new Error('IMAGE_IDENTITY_AMBIGUOUS');await sleep(2000)}throw new Error('IMAGE_FOLLOW_UP_REQUIRED: no resubmission');}
export async function downloadImage(context:BrowserContext,asset:ImageAsset,destination:string){if(!/^[a-zA-Z0-9-]{16,100}$/.test(asset.id)||!new URL(asset.url).pathname.includes(asset.id))throw new Error('IMAGE_IDENTITY_MISMATCH');const response=await context.request.get(asset.url,{timeout:60000});if(!response.ok())throw new Error('IMAGE_DOWNLOAD_FAILED');const bytes=await response.body();const type=bytes[0]===137?'image/png':bytes[0]===255?'image/jpeg':'image/webp';validateFile(type,bytes.length,'image');validateSignature(bytes,type);await writeFile(destination,bytes,{mode:0o600});return {type,size:bytes.length};}
