// Deliberately has no imports from cli/browser/flow: exporting never submits a generation.
import {mkdir,readFile,writeFile,rename,open,unlink,stat} from 'node:fs/promises';
import {resolve,basename} from 'node:path';
import {randomUUID} from 'node:crypto';
import {root,connection,rpc,read,persist,sleep} from './runtime';
import {tools,command,probe,decode,hashFile,alpha,subtitles} from './montage-media';
import {validateEdit,editDimensions,type ExportPhase} from '../shared/editing';
import type {Doc,Id} from '../convex/_generated/dataModel';
const name=process.argv[2]??'status',id=process.argv[3];
const local=resolve(root,'montage');await mkdir(local,{recursive:true});
if(name==='status'){const processState=await read<{pid:number;running:boolean}>('montage-process.json');let running=false;if(processState?.running)try{process.kill(processState.pid,0);running=true;}catch{/* stale process */}console.log({running,process:processState,job:await read('montage-status.json')});process.exit(0);}
if(name==='stop'){await persist('montage-stop.json',{stop:true});console.log('Montage stop requested. No Flow action.');process.exit(0);}
if(name==='check'){console.log((await command(tools.ffmpeg,['-version'])).toString().split('\n')[0]);console.log((await command(tools.ffprobe,['-version'])).toString().split('\n')[0]);process.exit(0);}
if(!['run','resume','reupload','watch'].includes(name)||name!=='watch'&&!/^[a-zA-Z0-9]+$/.test(id??''))throw new Error('Use montage:run/resume/reupload -- EXPORT_ID or montage:watch');
const lockPath=resolve(local,'editor.lock');
async function lock(){try{const f=await open(lockPath,'wx');await f.writeFile(String(process.pid));await f.close();}catch(e){if((e as NodeJS.ErrnoException).code!=='EEXIST')throw e;const pid=Number(await readFile(lockPath,'utf8'));try{process.kill(pid,0);}catch{await unlink(lockPath);return lock();}throw new Error('Montage already running.',{cause:e});}}
await lock();await persist('montage-process.json',{pid:process.pid,running:true,mode:name,startedAt:new Date().toISOString()});await persist('montage-stop.json',{stop:false});const control=new AbortController();const stopTimer=setInterval(()=>{void read<{stop:boolean}>('montage-stop.json').then(v=>{if(v?.stop)control.abort()}).catch(()=>control.abort())},1000);process.on('SIGINT',()=>control.abort());process.on('SIGTERM',()=>control.abort());
async function execute(exportId:string){
 const cfg=await connection(),identity={exportId:exportId as Id<'exports'>,workerId:cfg.workerId,fence:randomUUID()};
 const job=await rpc<Doc<'exports'>>('editClaim',identity);const dir=resolve(local,exportId);await mkdir(dir,{recursive:true});
 const heartbeat=setInterval(()=>{void rpc('editHeartbeat',identity).catch(()=>control.abort())},15000);
 const journalName=`montage/${exportId}.json`;let journal=await read<{verified?:boolean;hash?:string;media?:Doc<'exports'>['media'];encodeRuns:number;normalizedRuns?:number;prepared?:boolean}>(journalName)??{encodeRuns:0};
 async function phase(status:ExportPhase,percent?:number){await rpc('editProgress',{...identity,status,percent});await persist('montage-status.json',{pid:process.pid,exportId,status,percent,updatedAt:new Date().toISOString()});console.log(status,percent===undefined?'':`${percent}%`);}
 async function fetchFile(storageId:string,file:string){const path=resolve(dir,file);const meta=await mediaRequest(storageId,{metadata:true});const info=await meta.json() as {size:number;hash:string};try{if((await stat(path)).size===info.size&&await hashFile(path)===info.hash)return path;}catch{/* missing or incomplete cache */}if(!Number.isSafeInteger(info.size)||info.size<=0||info.size>100*1024*1024)throw new Error('Invalid stored file');const parts:Buffer[]=[];for(let offset=0;offset<info.size;offset+=8*1024*1024){control.signal.throwIfAborted();const r=await mediaRequest(storageId,{offset});parts.push(Buffer.from(await r.arrayBuffer()));}const bytes=Buffer.concat(parts);if(bytes.length!==info.size)throw new Error('Incomplete source download');await writeFile(path+'.part',bytes);if(await hashFile(path+'.part')!==info.hash)throw new Error('Source hash mismatch');await rename(path+'.part',path);return path;}
 async function mediaRequest(storageId:string,extra:object){const r=await fetch(`${cfg.site}/runner`,{method:'POST',headers:{Authorization:`Bearer ${cfg.token}`,'Content-Type':'application/json'},body:JSON.stringify({op:'editFile',args:{exportId,storageId,...extra}}),signal:AbortSignal.any([control.signal,AbortSignal.timeout(30000)])});if(!r.ok)throw new Error(`Protected source refused (${r.status})`);return r;}
 let last=0,progressError:unknown,chain:Promise<void>=Promise.resolve();
 async function ff(args:string[],status:ExportPhase,duration:number){await phase(status);await command(tools.ffmpeg,['-hide_banner','-y',...args,'-progress','pipe:1','-nostats'],dir,seconds=>{if(!Number.isFinite(seconds))return;const percent=Math.max(0,Math.min(99,Math.floor(seconds/duration*100)));if(Date.now()-last>1000){last=Date.now();chain=chain.then(()=>phase(status,percent)).catch(e=>{progressError=e;control.abort();});}},control.signal);await chain;if(progressError)throw progressError;}
 const final=resolve(dir,'final.mp4');
 try{
  validateEdit(job.settings);const s=job.settings;
  // The only upload retry path uses a previously validated file and the saved hash.
  if(journal.verified){const m=await probe(final);await decode(final,control.signal);if(await hashFile(final)!==journal.hash||Math.abs(m.duration-s.duration)>.12)throw new Error('Saved output no longer matches checkpoint');}
  else{
   if(name==='reupload')throw new Error('No verified output to re-upload. Use resume.');
   await phase('preparing');const sources:Awaited<ReturnType<typeof probe>>[]=[];const paths:string[]=[];
   for(let i=0;i<s.clips.length;i++){const path=await fetchFile(s.clips[i].storageId,`source-${i}.mp4`);const m=await probe(path);if(!Number.isFinite(m.duration)||s.clips[i].end>m.duration+.04)throw new Error(`المقطع ${i+1} أقصر من نهاية القص: ${m.duration.toFixed(3)} ث`);await decode(path,control.signal);sources.push(m);paths.push(path);}
   const audio=sources.some(m=>m.audio),{width:w,height:h}=editDimensions(s);
   let logo:string|undefined;if(s.logo.enabled){if(!job.logoId)throw new Error('No logo');logo=await fetchFile(job.logoId,'logo-image');const a=await alpha(logo);await writeFile(resolve(dir,'logo-alpha.json'),JSON.stringify(a));if(!a.valid)throw new Error('الشعار لا يحتوي قناة Alpha وبكسلات شفافة حقيقية. استبدله أو عطّل الشعار.');}
   for(let i=0;i<paths.length;i++){
    const c=s.clips[i],target=resolve(dir,`normalized-${i}.mp4`);let valid=false;try{const p=await probe(target);valid=p.width===w&&p.height===h&&Math.abs(p.duration-(c.end-c.start))<.1;if(valid)await decode(target,control.signal);}catch{valid=false;}
    if(valid)continue;
    const scale=s.fit==='contain'?`scale=${w}:${h}:force_original_aspect_ratio=decrease,pad=${w}:${h}:(ow-iw)/2:(oh-ih)/2:color=black`:`scale=${w}:${h}:force_original_aspect_ratio=increase,crop=${w}:${h}`;
    const args=['-ss',String(c.start),'-i',paths[i]];if(audio&&!sources[i].audio)args.push('-f','lavfi','-i','anullsrc=r=48000:cl=stereo');args.push('-t',String(c.end-c.start),'-map','0:v:0','-vf',`${scale},setsar=1,fps=30,format=yuv420p`,'-c:v','libx264','-preset','veryfast','-crf','19');if(audio)args.push('-map',sources[i].audio?'0:a:0':'1:a:0','-af','aresample=48000','-ac','2','-c:a','aac');else args.push('-an');args.push(`normalized-${i}.part.mp4`);await ff(args,'preparing',c.end-c.start);await rename(resolve(dir,`normalized-${i}.part.mp4`),target);journal.normalizedRuns=(journal.normalizedRuns??0)+1;await persist(journalName,journal);
   }
   journal.prepared=true;await persist(journalName,journal);if(process.argv.includes('--test-pause-after-preparing')){console.log('Test checkpoint: prepared. Stop then resume in a new process.');while(!control.signal.aborted)await sleep(500);control.signal.throwIfAborted();}
   const total=s.clips.reduce((n,c)=>n+c.end-c.start,0)-s.transition*(s.clips.length-1);const mergeArgs:string[]=[];for(let i=0;i<paths.length;i++)mergeArgs.push('-i',`normalized-${i}.mp4`);
   const filters:string[]=[];let video='0:v',sound='0:a';
   if(s.clips.length>1&&s.transition>0){for(let i=0;i<paths.length;i++)filters.push(`[${i}:v]settb=AVTB,setpts=PTS-STARTPTS[v${i}]`);video='v0';let offset=s.clips[0].end-s.clips[0].start;for(let i=1;i<paths.length;i++){offset-=s.transition;filters.push(`[${video}][v${i}]xfade=transition=fade:duration=${s.transition}:offset=${offset}[vx${i}]`);video=`vx${i}`;if(audio){filters.push(`[${sound}][${i}:a]acrossfade=d=${s.transition}:c1=tri:c2=tri[ax${i}]`);sound=`ax${i}`;}offset+=s.clips[i].end-s.clips[i].start;}}
   else if(s.clips.length>1){filters.push(`${paths.map((_,i)=>`[${i}:v]${audio?`[${i}:a]`:''}`).join('')}concat=n=${paths.length}:v=1:a=${audio?1:0}[joined]${audio?'[joinedA]':''}`);video='joined';sound='joinedA';}
   if(filters.length)mergeArgs.push('-filter_complex',filters.join(';'));mergeArgs.push('-map',video.includes(':')?video:`[${video}]`);if(audio)mergeArgs.push('-map',sound.includes(':')?sound:`[${sound}]`,'-c:a','aac');else mergeArgs.push('-an');mergeArgs.push('-c:v','libx264','-preset','veryfast','-crf','19','-t',String(total),'merged.part.mp4');await ff(mergeArgs,'merging',total);await rename(resolve(dir,'merged.part.mp4'),resolve(dir,'merged.mp4'));
   await phase('overlay');const lines=await subtitles(resolve(dir,'titles.ass'),s,job.texts);const args=['-i','merged.mp4'];if(logo)args.push('-i',basename(logo));const f:string[]=[];let base='0:v';if(lines.length){f.push(`[0:v]ass=titles.ass[text]`);base='text';}if(logo){const size=Math.round(w*s.logo.size/100/2)*2;f.push(`[1:v]scale=${size}:-2[logo]`);const x=s.logo.position.endsWith('right')?'W-w-40':'40',y=s.logo.position.startsWith('top')?'40':'H-h-40';f.push(`[${base}][logo]overlay=x=${x}:y=${y}:enable='between(t,${s.logo.start},${s.logo.end})'[over]`);base='over';}if(f.length)args.push('-filter_complex',f.join(';'));args.push('-map',base.includes(':')?base:`[${base}]`);if(audio)args.push('-map','0:a:0','-c:a','aac');else args.push('-an');args.push('-t',String(s.duration),'-c:v','libx264','-preset','veryfast','-crf','20','-pix_fmt','yuv420p','-movflags','+faststart','final.part.mp4');journal.encodeRuns++;await persist(journalName,journal);await ff(args,'encoding',s.duration);await rename(resolve(dir,'final.part.mp4'),final);
   await phase('verifying');const m=await probe(final);await decode(final,control.signal);if(m.codec!=='h264'||m.audio&&m.audioCodec!=='aac'||m.width!==w||m.height!==h||Math.abs(m.duration-s.duration)>.12||m.size<=0||m.size>100*1024*1024)throw new Error('Final media verification failed');
   journal={...journal,verified:true,hash:await hashFile(final),media:{duration:m.duration,width:m.width,height:m.height,size:m.size,audio:m.audio,sources:sources.map((v,i)=>({storageId:s.clips[i].storageId,width:v.width,height:v.height,duration:v.duration}))}};await persist(journalName,journal);
  }
  await phase('uploading');if(process.argv.includes('--test-upload-failure'))throw new Error('اختبار مونتاج: فشل رفع مقصود بعد حفظ الملف المتحقق؛ استعمل reupload دون إعادة تصدير.');
  const key=`video:${journal.hash}`,ticket=await rpc<{url:string|null;storageId:Id<'_storage'>|null}>('editUpload',{...identity,key,size:journal.media!.size});let storageId=ticket.storageId;
  if(!storageId){const bytes=await readFile(final);const r=await fetch(ticket.url!,{method:'POST',headers:{'Content-Type':'video/mp4'},body:bytes,signal:AbortSignal.any([control.signal,AbortSignal.timeout(120000)])});if(!r.ok)throw new Error(`Upload failed (${r.status})`);storageId=(await r.json() as {storageId:Id<'_storage'>}).storageId;}
  await rpc('editFinish',{...identity,key,storageId,media:journal.media});await persist('montage-status.json',{exportId,status:'completed',media:journal.media,encodeRuns:journal.encodeRuns});console.log('Export completed',exportId,journal.media);
 }catch(e){const error=(progressError instanceof Error?progressError.message:control.signal.aborted?'توقف المونتاج؛ استعمل resume لاستكمال المقاطع المحفوظة دون توليد.':e instanceof Error?e.message:'Montage failed').replace(/https?:\/\/\S+/g,'[URL]').slice(0,1200);await rpc('editProgress',{...identity,status:'failed',error}).catch(()=>undefined);await persist('montage-status.json',{exportId,status:'failed',error,encodeRuns:journal.encodeRuns});throw new Error(error,{cause:e});}
 finally{clearInterval(heartbeat);}
}
try{if(name==='watch'){console.log('Montage queue only. No generation.');while(!control.signal.aborted){const next=await rpc<string|null>('editPending',{});if(next){try{await execute(next);}catch(e){console.error((e as Error).message)}}else await sleep(2000);}}else await execute(id!);}
catch(e){console.error((e instanceof Error?e.message:'Montage failed').replace(/https?:\/\/\S+/g,'[URL]'));process.exitCode=1;}
finally{await persist('montage-process.json',{pid:process.pid,running:false,mode:name,endedAt:new Date().toISOString()});clearInterval(stopTimer);await unlink(lockPath).catch(()=>undefined);}
