import {memo} from 'react';
import {motion, useReducedMotion} from 'motion/react';
import {Film, Sparkles, Palette, Download, MessageCircle, Users, Images, Layers, Play} from 'lucide-react';
import {useQuery} from 'convex/react';
import {api} from '../convex/_generated/api';
import type {Id} from '../convex/_generated/dataModel';
import {taskSteps} from '../shared/studio';

const particles=Array.from({length:22},(_,i)=>({left:`${(i*43+11)%100}%`,top:`${(i*29+7)%100}%`,delay:`${-i*1.7}s`,size:i%4===0?4:2}));

export function AdAmbient(){return <div className="ad-ambient" aria-hidden="true"><div className="ad-nebula"/><svg className="ad-light-trails" viewBox="0 0 1448 1086" preserveAspectRatio="xMidYMid slice"><defs><linearGradient id="ad-trail" x1="0" x2="1"><stop stopColor="#367eff" stopOpacity="0"/><stop offset=".5" stopColor="#a665ff"/><stop offset="1" stopColor="#3aa4ff" stopOpacity="0"/></linearGradient></defs><g fill="none" stroke="url(#ad-trail)"><path d="M-100 60C230 710 900-250 1630 140"/><path d="M-180 340C280 1050 810 370 1630 820"/><path d="M-70 850C460 570 680 1250 1590 910"/><path d="M-100 1090C340 650 530 1190 1640 740"/></g><g fill="#27447a" opacity=".25"><path d="M0 1086V982l52-57 70 54 101-36 76 34 87-74 109 68 80-38 110 47 140-25 80 36 120-79 89 75 80-44 92 69 162-105v179z"/></g></svg>{particles.map((p,i)=><i key={i} style={{left:p.left,top:p.top,width:p.size,height:p.size,animationDelay:p.delay}}/>)}</div>}

/** Decorative vector scenes, never presented as generated videos or uploaded references. */
function SceneArt({kind}:{kind:'cafe'|'room'|'coffee'}){return <svg viewBox="0 0 100 130" aria-hidden="true"><defs><linearGradient id={`scene-${kind}`} x2=".4" y2="1"><stop stopColor={kind==='coffee'?'#312441':'#395567'}/><stop offset="1" stopColor="#080d22"/></linearGradient></defs><rect width="100" height="130" fill={`url(#scene-${kind})`}/>{kind==='coffee'?<><ellipse cx="50" cy="100" rx="48" ry="12" fill="#a66b46"/><path d="M20 50h56l-6 43H28z" fill="#e4b69a"/><ellipse cx="48" cy="50" rx="28" ry="8" fill="#ebdac0"/><ellipse cx="48" cy="51" rx="22" ry="6" fill="#663726"/><path d="M76 57c29-9 27 32-5 20" fill="none" stroke="#e4b69a" strokeWidth="9"/><path d="M37 37c-12-13 16-13 5-28M56 37c-12-13 16-13 5-28" stroke="#e8d6ff" opacity=".5" strokeWidth="2" fill="none"/></>:<><path d="M0 0h100v12H0zM0 86h100v44H0z" fill="#ae7954"/><path d="M12 14h32v67H12zM54 14h34v67H54z" fill="#0b1e33" stroke="#c99261" strokeWidth="3"/><path d="M16 20h24v35H16zM58 20h26v35H58z" fill="#6a9caa" opacity=".7"/><path d="M28 14v66M71 14v66" stroke="#ccaf83"/><path d="M0 110l100-17M0 126l100-17M25 86L3 130M75 86l23 44" stroke="#d0a585" opacity=".3"/><ellipse cx="50" cy="92" rx="28" ry="7" fill="#cea879"/><path d="M50 98v25M20 99v25M80 99v25" stroke="#392a2b" strokeWidth="5"/><circle cx="22" cy="18" r="5" fill="#f8d798"/><circle cx="77" cy="18" r="5" fill="#f8d798"/>{kind==='room'&&<><path d="M0 61h25v26H0zM78 61h22v26H78z" fill="#bf7657"/><path d="M9 68h10M82 68h10" stroke="#f0bd8a"/></>}</>}</svg>}

const HeroVisual=memo(function HeroVisual(){return <div className="ad-visual" aria-hidden="true"><span className="ad-art-caption" dir="ltr">AI TURNS IDEAS<br/>INTO IMPACT</span><div className="ad-visual-stars"/><div className="ad-orbit ad-orbit-one"/><div className="ad-orbit ad-orbit-two"/><div className="ad-light-sweep"/><div className="ad-platform"><span/><i/></div><div className="ad-icon-perspective"><div className="ad-film-cube"><Film size={105} strokeWidth={1.8}/></div></div><div className="ad-floating-frame frame-room"><SceneArt kind="room"/></div><div className="ad-floating-frame frame-cafe"><SceneArt kind="cafe"/></div><div className="ad-floating-frame frame-coffee"><SceneArt kind="coffee"/></div></div>});

export const CreativeHero=memo(function CreativeHero({requestId}:{requestId?:Id<'requests'>}){const reduce=useReducedMotion(),jobs=useQuery(api.pipeline.state,requestId?{requestId}:'skip'),edits=useQuery(api.editing.state,requestId?{requestId}:'skip'),job=jobs?.[0],steps=taskSteps(job,edits?.exports.find(e=>e._id===job?.exportId));return <motion.section className="ad-hero studio-panel" initial={reduce?false:{opacity:0,scale:.98}} animate={{opacity:1,scale:1}} transition={{duration:.55}} aria-label="مشهد — محركك الإبداعي"><HeroVisual/><div className="ad-hero-copy"><span>كل مشهد يبدأ بفكرة</span><h2>إعلانك القادم{' '}<br/>بين يديك</h2><p>التوليد بالذكاء الاصطناعي.{' '}<br/>ثم إعلان واحد جاهز للتحميل.</p></div><ol className="ad-timeline" aria-label="مراحل صناعة الإعلان">{[{name:'التوليد',icon:Sparkles,detail:'حوّل فكرتك إلى فيديو'},{name:'المعالجة',icon:Sparkles,detail:'تجهيز المقاطع ودمجها'},{name:'التصميم',icon:Palette,detail:'إضافة الهوية والعناصر البصرية'},{name:'التحميل',icon:Download,detail:'إعلانك جاهز للمشاهدة'}].map((s,i)=><li key={s.name} className={job?(steps[i].done?'done':steps[i].active?'active':''):undefined} aria-current={job&&steps[i].active?'step':undefined}><b>{i+1}</b><s.icon size={24}/><strong>{s.name}</strong><small>{job?(steps[i].done?'مكتمل':steps[i].active?steps[i].percent!==undefined?`${steps[i].percent}%`:'جارٍ التنفيذ':'بانتظار المرحلة'):s.detail}</small></li>)}</ol><div className="ad-hero-signature">من فكرة .. إلى تأثير حقيقي</div></motion.section>});

export function AdShortcuts({onPrompt,onFilm,onPhotos,onClips,onResults}:{onPrompt:()=>void;onFilm:()=>void;onPhotos:()=>void;onClips:()=>void;onResults:()=>void}){return <nav className="ad-shortcuts" aria-label="اختصارات الاستوديو">{[{name:'المناقشة',icon:MessageCircle,action:onPrompt,title:'اكتب وصف إعلانك'},{name:'الشخصيات',icon:Users,action:onFilm,title:'فتح استوديو الأفلام والشخصيات الحالي'},{name:'المراجع',icon:Images,action:onPhotos,title:'صور الشارع والمحل'},{name:'الحلقات',icon:Layers,action:onClips,title:'فتح استوديو الأفلام والحلقات الحالي'},{name:'النتائج',icon:Play,action:onResults,title:'فتح طلباتي'}].map(s=><motion.button type="button" key={s.name} onClick={s.action} title={s.title} whileHover={{y:-1}} whileTap={{scale:.98}}><s.icon size={21}/><span>{s.name}</span></motion.button>)}</nav>}

