import { Component, createContext, useContext, useEffect, useRef, useState, type ReactNode } from 'react';
import { ClerkProvider, SignInButton, UserButton, useAuth } from '@clerk/react';
import { arSA } from '@clerk/localizations';
import { ConvexReactClient, useConvex, useConvexAuth, useMutation, useQuery, useAction } from 'convex/react';
import { ConvexProviderWithClerk } from 'convex/react-clerk';
import { api } from '../convex/_generated/api';
import type { Doc, Id } from '../convex/_generated/dataModel';
import type { Draft } from './data';
import { validateFile, validateSignature, type FileKind } from '../shared/validation';
import type {FlowOption,Template} from '../shared/pipeline';
import {canonical} from '../shared/editing';
const config={url:import.meta.env.VITE_CONVEX_URL as string|undefined,site:import.meta.env.VITE_CONVEX_SITE_URL as string|undefined,key:import.meta.env.VITE_CLERK_PUBLISHABLE_KEY as string|undefined};
const complete=!!config.url&&!!config.site&&!!config.key;
const hasConfig=!!config.url||!!config.site||!!config.key;
const validConfig=complete && /^https:\/\/[a-z0-9-]+\.convex\.cloud$/.test(config.url!) && /^https:\/\/[a-z0-9-]+\.convex\.site$/.test(config.site!) && config.url!.replace('.cloud','.site')===config.site && config.key!.startsWith('pk_test_');
const client=validConfig ? new ConvexReactClient(config.url!) : null;
export function cloudError(error:unknown){return error instanceof Error ? error.message : 'تعذر الاتصال. أعد المحاولة باستخدام المسودة نفسها؛ لن يتكرر الطلب.';}
interface CloudContextValue {requests:Doc<'requests'>[]|undefined;selected:Doc<'requests'>|undefined;select:(id:Id<'requests'>)=>void;send:(draft:Draft,submit:boolean)=>Promise<string>;generate:(draft:Draft,option:FlowOption,template:Template)=>Promise<string>;uploadVideo:(file:File)=>Promise<void>;uploadImage:(file:File)=>Promise<Id<"_storage">>;getFile:(id:Id<'_storage'>,signal?:AbortSignal)=>Promise<Blob>;busy:boolean;progress:{name:string;percent:number}|null;error:string;message:string;connected:boolean}
const CloudContext=createContext<CloudContextValue|null>(null);
export const useCloud=()=>useContext(CloudContext);
class Boundary extends Component<{children:ReactNode},{failed:boolean}>{state={failed:false};static getDerivedStateFromError(){return {failed:true};}render(){return this.state.failed?<div className="auth-screen"><h1>تعذر الاتصال بمشروع Convex</h1><p>تحقق من إعدادات Development ونشر وظائف المشروع ثم أعد تحميل الصفحة. المسودات المحلية محفوظة.</p><button onClick={()=>window.location.reload()}>إعادة المحاولة</button></div>:this.props.children;}}
export function CloudRoot({children}:{children:ReactNode}){
 if(!hasConfig)return <><div className="setup-banner">الربط السحابي بانتظار إعداد Convex وتسجيل دخول المالك. المسودات المحلية الحالية محفوظة. راجع README و.env.example.</div>{children}</>;
 if(!client)return <div className="auth-screen"><h1>إعداد Development غير مكتمل</h1><p>أكمل متغيرات Convex وClerk في .env.local. يقبل المشروع مفتاح Clerk التجريبي فقط؛ لم تُفتح البيانات المحلية أو السحابية.</p></div>;
 return <ClerkProvider publishableKey={config.key!} localization={arSA}><ConvexProviderWithClerk client={client} useAuth={useAuth}><Boundary><OwnerGate>{children}</OwnerGate></Boundary></ConvexProviderWithClerk></ClerkProvider>;
}
function OwnerGate({children}:{children:ReactNode}){const {isLoading,isAuthenticated}=useConvexAuth();const allowed=useQuery(api.access.allowed,isAuthenticated?{}:'skip');
 if(isLoading)return <div className="auth-screen"><h1>جارٍ التحقق من تسجيل الدخول…</h1></div>;
 if(!isAuthenticated)return <div className="auth-screen"><h1>مشهد — استوديوك الخاص</h1><p>سجّل الدخول بحساب المالك للوصول إلى الطلبات والملفات.</p><SignInButton mode="modal"><button className="primary">تسجيل الدخول</button></SignInButton></div>;
 if(allowed===undefined)return <div className="auth-screen">جارٍ التحقق من صلاحية المالك…</div>;
 if(!allowed)return <div className="auth-screen"><h1>هذا الحساب غير مصرح له</h1><p>الوصول مقصور على هوية المالك المسجلة في إعدادات Convex.</p><UserButton/></div>;
 return <CloudReady>{children}</CloudReady>;
}
function uploadBytes(url:string,file:File,progress:(percent:number)=>void):Promise<Id<'_storage'>>{return new Promise((resolve,reject)=>{const xhr=new XMLHttpRequest();xhr.open('POST',url);xhr.setRequestHeader('Content-Type',file.type);xhr.timeout=120000;xhr.upload.onprogress=e=>{if(e.lengthComputable)progress(Math.round(e.loaded/e.total*100));};xhr.onerror=()=>reject(new Error('انقطع الاتصال أثناء الرفع. أعد المحاولة؛ المسودة محفوظة.'));xhr.ontimeout=()=>reject(new Error('انتهت مهلة رفع الملف. أعد المحاولة.'));xhr.onload=()=>{try{if(xhr.status<200||xhr.status>=300)throw new Error('تعذر رفع الملف إلى Convex.');const value=JSON.parse(xhr.responseText) as {storageId?:Id<'_storage'>};if(!value.storageId)throw new Error('لم يُرجع الخادم معرّف الملف.');resolve(value.storageId);}catch(error){reject(error);}};xhr.send(file);});}
function CloudReady({children}:{children:ReactNode}){
 const requests=useQuery(api.requests.list);const save=useMutation(api.requests.save);const authorize=useMutation(api.pipeline.authorize);const begin=useMutation(api.files.begin);const finish=useAction(api.files.finish);const attach=useMutation(api.requests.attachManualVideo);const {getToken,sessionClaims}=useAuth();const convex=useConvex();
 const [selectedId,setSelectedId]=useState<Id<'requests'>|null>(()=>{try{return localStorage.getItem('mashhad-selected-request') as Id<'requests'>|null;}catch{return null;}}),[busy,setBusy]=useState(false),[progress,setProgress]=useState<{name:string;percent:number}|null>(null),[error,setError]=useState(''),[message,setMessage]=useState('');const lock=useRef(false);const [connected,setConnected]=useState(globalThis.navigator.onLine && convex.connectionState().isWebSocketConnected);
 useEffect(()=>{const timer=window.setInterval(()=>setConnected(globalThis.navigator.onLine && convex.connectionState().isWebSocketConnected),1000);return()=>window.clearInterval(timer)},[convex]);
 useEffect(()=>{try{if(selectedId)localStorage.setItem('mashhad-selected-request',selectedId);}catch{/* selection is optional */}},[selectedId]);
 const selected=requests?.find(r=>r._id===selectedId);
 async function upload(file:File,kind:FileKind){validateFile(file.type,file.size,kind);validateSignature(new Uint8Array(await file.slice(0,32).arrayBuffer()),file.type);setProgress({name:file.name,percent:0});const hash=Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',await file.arrayBuffer()))).map(n=>n.toString(16).padStart(2,'0')).join('');const key=`${kind}:${hash}`;const ticket=await begin({key,kind,name:file.name,type:file.type,size:file.size});if(ticket.storageId){setProgress({name:file.name,percent:100});return ticket.storageId;}const id=await uploadBytes(ticket.url!,file,percent=>setProgress({name:file.name,percent}));setProgress({name:`التحقق من ${file.name}`,percent:100});return finish({key,storageId:id});}
 async function operation<T>(task:()=>Promise<T>):Promise<T>{if(lock.current)throw new Error('هناك عملية حفظ أو رفع قيد التنفيذ.');if(!globalThis.navigator.onLine || !convex.connectionState().isWebSocketConnected)throw new Error('الاتصال غير متاح. المسودة محفوظة محليًا؛ أعد إرسالها عند عودة الاتصال.');lock.current=true;setBusy(true);setError('');setMessage('');try{return await task();}catch(error){setError(cloudError(error));throw error;}finally{lock.current=false;setBusy(false);setProgress(null);}}
 async function send(draft:Draft,submit:boolean){return operation(async()=>{const existing=requests?.find(r=>r.key===draft.id);if(existing&&existing.status!=='مسودة'){setSelectedId(existing._id);const message='هذا الطلب أُرسل سابقًا؛ لم يُرسل مرة ثانية. لإنشاء نسخة مختلفة اختر «إعلان جديد».';setMessage(message);return message;}const logoId=draft.logo?await upload(draft.logo,'image'):undefined;const referenceIds:Id<'_storage'>[]=[];for(const file of draft.references)referenceIds.push(await upload(file,'image'));const id=await save({key:draft.id,form:draft.form,clipCount:draft.clipCount??1,logoId,referenceIds,submit,createdAt:Date.parse(draft.createdAt)});setSelectedId(id);const message=submit?'حُفظ الطلب دون تفويض توليد؛ يلزم اختيار خطة وضغط زر توليد الإعلان.':'تم نقل المسودة إلى Convex بنجاح. بقيت النسخة المحلية محفوظة.';setMessage(message);return message;});}
 async function uploadVideo(file:File){if(!selected)throw new Error('اختر طلبًا أولًا.');await operation(async()=>{const id=await upload(file,'video');await attach({requestId:selected._id,storageId:id});setMessage('تم ربط الفيديو المرفوع يدويًا بالطلب. هذا الفيديو ليس ناتج توليد من النظام.');});}
 async function uploadImage(file:File){return operation(()=>upload(file,'image'));}
 async function generate(draft:Draft,option:FlowOption,template:Template){return operation(async()=>{
 const existing=requests?.find(r=>r.key===draft.id);if(existing&&canonical(existing.form)!==canonical(draft.form))throw new Error('هذا الطلب محفوظ بإعدادات مختلفة؛ اختر إعلان جديد للحفاظ على الأصول.');
 const logoId=existing?.logoId??(draft.logo?await upload(draft.logo,'image'):undefined);const referenceIds=existing?.referenceIds??[];if(!existing)for(const file of draft.references)referenceIds.push(await upload(file,'image'));
 const requestId=existing?._id??await save({key:draft.id,form:draft.form,clipCount:draft.clipCount??1,logoId,referenceIds,submit:true,createdAt:Date.parse(draft.createdAt)});
 setSelectedId(requestId);await authorize({requestId,key:`generate-${draft.id}`,option,count:draft.clipCount??1,template});const message='حُفظ تفويض هذا الطلب فقط. سيبدأ Worker المتصل تلقائيًا؛ إذا كان متوقفًا يبقى الطلب بانتظار اتصاله.';setMessage(message);return message;
 });}
 async function getFile(id:Id<'_storage'>,signal?:AbortSignal){const token=await getToken(sessionClaims?.aud==='convex'?{}:{template:'convex'});if(!token)throw new Error('يحتاج تسجيل دخول.');const endpoint=`${config.site}/files?id=${encodeURIComponent(id)}`;const options={headers:{Authorization:`Bearer ${token}`},cache:'no-store' as const,signal};const metadata=await fetch(`${endpoint}&metadata=1`,options);if(!metadata.ok)throw new Error('تعذر تحميل الملف المحمي؛ تحقق من الجلسة.');const info=await metadata.json() as {size:number;type:string};const size=info.size;if(!Number.isSafeInteger(size)||size<=0||size>100*1024*1024)throw new Error('حجم الملف غير صالح.');const parts:Blob[]=[];for(let offset=0;offset<size;offset+=8*1024*1024){const response=await fetch(`${endpoint}&offset=${offset}`,options);if(!response.ok)throw new Error('انقطع تنزيل الملف المحمي.');parts.push(await response.blob());}return new Blob(parts,{type:info.type});}
 return <CloudContext.Provider value={{requests,selected,select:setSelectedId,send,generate,uploadVideo,uploadImage,getFile,busy,progress,error,message,connected}}>{children}</CloudContext.Provider>;
}
export function CloudNotice(){const cloud=useCloud();if(!cloud)return null;return <div className="cloud-notice"><div className="cloud-toolbar"><span className={cloud.connected?'online':'offline'}>{cloud.connected?'متصل بـConvex · Development':'الاتصال منقطع — المسودات المحلية محفوظة'}</span><UserButton/></div>{cloud.progress&&<div role="status"><p>{cloud.progress.name} — {cloud.progress.percent}%</p><progress max={100} value={cloud.progress.percent}/></div>}{cloud.error&&<div role="alert" className="notice error">{cloud.error}</div>}{cloud.message&&<div role="status" className="notice success">{cloud.message}</div>}</div>}
function ProtectedImage({id}:{id:Id<'_storage'>}){const cloud=useCloud()!;const [url,setUrl]=useState(''),[error,setError]=useState('');const getFile=cloud.getFile;const loader=useRef(getFile);useEffect(()=>{loader.current=getFile},[getFile]);useEffect(()=>{const abort=new AbortController();let objectUrl='';setUrl('');setError('');loader.current(id,abort.signal).then(blob=>{if(abort.signal.aborted)return;objectUrl=URL.createObjectURL(blob);setUrl(objectUrl)}).catch(error=>{if(!abort.signal.aborted)setError(cloudError(error))});return()=>{abort.abort();if(objectUrl)URL.revokeObjectURL(objectUrl)}},[id]);return error?<span role="alert">{error}</span>:url?<img src={url} alt="صورة محفوظة في الطلب"/>:<span>جارٍ تحميل الصورة…</span>}
export function CloudPreview(){const cloud=useCloud();if(!cloud)return null;return <PreviewReady key={cloud.selected?._id??"none"} cloud={cloud}/>;}
function PreviewReady({cloud}:{cloud:CloudContextValue}){const selected=cloud.selected;const [resultIndex,setResultIndex]=useState(0);const [url,setUrl]=useState(''),[error,setError]=useState('');const loader=useRef(cloud.getFile);useEffect(()=>{loader.current=cloud.getFile},[cloud.getFile]);const videoId=selected?.results?.[resultIndex]?.storageId??selected?.videoId;useEffect(()=>{const abort=new AbortController();let objectUrl='';setUrl('');setError('');if(videoId)loader.current(videoId,abort.signal).then(blob=>{if(abort.signal.aborted)return;objectUrl=URL.createObjectURL(blob);setUrl(objectUrl)}).catch(error=>{if(!abort.signal.aborted)setError(cloudError(error))});return()=>{abort.abort();if(objectUrl)URL.revokeObjectURL(objectUrl)}},[videoId]);
 return <section id="cloud-preview" className="card cloud-preview"><h2>معاينة الطلب السحابي</h2>{selected?<><p>{selected.form.name} · {selected.status}</p><p>معرّف الطلب: <code dir="ltr">{selected._id}</code></p>{selected.runner&&<p>تشغيل محلي: {({'prepared':'جاهز للمراجعة','intent':'تم تثبيت نية الإرسال','submitted':'أُرسل إلى Flow','unknown':'الإرسال غير محسوم — تحقق يدويًا','downloaded':'الفيديو محلي؛ بانتظار الرفع','uploaded':'الفيديو محفوظ'})[selected.runner.phase]} · المقاطع اللازمة: {selected.runner.requiredClips??selected.clipCount} · مدة المقطع: {selected.runner.clipSeconds??"غير معروفة"} ثانية. مقاطع مصدر محفوظة؛ إعدادات المونتاج أدناه.</p>}<p>المقاطع: {selected.clipCount} · آخر تحديث: {new Date(selected.updatedAt).toLocaleString('ar-IQ')}</p><p>النقاط المتوقعة: {selected.estimatedPoints??'غير متوفرة'} (تقدير فقط)</p><p>النقاط الفعلية: {selected.actualPoints??'غير متوفرة'}</p>{selected.runner?.phase==="unknown"&&<div className="notice error">لا تعد إرسال الطلب؛ تحقّق من Flow ثم استكمل المتابعة عبر worker:resume. إعادة الإرسال قد تصرف نقاطًا مرة ثانية.</div>}{selected.status==="يحتاج تسجيل دخول"&&<p>شغّل worker:login، أكمل تسجيل الدخول أو التحقق بنفسك في Chrome، ثم worker:resume لهذا الطلب.</p>}{selected.externalTaskId&&<p>المهمة الخارجية: {selected.externalTaskId}</p>}{selected.error&&<div className="notice error">{selected.error}</div>}{selected.results&&<div className="references">{selected.results.map((r,i)=><button key={r.assetId} onClick={()=>setResultIndex(i)} aria-pressed={resultIndex===i}>النتيجة {i+1} · {r.duration} ث · {r.width}×{r.height}</button>)}</div>}{url?<><video src={url} controls playsInline preload="metadata" onError={()=>setError('تعذر تشغيل الفيديو؛ تحقق من ترميز MP4. يفضل H.264/AAC.')}/><a className="download" href={url} download={`ad-${selected._id}-${resultIndex+1}.mp4`}>تحميل الفيديو</a><p>{selected.videoSource==='manual'?'فيديو مرفوع يدويًا؛ لم يولّده النظام.':'ملف ناتج برنامج التشغيل الخارجي'}</p></>:<div className="video-placeholder landscape"><p>{videoId?'جارٍ تحميل الفيديو المحمي…':'لا يوجد فيديو لهذا الطلب بعد.'}</p></div>}{error&&<div role="alert" className="notice error">{error}</div>}<label className="upload"><strong>رفع فيديو جاهز إلى هذا الطلب</strong><small>MP4 · حتى 100 MB · اختبار التخزين والعرض</small><input type="file" accept="video/mp4" disabled={cloud.busy||!cloud.connected} onChange={e=>{const file=e.target.files?.[0];e.target.value='';if(file)cloud.uploadVideo(file).catch(error=>setError(cloudError(error)))}}/></label><div className="references">{selected.logoId&&<ProtectedImage id={selected.logoId}/>} {selected.referenceIds.map((id,i)=><ProtectedImage key={`${id}-${i}`} id={id}/>)}</div></>:<p>اختر «عرض» من الطلبات لرفع فيديو يدوي ومعاينته وتنزيله.</p>}</section>;
}
export function CloudRequests(){const cloud=useCloud();if(!cloud)return null;return <section id="cloud-requests" className="card requests"><div className="section-title"><div><h2>طلبات Convex <span className="count">{cloud.requests?.length??'…'}</span></h2><p>تحديث مباشر · Worker محلي · Development</p></div></div>{cloud.requests===undefined?<p>جارٍ تحميل الطلبات…</p>:cloud.requests.length===0?<p>لا توجد طلبات سحابية بعد. أرسل نموذج الإعلان أو انقل مسودة محلية.</p>:<div className="table-wrap"><table><thead><tr><th>الاسم</th><th>تاريخ الإنشاء</th><th>الموديل</th><th>الحالة</th><th>المعاينة</th></tr></thead><tbody>{cloud.requests.map(r=><tr key={r._id}><td>{r.form.name}</td><td>{new Date(r.createdAt).toLocaleString('ar-IQ')}</td><td dir="ltr">{r.form.model}</td><td><span className="status">{r.status}</span></td><td><button className="text-button" onClick={()=>{cloud.select(r._id);document.getElementById("cloud-preview")?.scrollIntoView({behavior:"smooth",block:"start"})}} disabled={cloud.busy}>عرض</button></td></tr>)}</tbody></table></div>}</section>;}


