import {ConvexError} from 'convex/values';
import {AiWallet} from './ai-wallet';
import {useAuth} from '@clerk/react';
import {useEffect,useRef,useState,type FormEvent} from 'react';
import {useMutation,useQuery} from 'convex/react';
import {Clapperboard,MessageCircle,Users,Layers,Play,Send,Sparkles,CheckCircle2,Pencil,Check,X} from 'lucide-react';
import {api} from '../convex/_generated/api';
import type {FlowOption} from '../shared/pipeline';
import {filmOptions} from '../shared/film-experience';
import type {Id} from '../convex/_generated/dataModel';
import {cloudError,useCloud} from './cloud';
import './film-studio.css';
import {FilmWorkshop} from './film-workshop';
import {FilmProduction} from './film-production';

const sections=[{id:'discussion',name:'المناقشة',icon:MessageCircle},{id:'characters',name:'الشخصيات',icon:Users},{id:'episodes',name:'الحلقات',icon:Layers},{id:'results',name:'النتائج',icon:Play}] as const;
type Section=typeof sections[number]['id'];

export function FilmStudio({initialSection='discussion',newRequest=0}:{initialSection?:Section;newRequest?:number}={}){
 const projects=useQuery(api.films.list),create=useMutation(api.films.create),rename=useMutation(api.films.rename),cloud=useCloud();
 const [selected,setSelected]=useState<Id<'filmProjects'>|null>(null),[fresh,setFresh]=useState(false),[title,setTitle]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[section,setSection]=useState<Section>(initialSection);
 const {userId}=useAuth(),localPreview=['localhost','127.0.0.1','[::1]'].includes(location.hostname),storageKey='mashhad-local-film-names:'+userId;
 const [localNames,setLocalNames]=useState<{subject:string|null|undefined;names:Record<string,string>}>(()=>{let names:Record<string,string>={};if(localPreview)try{const data=JSON.parse(localStorage.getItem(storageKey)??'{}');if(data&&typeof data==='object'&&!Array.isArray(data))names=Object.fromEntries(Object.entries(data).filter(([key,value])=>key.length<100&&typeof value==='string'&&value.length<=120)) as Record<string,string>;}catch{/* Optional local preview storage. */}return {subject:userId,names};});
 const [editingName,setEditingName]=useState<{id:Id<'filmProjects'>;original:string;value:string}|null>(null),[renameNotice,setRenameNotice]=useState('');
 const id=selected??(!fresh?projects?.[0]?._id:null),lock=useRef(false),createKey=useRef(crypto.randomUUID());
 const project=projects?.find(p=>p._id===id);
 const names=localPreview&&localNames.subject===userId?localNames.names:{},sessionName=names[id??'']??project?.title??'';
 useEffect(()=>{if(!newRequest)return;setSelected(null);setFresh(true);setSection('discussion');setError('');setEditingName(null);setRenameNotice('')},[newRequest]);
 async function saveName(e:FormEvent){e.preventDefault();if(lock.current||!editingName)return;const edit=editingName,next=edit.value.trim();if(!next||next.length>120){setError('أدخل اسمًا حتى 120 حرفًا.');return;}lock.current=true;setBusy(true);setError('');try{
 if(project?.canRename){await rename({projectId:edit.id,title:next,expectedTitle:edit.original});const updated={...names};delete updated[edit.id];setLocalNames({subject:userId,names:updated});if(localPreview)try{localStorage.setItem(storageKey,JSON.stringify(updated))}catch{/* Preview name remains reactive. */}setRenameNotice('تم تغيير اسم الجلسة في كل تبويبات الفيلم.');}
 else if(localPreview){const updated={...names,[edit.id]:next};setLocalNames({subject:userId,names:updated});try{localStorage.setItem(storageKey,JSON.stringify(updated))}catch{/* Name remains in this preview session. */}setRenameNotice('تم حفظ الاسم في المعاينة المحلية لكل تبويبات الفيلم؛ حفظه بالخدمة يتفعّل عند نشر التحديث.');}
 else throw new Error('تعديل الاسم يحتاج تحديث الخدمة.');
 setSelected(edit.id);setEditingName(null);
 }catch(e){setError(cloudError(e))}finally{lock.current=false;setBusy(false)}}
 async function newFilm(e:FormEvent){e.preventDefault();if(lock.current)return;lock.current=true;setBusy(true);setError('');try{setSelected(await create({key:createKey.current,title}));setFresh(false);setTitle('');createKey.current=crypto.randomUUID();setSection('discussion');}catch(e){setError(cloudError(e))}finally{lock.current=false;setBusy(false)}}
 return <section className="film-studio"><nav className="film-toolbar" aria-label="أدوات استوديو الأفلام">{sections.map(s=><button key={s.id} aria-pressed={section===s.id} onClick={()=>setSection(s.id)}><s.icon size={18}/><span>{s.name}</span></button>)}</nav><div className="film-project-select"><label htmlFor="film-project">الفيلم الحالي</label><select id="film-project" disabled={busy} value={id??''} onChange={e=>{setSelected(e.target.value as Id<'filmProjects'>||null);setFresh(!e.target.value);setEditingName(null);setRenameNotice('');setError('')}}><option value="">اختر فيلمًا أو ابدأ فكرة جديدة</option>{projects?.map(p=><option value={p._id} key={p._id}>{names[p._id]??p.title}</option>)}</select>{project&&<button className="film-rename" disabled={busy} onClick={()=>{setEditingName({id:project._id,original:project.title,value:sessionName});setError('');setRenameNotice('')}}><Pencil size={16}/> تعديل اسم الجلسة</button>}</div>{editingName&&<form className="film-rename-form studio-panel" onSubmit={saveName}><label htmlFor="film-session-name">اسم الجلسة<input id="film-session-name" autoFocus required maxLength={120} disabled={busy} value={editingName.value} onChange={e=>setEditingName({...editingName,value:e.target.value})}/></label><div className="film-actions"><button className="studio-generate" disabled={busy||!editingName.value.trim()}><Check size={16}/>{busy?'جارٍ الحفظ…':!project?.canRename&&localPreview?'حفظ بالمعاينة المحلية':'حفظ الاسم'}</button><button type="button" disabled={busy} onClick={()=>{setEditingName(null);setError('')}}><X size={16}/> إلغاء</button></div></form>}{renameNotice&&<p className="film-rename-notice" role="status">{renameNotice}</p>}{id&&<h2 className="film-session-heading">{sessionName}</h2>}{error&&<div role="alert" className="studio-error">{error}</div>}{projects===undefined?<div className="studio-panel" role="status">جارٍ تحميل أفلامك المحفوظة…</div>:!id?<form className="film-start studio-panel" onSubmit={newFilm}><div className="film-orb"><Sparkles size={34}/></div><h2>أي حكاية تريد أن تصنع؟</h2><p>ابدأ باسم مؤقت؛ مساعدك يناقش معك القصة والأسلوب والشخصيات والمدة والميزانية.</p><label>اسم الفيلم<input required value={title} onChange={e=>setTitle(e.target.value)} maxLength={120} placeholder="مثل: آخر فرصة، أو مغامرة كارتونية"/></label><button className="studio-generate" disabled={busy||!cloud?.connected}>{busy?'جارٍ حفظ الفيلم…':'ابدأ المناقشة'}<MessageCircle size={18}/></button><small>إنشاء النقاش لا يبدأ إنتاج فيديو ولا يخصم نقاط إنتاج.</small></form>:section==='discussion'?<FilmDiscussion key={id} id={id} sessionName={sessionName} onEpisode={()=>setSection('episodes')}/>:section==='characters'||section==='episodes'?<FilmWorkshop id={id} section={section} sessionName={sessionName}/>:<FilmProduction key={id} id={id} sessionName={sessionName}/>}</section>;
}
function FilmDiscussion({id,onEpisode,sessionName}:{id:Id<'filmProjects'>;onEpisode:()=>void;sessionName:string}){
 const wallet=useQuery(api.wallets.aiMine);
 const state=useQuery(api.films.state,{projectId:id}),send=useMutation(api.films.send),checkPending=useMutation(api.films.checkPending),cloud=useCloud();
 const [text,setText]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),pending=useRef<{key:string;text:string}|null>(null),lock=useRef(false),last=useRef<HTMLDivElement>(null);
 const working=state?.turns.some(t=>t.status==='queued'||t.status==='running');
 useEffect(()=>{if(!working)return;const check=()=>{void checkPending({projectId:id}).catch(()=>{})};check();const timer=setInterval(check,30_000);return()=>clearInterval(timer)},[id,working,checkPending]);
 useEffect(()=>{last.current?.scrollIntoView({block:'nearest',behavior:'smooth'})},[state?.turns.length,working]);
 async function submit(e:FormEvent){e.preventDefault();if(lock.current||working||!text.trim())return;lock.current=true;setBusy(true);setError('');if(!pending.current)pending.current={key:crypto.randomUUID(),text:text.trim()};try{await send({projectId:id,...pending.current});pending.current=null;setText('')}catch(e){if(e instanceof ConvexError)pending.current=null;setError(cloudError(e))}finally{lock.current=false;setBusy(false)}}
 if(!state)return <div className="studio-panel">جارٍ تحميل النقاش…</div>;
 return <><FilmDiscussionSettings id={id}/><div className="film-discussion"><div className="film-conversation studio-panel"><div className="film-chat-title"><div><MessageCircle size={20}/><strong>{sessionName}</strong></div><span><CheckCircle2 size={13}/> محفوظ</span></div><div className="film-messages" role="log" aria-label="مناقشة الفيلم" aria-live="polite">{state.turns.length===0&&<div className="film-welcome"><Sparkles size={30}/><h2>خلّينا نبدأ بفكرتك</h2><p>شنو القصة اللي تتخيلها؟ واقعية لو كارتونية؟ وإذا ما عندك فكرة، اطلب مني نقترح واحدة سوه.</p><div>{['أريد فكرة فيلم كارتوني','عندي قصة عراقية أريد نناقشها','ساعدني أحدد المدة والميزانية'].map(t=><button key={t} onClick={()=>setText(t)}>{t}</button>)}</div></div>}{state.turns.map(t=><div className="film-turn" key={t._id}><article className="film-bubble user"><small>أنت</small><p>{t.userText}</p></article>{t.reply&&<article className="film-bubble assistant"><small><Sparkles size={13}/> مساعد القصة</small><p>{t.reply}</p></article>}{(t.status==='queued'||t.status==='running')&&<div className="film-thinking" role="status"><span/><span/><span/> مساعدك يراجع النقاش…</div>}{t.error&&<div className="film-turn-error" role="alert">{t.error}{t.status==='unknown'&&<small>النتيجة والكلفة غير محسومتين؛ لا توجد إعادة محاولة تلقائية.</small>}</div>}</div>)}<div ref={last}/></div><form className="film-composer" onSubmit={submit}><label htmlFor="film-message" className="film-sr">رسالتك لمساعد الفيلم</label><textarea id="film-message" rows={3} maxLength={4000} value={text} disabled={busy||working||!!pending.current} onChange={e=>setText(e.target.value)} placeholder="احچي عن الفكرة، الشخصيات، أو الأحداث…"/><button type="submit" aria-label={pending.current?'تحقق من إرسال الرسالة':'إرسال رسالة الفيلم'} disabled={busy||working||!cloud?.connected||!state.configured||!text.trim()||(!pending.current&&(!wallet||wallet.availableMicros<=0))}><Send size={20}/></button></form>{error&&<div className="film-turn-error" role="alert">{error}{pending.current&&<small>زر الإرسال يتحقق من الإرسال نفسه؛ لا ينشئ رسالة ثانية.</small>}</div>}{!state.configured&&<p className="studio-error">مساعد المناقشة غير متاح حاليًا.</p>}<p className="film-chat-note">المناقشة لا تبدأ الإنتاج. سنعرض كلفة الحلقة ونطلب موافقتك قبل إنتاجها.</p></div><aside className="film-summary studio-panel"><h2>حلقتك القادمة</h2><p>بعد الاتفاق على القصة، راجع الحلقة وشخصياتها وكلفتها قبل الإنتاج.</p><button className="studio-generate" disabled={working||!state.project.brief} onClick={onEpisode}>اعتماد الحلقة <CheckCircle2 size={18}/></button><AiWallet/><div className="film-clean"><FilmClean/> <span>فيلم دون كتابة أو شعار فوق الصورة.</span></div></aside></div></>;
}
function FilmClean(){return <Clapperboard size={18}/>}

function FilmDiscussionSettings({id}:{id:Id<'filmProjects'>}){
 const state=useQuery(api.filmWorkshop.state,{projectId:id}),available=useQuery(api.filmProduction.options,{projectId:id}),save=useMutation(api.filmWorkshop.productionSettings);
 const [choice,setChoice]=useState<FlowOption|null>(null),[busy,setBusy]=useState(false),[notice,setNotice]=useState(''),[error,setError]=useState(''),lock=useRef(false);
 const options=filmOptions(available?.options??[]),current=choice??state?.project.productionOption??options[0];
 const models=[...new Set(options.map(o=>o.model))];
 async function submit(e:FormEvent){e.preventDefault();if(lock.current||!current)return;lock.current=true;setBusy(true);setNotice('');setError('');try{await save({projectId:id,option:current});setChoice(null);setNotice('تم الحفظ؛ تخطيط الحلقة وإنتاجها يعتمدان هذا الاختيار.')}catch(e){setError(cloudError(e))}finally{lock.current=false;setBusy(false)}}
 return <details className="film-discussion-settings studio-panel"><summary>إعدادات الفيلم {current&&<span>{current.actualModel} · {current.aspect==='9:16'?'عمودي':'أفقي'}</span>}</summary><form onSubmit={submit}><div className="film-settings-grid"><label>الموديل<select value={current?.model??''} disabled={busy||!options.length} onChange={e=>{setChoice(options.find(o=>o.model===e.target.value&&o.aspect===current?.aspect)??options.find(o=>o.model===e.target.value)??null);setNotice('')}}>{models.map(m=><option key={m} value={m}>{options.find(o=>o.model===m)?.actualModel}</option>)}</select></label><label>المقاس<select value={current?.aspect??'9:16'} disabled={busy||!options.length} onChange={e=>{setChoice(options.find(o=>o.model===current?.model&&o.aspect===e.target.value&&o.resolution===current?.resolution)??options.find(o=>o.model===current?.model&&o.aspect===e.target.value)??null);setNotice('')}}><option value="9:16">عمودي 9:16</option><option value="16:9">أفقي 16:9</option></select></label><label>الجودة<select value={current?.resolution??'360p'} disabled={busy||!options.length} onChange={e=>{setChoice(options.find(o=>o.model===current?.model&&o.aspect===current?.aspect&&o.resolution===e.target.value)??null);setNotice('')}}>{options.filter(o=>o.model===current?.model&&o.aspect===current?.aspect).map(o=><option key={o.resolution} value={o.resolution}>{o.resolution}</option>)}</select></label></div><button className="film-rename" disabled={busy||!current}><Check size={16}/>{busy?'جارٍ الحفظ…':'حفظ'}</button>{notice&&<p role="status">{notice}</p>}{error&&<p className="studio-error" role="alert">{error}</p>}{!options.length&&<p>خيارات التوليد غير متاحة حاليًا.</p>}</form></details>;
}
