import {useEffect,useRef,useState,type FormEvent} from 'react';
import {useAction,useMutation,useQuery} from 'convex/react';
import {useAuth} from '@clerk/react';
import {api} from '../convex/_generated/api';
import type {Doc,Id} from '../convex/_generated/dataModel';
import type {FlowOption} from '../shared/pipeline';
import {filmOptions,episodeDuration} from '../shared/film-experience';
import {FilmProduction} from './film-production';
import {validateFile} from '../shared/validation';
import {downloadProtectedMedia} from './protected-media';
import {cloudError} from './cloud';
export function FilmWorkshop({id,section,sessionName}:{id:Id<'filmProjects'>;sessionName?:string;section:'characters'|'images'|'episodes'}){
 const state=useQuery(api.filmWorkshop.state,{projectId:id});
 if(!state)return <div className="studio-panel">جارٍ تحميل أدوات الفيلم…</div>;
 return <div className="film-workshop studio-panel">{section==='episodes'?<Episodes key={id} id={id} state={state} sessionName={sessionName}/>:<References key={`${id}:${section}`} id={id} refs={state.references} kind={section==='characters'?'character':'place'}/>}</div>;
}
type Workshop=NonNullable<ReturnType<typeof useQuery<typeof api.filmWorkshop.state>>>;
function References({id,refs,kind}:{id:Id<'filmProjects'>;refs:Doc<'filmReferences'>[];kind:'character'|'place'}){
 const save=useMutation(api.filmWorkshop.reference),begin=useMutation(api.filmWorkshop.begin),finish=useAction(api.filmWorkshop.finish);
 const [editing,setEditing]=useState<Doc<'filmReferences'>|null>(null),[name,setName]=useState(''),[description,setDescription]=useState(''),[file,setFile]=useState<File|null>(null),[preview,setPreview]=useState(''),[remove,setRemove]=useState(false),[busy,setBusy]=useState(false),[progress,setProgress]=useState<number|null>(null),[error,setError]=useState(''),[notice,setNotice]=useState('');
 const lock=useRef(false),key=useRef(crypto.randomUUID()),uploaded=useRef<{file:File;id:Id<'_storage'>}|null>(null);
 useEffect(()=>{if(!file){setPreview('');return;}const url=URL.createObjectURL(file);setPreview(url);return()=>URL.revokeObjectURL(url)},[file]);
 function reset(){setEditing(null);setName('');setDescription('');setFile(null);setRemove(false);key.current=crypto.randomUUID();uploaded.current=null;}
 async function submit(e:FormEvent){e.preventDefault();if(lock.current)return;lock.current=true;setBusy(true);setError('');setNotice('');try{
  let fileId=remove?undefined:editing?.fileId;
  if(file){validateFile(file.type,file.size,'image');const decoded=await createImageBitmap(file);decoded.close();if(uploaded.current?.file===file)fileId=uploaded.current.id;else{const hash=Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',await file.arrayBuffer()))).map(n=>n.toString(16).padStart(2,'0')).join('');const ticket=await begin({projectId:id,key:hash,type:file.type,size:file.size});fileId=ticket.fileId;if(!fileId){setProgress(0);fileId=await new Promise<Id<'_storage'>>((resolve,reject)=>{const x=new XMLHttpRequest();x.open('POST',ticket.url!);x.setRequestHeader('Content-Type',file.type);x.timeout=120000;x.upload.onprogress=e=>{if(e.lengthComputable)setProgress(Math.round(e.loaded/e.total*100))};x.onerror=x.ontimeout=()=>reject(new Error('انقطع الرفع؛ أعد حفظ المرجع.'));x.onload=()=>{try{if(x.status<200||x.status>=300)throw new Error('فشل الرفع');resolve(JSON.parse(x.responseText).storageId)}catch(e){reject(e)}};x.send(file)});await finish({projectId:id,key:hash,fileId});}uploaded.current={file,id:fileId};}}
  await save({projectId:id,key:editing?.key.slice(`${id}:`.length)??key.current,kind,name,description,...(fileId?{fileId}:{})});reset();setNotice('حُفظ المرجع لهذا الفيلم. راجع اعتماد الحلقات عند تغييره.');
 }catch(e){setError(cloudError(e))}finally{lock.current=false;setBusy(false);setProgress(null)}}
 return <><h2>{kind==='character'?'الشخصيات وهوية كل شخصية':'الأماكن ومراجع المشاهد'}</h2><p>{kind==='character'?'احفظ الاسم والملامح والملابس والصوت. الصورة مرجع للشخصية، والخلفية البيضاء مقبولة.':'احفظ المكان والإضاءة وزوايا التصوير. اربطه بالمشهد ليبقى مكان القصة واضحًا.'} لا تُضاف هذه الصور أو الأسماء كشعار أو كتابة فوق الفيلم.</p><div className="film-ref-grid">{refs.filter(r=>r.kind===kind).map(r=><article className="film-ref-card" key={r._id}>{r.fileId&&<FilmReferenceImage projectId={id} fileId={r.fileId}/>}<h3>{r.name}</h3><p>{r.description}</p><button onClick={()=>{setEditing(r);setName(r.name);setDescription(r.description);setFile(null);setRemove(false);setNotice('');setError('')}} disabled={busy}>تعديل المرجع</button></article>)}</div><form className="film-ref-form" onSubmit={submit}><h3>{editing?'تعديل':'إضافة'} {kind==='character'?'شخصية':'مكان'}</h3><label>الاسم<input required maxLength={100} value={name} onChange={e=>setName(e.target.value)} disabled={busy}/></label><label>{kind==='character'?'الملامح والملابس والصوت وما يجب الحفاظ عليه':'وصف المكان والإضاءة وما يمثله المرجع'}<textarea maxLength={1800} rows={4} value={description} onChange={e=>setDescription(e.target.value)} disabled={busy}/></label><label>صورة مرجعية — PNG / JPG / WebP، حتى 10 MB<input type="file" accept="image/png,image/jpeg,image/webp" disabled={busy} key={editing?._id??key.current} onChange={e=>{setFile(e.target.files?.[0]??null);setRemove(false);uploaded.current=null}}/></label>{preview?<img className="film-ref-preview" src={preview} alt="معاينة الصورة قبل الحفظ"/>:editing?.fileId&&!remove&&<FilmReferenceImage projectId={id} fileId={editing.fileId}/>}<button type="button" disabled={busy} onClick={()=>{setFile(null);setRemove(true)}}>حفظ دون صورة</button>{progress!==null&&<div role="status"><progress max={100} value={progress}/> رفع الصورة {progress}%</div>}{error&&<p className="studio-error" role="alert">{error}</p>}{notice&&<p role="status">{notice}</p>}<div className="film-actions"><button className="studio-generate" disabled={busy}>{busy?'جارٍ الحفظ والتحقق…':'حفظ المرجع'}</button>{editing&&<button type="button" onClick={reset} disabled={busy}>إلغاء التعديل</button>}</div></form></>;
}
function FilmReferenceImage({projectId,fileId}:{projectId:Id<'filmProjects'>;fileId:Id<'_storage'>}){
 const {getToken,sessionClaims,userId}=useAuth(),[url,setUrl]=useState(''),[error,setError]=useState('');
 useEffect(()=>{const controller=new AbortController();let local='';setError('');void downloadProtectedMedia(`${import.meta.env.VITE_CONVEX_SITE_URL}/film-files?projectId=${projectId}&id=${fileId}`,()=>getToken(sessionClaims?.aud==='convex'?{}:{template:'convex'}),controller.signal,()=>{},45000,userId??undefined).then(blob=>{if(!controller.signal.aborted){local=URL.createObjectURL(blob);setUrl(local)}}).catch(()=>{if(!controller.signal.aborted)setError('تعذر تحميل المرجع المحمي.');});return()=>{controller.abort();URL.revokeObjectURL(local)}},[projectId,fileId,getToken,sessionClaims?.aud,userId]);
 return error?<p role="alert">{error}</p>:url?<img className="film-ref-preview" src={url} alt="صورة مرجعية للفيلم"/>:<p>جارٍ تحميل الصورة…</p>;
}
function Episodes({id,state,sessionName}:{id:Id<'filmProjects'>;state:Workshop;sessionName?:string}){
 const settings=useMutation(api.filmWorkshop.settings),draft=useMutation(api.filmWorkshop.draft),save=useMutation(api.filmWorkshop.save),check=useMutation(api.films.checkPending);
 const conversation=useQuery(api.films.state,{projectId:id}),available=useQuery(api.filmProduction.options,{projectId:id});
 const [config,setConfig]=useState({...state.settings,seconds:state.project.settings?.requestedSeconds??state.settings.seconds}),[episode,setEpisode]=useState(1),[choice,setChoice]=useState<FlowOption|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const lock=useRef(false),pending=useRef<{key:string;episode:number;clipSeconds:number}|null>(null);
 const choices=filmOptions(available?.options??[]),option=state.project.productionOption??choice??choices.find(o=>o.model==='Omni Flash'&&o.resolution==='360p')??choices[0];
 const working=conversation?.turns.some(t=>['queued','running'].includes(t.status));
 useEffect(()=>{if(!working)return;const timer=setInterval(()=>{void check({projectId:id}).catch(()=>{})},30000);return()=>clearInterval(timer)},[working,id,check]);
 const latest=state.episodes.filter(e=>e.episode===episode).sort((a,b)=>b.version-a.version)[0];
 async function run(task:()=>Promise<unknown>){if(lock.current)return;lock.current=true;setBusy(true);setError('');try{await task()}catch(e){setError(cloudError(e))}finally{lock.current=false;setBusy(false)}}
 const duration=option?Math.ceil(config.seconds/option.seconds)*option.seconds:config.seconds;
 return <><h2>الحلقة {episode}</h2>
 {state.settings.episodes>1&&<div className="film-actions">{Array.from({length:state.settings.episodes},(_,i)=><button key={i} aria-pressed={episode===i+1} disabled={busy||working} onClick={()=>{setEpisode(i+1);setError('')}}>الحلقة {i+1}</button>)}</div>}
 {!latest||latest.stale?<><div className="film-settings-grid"><label>مدة الحلقة المطلوبة بالثواني<input type="text" inputMode="numeric" pattern="[0-9]+" lang="en" dir="ltr" value={config.seconds} disabled={busy||working} onChange={e=>setConfig({...config,seconds:Number(e.target.value)})}/></label>{!state.project.productionOption&&<label>الموديل والجودة<select value={option?JSON.stringify(option):''} disabled={busy||working||!!pending.current} onChange={e=>setChoice(JSON.parse(e.target.value))}>{choices.map((o,i)=><option key={i} value={JSON.stringify(o)}>{o.actualModel} · {o.resolution} · {o.aspect==='9:16'?'عمودي':'أفقي'}</option>)}</select></label>}</div>
 <p>مدة الحلقة: <strong dir="ltr">{duration}</strong> ثانية. تكلفة الإنتاج تظهر قبل الموافقة.</p>
 {!state.references.some(r=>r.kind==='character')&&<p className="studio-error">أضف أسماء شخصيات هذه القصة وصورها من «الشخصيات» أولًا.</p>}
 <button className="studio-generate" disabled={!available?.storyPlanningReady||busy||working||!option||!state.project.brief||!state.references.some(r=>r.kind==='character')} onClick={()=>void run(async()=>{if(!pending.current){const seconds=episodeDuration(config.seconds,option.seconds);await settings({projectId:id,settings:{...config,requestedSeconds:config.seconds,seconds}});pending.current={key:crypto.randomUUID(),episode,clipSeconds:option.seconds};}await draft({projectId:id,...pending.current});pending.current=null;})}>{working?'مساعد القصة يجهّز الحلقة…':pending.current?'تحقق من طلب التخطيط':'موافق، جهّز الحلقة'}</button></>:<><article className="film-episode film-scene"><h3>{latest.plan.title}</h3><p className="film-brief">{latest.plan.synopsis}</p><p>مدة الحلقة: <strong dir="ltr">{latest.plan.scenes.reduce((n,s)=>n+s.seconds,0)}</strong> ثانية · {latest.approved?'معتمدة':'بانتظار موافقتك'}</p>{!latest.approved&&<button className="studio-generate" disabled={busy||working} onClick={()=>void run(()=>save({projectId:id,episodeId:latest._id,plan:latest.plan,approve:true}))}>هل توافق على الحلقة؟ موافق، اعرض الكلفة</button>}<details className="film-episode-extra"><summary>إعادة مراجعة الحلقة</summary><p>المراجعة الجديدة تستهلك من رصيد المناقشة.</p><button disabled={!available?.storyPlanningReady||busy||working} onClick={()=>void run(async()=>{if(!option)return;const seconds=episodeDuration(config.seconds,option.seconds);await settings({projectId:id,settings:{...config,seconds}});await draft({projectId:id,episode,key:crypto.randomUUID(),clipSeconds:option.seconds});})}>مراجعة التخطيط حسب آخر اتفاق</button></details></article>{latest.approved&&<details className="film-episode-extra"><summary>كلفة الحلقة والتوليد</summary><FilmProduction id={id} sessionName={sessionName} preferredOption={option} preferredEpisode={latest._id}/></details>}</>}
 {!available?.storyPlanningReady&&<p role="status">معاينة محلية: يبدأ مسار التخطيط الجديد بعد تفعيل تحديث الخدمة.</p>}{error&&<p className="studio-error" role="alert">{error}</p>}{conversation?.turns.filter(t=>t.episode===episode).slice(-1).filter(t=>t.error).map(t=><p role="alert" className="studio-error" key={t._id}>{t.error}</p>)}</>;
}
