import {ConvexError} from 'convex/values';
import {AiWallet} from './ai-wallet';
import {useEffect,useRef,useState,type FormEvent} from 'react';
import {useMutation,useQuery} from 'convex/react';
import {Clapperboard,MessageCircle,Users,Images,Layers,Play,Plus,Send,Sparkles,CheckCircle2} from 'lucide-react';
import {api} from '../convex/_generated/api';
import type {Id} from '../convex/_generated/dataModel';
import {cloudError,useCloud} from './cloud';
import './film-studio.css';
import {FilmWorkshop} from './film-workshop';
import {FilmProduction} from './film-production';

const sections=[{id:'discussion',name:'المناقشة',icon:MessageCircle},{id:'characters',name:'الشخصيات',icon:Users},{id:'images',name:'المراجع',icon:Images},{id:'episodes',name:'الحلقات',icon:Layers},{id:'results',name:'النتائج',icon:Play}] as const;
type Section=typeof sections[number]['id'];

export function FilmStudio({initialSection='discussion'}:{initialSection?:Section}={}){
 const projects=useQuery(api.films.list),create=useMutation(api.films.create),cloud=useCloud();
 const [selected,setSelected]=useState<Id<'filmProjects'>|null>(null),[fresh,setFresh]=useState(false),[title,setTitle]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[section,setSection]=useState<Section>(initialSection);
 const id=selected??(!fresh?projects?.[0]?._id:null),lock=useRef(false),createKey=useRef(crypto.randomUUID());
 async function newFilm(e:FormEvent){e.preventDefault();if(lock.current)return;lock.current=true;setBusy(true);setError('');try{setSelected(await create({key:createKey.current,title}));setFresh(false);setTitle('');createKey.current=crypto.randomUUID();setSection('discussion');}catch(e){setError(cloudError(e))}finally{lock.current=false;setBusy(false)}}
 return <section className="film-studio"><div className="film-heading"><div><span className="studio-kicker"><Clapperboard size={16}/> عالم قصتك</span><h1>استوديو الأفلام <span dir="ltr">AI</span></h1><p>ناقش فكرتك. ابنِ عالمها. وخطّط حكاية تستحق المشاهدة.</p></div><button className="film-new" onClick={()=>{setSelected(null);setFresh(true);setSection('discussion');setError('')}}><Plus size={16}/>فيلم جديد</button></div><nav className="film-toolbar" aria-label="أدوات استوديو الأفلام">{sections.map(s=><button key={s.id} aria-pressed={section===s.id} onClick={()=>setSection(s.id)}><s.icon size={18}/><span>{s.name}</span></button>)}</nav><div className="film-project-select"><label htmlFor="film-project">نقاشاتك المحفوظة</label><select id="film-project" value={id??''} onChange={e=>{setSelected(e.target.value as Id<'filmProjects'>||null);setFresh(!e.target.value);setSection('discussion')}}><option value="">اختر فيلمًا أو ابدأ فكرة جديدة</option>{projects?.map(p=><option value={p._id} key={p._id}>{p.title}</option>)}</select></div>{error&&<div role="alert" className="studio-error">{error}</div>}{projects===undefined?<div className="studio-panel" role="status">جارٍ تحميل أفلامك المحفوظة…</div>:!id?<form className="film-start studio-panel" onSubmit={newFilm}><div className="film-orb"><Sparkles size={34}/></div><h2>أي حكاية تريد أن تصنع؟</h2><p>ابدأ باسم مؤقت؛ مساعدك يناقش معك القصة والأسلوب والشخصيات والمدة والميزانية.</p><label>اسم الفيلم<input required value={title} onChange={e=>setTitle(e.target.value)} maxLength={120} placeholder="مثل: آخر فرصة، أو مغامرة كارتونية"/></label><button className="studio-generate" disabled={busy||!cloud?.connected}>{busy?'جارٍ حفظ الفيلم…':'ابدأ المناقشة'}<MessageCircle size={18}/></button><small>إنشاء النقاش لا يبدأ إنتاج فيديو ولا يخصم نقاط إنتاج.</small></form>:section==='discussion'?<FilmDiscussion key={id} id={id}/>:section==='characters'||section==='images'||section==='episodes'?<FilmWorkshop id={id} section={section}/>:<FilmProduction key={id} id={id}/>}</section>;
}
function FilmDiscussion({id}:{id:Id<'filmProjects'>}){
 const wallet=useQuery(api.wallets.aiMine);
 const state=useQuery(api.films.state,{projectId:id}),send=useMutation(api.films.send),checkPending=useMutation(api.films.checkPending),cloud=useCloud();
 const [text,setText]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),pending=useRef<{key:string;text:string}|null>(null),lock=useRef(false),last=useRef<HTMLDivElement>(null);
 const working=state?.turns.some(t=>t.status==='queued'||t.status==='running');
 useEffect(()=>{if(!working)return;const check=()=>{void checkPending({projectId:id}).catch(()=>{})};check();const timer=setInterval(check,30_000);return()=>clearInterval(timer)},[id,working,checkPending]);
 useEffect(()=>{last.current?.scrollIntoView({block:'nearest',behavior:'smooth'})},[state?.turns.length,working]);
 async function submit(e:FormEvent){e.preventDefault();if(lock.current||working||!text.trim())return;lock.current=true;setBusy(true);setError('');if(!pending.current)pending.current={key:crypto.randomUUID(),text:text.trim()};try{await send({projectId:id,...pending.current});pending.current=null;setText('')}catch(e){if(e instanceof ConvexError)pending.current=null;setError(cloudError(e))}finally{lock.current=false;setBusy(false)}}
 if(!state)return <div className="studio-panel">جارٍ تحميل النقاش…</div>;
 return <div className="film-discussion"><div className="film-conversation studio-panel"><div className="film-chat-title"><div><MessageCircle size={20}/><strong>{state.project.title}</strong></div><span><CheckCircle2 size={13}/> محفوظ</span></div><div className="film-messages" role="log" aria-label="مناقشة الفيلم" aria-live="polite">{state.turns.length===0&&<div className="film-welcome"><Sparkles size={30}/><h2>خلّينا نبدأ بفكرتك</h2><p>شنو القصة اللي تتخيلها؟ واقعية لو كارتونية؟ وإذا ما عندك فكرة، اطلب مني نقترح واحدة سوه.</p><div>{['أريد فكرة فيلم كارتوني','عندي قصة عراقية أريد نناقشها','ساعدني أحدد المدة والميزانية'].map(t=><button key={t} onClick={()=>setText(t)}>{t}</button>)}</div></div>}{state.turns.map(t=><div className="film-turn" key={t._id}><article className="film-bubble user"><small>أنت</small><p>{t.userText}</p></article>{t.reply&&<article className="film-bubble assistant"><small><Sparkles size={13}/> مساعد القصة</small><p>{t.reply}</p></article>}{(t.status==='queued'||t.status==='running')&&<div className="film-thinking" role="status"><span/><span/><span/> مساعدك يراجع النقاش…</div>}{t.error&&<div className="film-turn-error" role="alert">{t.error}{t.status==='unknown'&&<small>النتيجة والكلفة غير محسومتين؛ لا توجد إعادة محاولة تلقائية.</small>}</div>}</div>)}<div ref={last}/></div><form className="film-composer" onSubmit={submit}><label htmlFor="film-message" className="film-sr">رسالتك لمساعد الفيلم</label><textarea id="film-message" rows={3} maxLength={4000} value={text} disabled={busy||working||!!pending.current} onChange={e=>setText(e.target.value)} placeholder="احچي عن الفكرة، الشخصيات، أو الأحداث…"/><button type="submit" aria-label={pending.current?'تحقق من إرسال الرسالة':'إرسال رسالة الفيلم'} disabled={busy||working||!cloud?.connected||!state.configured||!text.trim()||(!pending.current&&(!wallet||wallet.availableMicros<=0))}><Send size={20}/></button></form>{error&&<div className="film-turn-error" role="alert">{error}{pending.current&&<small>زر الإرسال يتحقق من الإرسال نفسه؛ لا ينشئ رسالة ثانية.</small>}</div>}{!state.configured&&<p className="studio-error">مساعد المناقشة غير متاح حاليًا.</p>}<p className="film-chat-note">المناقشة لا تبدأ الإنتاج. سنعرض كلفة الحلقة ونطلب موافقتك قبل إنتاجها.</p></div><aside className="film-summary studio-panel"><span className="studio-kicker"><CheckCircle2 size={14}/> ما اتفقنا عليه</span><h2>ملخص الحكاية</h2><p className="film-brief">{state.project.brief||'سيظهر هنا ملخص القرارات بعد أول رد: الأسلوب، الشخصيات، الأحداث والمدة. كل قرار يبقى قابلًا للنقاش.'}</p><AiWallet/><div className="film-clean"><FilmClean/> <span>فيلم دون كتابة أو شعار فوق الصورة.</span></div></aside></div>;
}
function FilmClean(){return <Clapperboard size={18}/>}
