type Row={key:string;blob:Blob;used:number};
const LIMIT=200*1024*1024,TTL=7*24*60*60*1000;
function open():Promise<IDBDatabase>{return new Promise((resolve,reject)=>{const r=indexedDB.open('mashhad-media-cache',1);r.onupgradeneeded=()=>r.result.createObjectStore('files',{keyPath:'key'});r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)})}
async function transaction<T>(mode:IDBTransactionMode,task:(store:IDBObjectStore)=>IDBRequest<T>):Promise<T>{const db=await open();try{return await new Promise<T>((resolve,reject)=>{const tx=db.transaction('files',mode),r=task(tx.objectStore('files'));let value:T;r.onsuccess=()=>{value=r.result};tx.oncomplete=()=>resolve(value);tx.onerror=()=>reject(tx.error);tx.onabort=()=>reject(tx.error)})}finally{db.close()}}
// Optional optimization: quota/private browsing failures never block playback.
export async function forgetMedia(key:string){try{await transaction('readwrite',s=>s.delete(key))}catch{/* cache unavailable */}}
export function clearMediaScope(scope:string){writes=writes.then(async()=>{try{const rows=await transaction<Row[]>('readonly',s=>s.getAll());for(const row of rows)if(row.key.startsWith(`${scope}:`))await forgetMedia(row.key)}catch{/* cache unavailable */}});return writes}
export async function readMedia(key:string,size:number,type:string){try{const row=await transaction<Row|undefined>('readonly',s=>s.get(key));if(!row)return null;if(Date.now()-row.used>TTL||row.blob.size!==size||row.blob.type!==type){await forgetMedia(key);return null}void transaction('readwrite',s=>s.put({...row,used:Date.now()})).catch(()=>{});return row.blob}catch{return null}}
let writes=Promise.resolve();
export function writeMedia(key:string,blob:Blob){writes=writes.then(async()=>{if(blob.size>LIMIT)return;try{const rows=await transaction<Row[]>('readonly',s=>s.getAll());let bytes=rows.filter(r=>r.key!==key).reduce((n,r)=>n+r.blob.size,0)+blob.size;for(const row of rows.sort((a,b)=>a.used-b.used)){if(row.key===key)continue;if(bytes<=LIMIT&&Date.now()-row.used<=TTL)continue;await forgetMedia(row.key);bytes-=row.blob.size}await transaction('readwrite',s=>s.put({key,blob,used:Date.now()}))}catch{/* network result remains usable */}});return writes}
