import {useEffect,useRef,useState} from 'react';
import {useMutation,useQuery} from 'convex/react';
import {api} from '../convex/_generated/api';
import type {Id} from '../convex/_generated/dataModel';
import {pipelineStages,clipStages,defaultTemplate,type FlowOption,type Template} from '../shared/pipeline';
import {canonical,exportPhases} from '../shared/editing';
import type {AdForm} from './data';
import {cloudError,useCloud} from './cloud';
export interface Choice{option:FlowOption;template:Template;count:number}
export function GenerationPlan({form,count,logo,opaque,value,onChange}:{form:AdForm;count:number;logo:boolean;opaque:boolean|null;value:Choice|null;onChange:(v:Choice)=>void}){const cloud=useCloud();return cloud?<PlanReady {...{form,count,logo,opaque,value,onChange}}/>:null;}
function PlanReady({form,count,logo,opaque,value,onChange}:{form:AdForm;count:number;logo:boolean;opaque:boolean|null;value:Choice|null;onChange:(v:Choice)=>void}){
 const worker=useQuery(api.pipeline.worker),[now,setNow]=useState(Date.now());useEffect(()=>{const t=setInterval(()=>setNow(Date.now()),5000);return()=>clearInterval(t)},[]);
 const list=worker?.options.filter(o=>o.model===form.model&&o.aspect===form.aspect)??[];const first=list[0],signature=first?canonical(first):'';const callback=useRef(onChange),formSnapshot=useRef(form);useEffect(()=>{callback.current=onChange;formSnapshot.current=form},[onChange,form]);
 useEffect(()=>{if(signature){const option=JSON.parse(signature) as FlowOption;callback.current({option,count:1,template:defaultTemplate({...formSnapshot.current,duration:option.seconds},logoSnapshot.current)});}},[signature]);
 const readyLogo=logo&&opaque===false;const logoSnapshot=useRef(readyLogo),choiceSnapshot=useRef(value);useEffect(()=>{logoSnapshot.current=readyLogo;choiceSnapshot.current=value},[readyLogo,value]);
 useEffect(()=>{const current=choiceSnapshot.current;if(current&&current.template.logo.enabled!==readyLogo)callback.current({...current,template:{...current.template,logo:{...current.template.logo,enabled:readyLogo}}});},[readyLogo]);
 const current=list.find(o=>canonical(o)===canonical(value?.option));const template=value?.template??defaultTemplate(form);const online=worker&&now-worker.seenAt<30000&&worker.state==='online',fresh=worker&&now-worker.observedAt<3600000;
 const choose=(option:FlowOption,n=count,t=template)=>onChange({option,count:n,template:{...t,aspect:form.aspect as '9:16'|'16:9',logo:{...t.logo,end:option.seconds!==value?.option.seconds||n!==value?.count?option.seconds*n:t.logo.end}}});
 return <section className="card generation-plan"><h2>ملخص التفويض والتصدير</h2><p className={online?'online':'offline'}>{online?'Worker متصل؛ يستقبل تفويض زر التوليد تلقائيًا':'Worker غير جاهز للتوليد؛ يبقى الطلب بانتظار اتصال صالح'}</p>{worker?.error&&<p className="warning">{worker.error}</p>}{!fresh||!list.length?<p className="notice">لا توجد خيارات وكلفة متحققة حديثًا لهذا الموديل والمقاس. شغّل worker:start وافتح مشروع Flow. لا يمكن بدء توليد بسعر أو مدة مفترضين.</p>:<><label>الخيار المتاح فعليًا<select value={current?canonical(current):''} onChange={e=>choose(JSON.parse(e.target.value) as FlowOption)}>{list.map(o=><option key={canonical(o)} value={canonical(o)}>{o.actualModel} · {o.resolution} · {o.seconds} ث · {o.cost} نقطة متوقعة للمقطع</option>)}</select></label>{current&&<><div className="duration spaced"><button type="button" disabled={count<=1} onClick={()=>choose(current,count-1)}>−</button><strong>{current.seconds*count} ثانية</strong><button type="button" aria-label="إضافة مقطع" disabled={(count+1)*current.seconds>180||count>=20} onClick={()=>choose(current,count+1)}>+</button></div><p>{count} مقطع مختلف × {current.seconds} ث، نتيجة واحدة لكل مقطع، ثم دمج في إعلان واحد. الكلفة المتوقعة: <strong>{current.cost*count}</strong> نقطة؛ الاستهلاك الفعلي غير معروف.</p><p>دقة المصدر المطلوبة {current.resolution}؛ دقة التصدير {template.width===720?'720p':'360p'}. تكبير الأبعاد لا يحسّن تفاصيل المصدر.</p></>}
 <p className="optional">{template.logo.enabled?"الشعار جاهز وسيُركّب أثناء المونتاج.":"دون شعار."} إعدادات الشعار والنصوص جاهزة؛ يمكنك تخصيصها من الإعدادات المتقدمة.</p><details className="advanced"><summary>إعدادات متقدمة</summary><div className="fields"><label>ملاءمة المصدر<select value={template.fit} onChange={e=>current&&choose(current,count,{...template,fit:e.target.value as Template['fit']})}><option value="contain">احتواء دون تشويه</option><option value="crop">قص لملء الشاشة</option></select></label><label>دقة التصدير<select value={template.width} onChange={e=>current&&choose(current,count,{...template,width:Number(e.target.value) as 360|720})}><option value={720}>720p</option><option value={360}>360p</option></select></label><label><span><input type="checkbox" checked={template.logo.enabled} disabled={(!logo||opaque!==false)&&!template.logo.enabled} onChange={e=>current&&choose(current,count,{...template,logo:{...template.logo,enabled:e.target.checked}})}/> تركيب الشعار الشفاف</span></label><label>حجم الشعار %<input type="number" min={5} max={35} value={template.logo.size} onChange={e=>current&&choose(current,count,{...template,logo:{...template.logo,size:e.target.valueAsNumber}})}/></label><label>بداية ظهور الشعار (ث)<input type="number" min={0} max={form.duration} value={template.logo.start} onChange={e=>current&&choose(current,count,{...template,logo:{...template.logo,start:e.target.valueAsNumber}})}/></label><label>نهاية ظهور الشعار (ث)<input type="number" min={0} max={form.duration} value={template.logo.end} onChange={e=>current&&choose(current,count,{...template,logo:{...template.logo,end:e.target.valueAsNumber}})}/></label><label>موضع الشعار<select value={template.logo.position} onChange={e=>current&&choose(current,count,{...template,logo:{...template.logo,position:e.target.value as Template['logo']['position']}})}>{['top-right','top-left','bottom-right','bottom-left'].map((p,i)=><option key={p} value={p}>{['أعلى يمين','أعلى يسار','أسفل يمين','أسفل يسار'][i]}</option>)}</select></label>{(['name','address','phone'] as const).map((key,i)=><label key={key}><span><input type="checkbox" checked={template.text[key]} onChange={e=>current&&choose(current,count,{...template,text:{...template.text,[key]:e.target.checked}})}/> {['اسم المحل','العنوان','رقم الهاتف'][i]}</span></label>)}<label>موضع النص<select value={template.text.position} onChange={e=>current&&choose(current,count,{...template,text:{...template.text,position:e.target.value as 'top'|'bottom'}})}><option value="bottom">أسفل</option><option value="top">أعلى</option></select></label><label>لون النص<input type="color" value={template.text.color} onChange={e=>current&&choose(current,count,{...template,text:{...template.text,color:e.target.value}})}/></label><label>خلفية النص<input type="color" value={template.text.background} onChange={e=>current&&choose(current,count,{...template,text:{...template.text,background:e.target.value}})}/></label></div></details>
 {logo&&opaque!==false&&<p className="warning">تركيب الشعار معطّل حتى التحقق من بكسلات شفافة حقيقية. يمكنك استبداله أو التصدير دون شعار.</p>}<div className="settings-preview" style={{color:template.text.color,background:template.text.background,padding:16,borderRadius:12}}><small>معاينة النصوص؛ هذه ليست نتيجة فيديو</small>{template.text.name&&<p>{form.name||'اسم المحل'}</p>}{template.text.address&&<p>{form.address||'العنوان'}</p>}{template.text.phone&&<p dir="ltr">{form.phone||'07700000000'}</p>}</div><p className="optional">ضغطة «توليد الإعلان» تفوّض هذه الخطة وحدها، وتشمل كلفة كل مقاطعها. لا موافقة أدمن إضافية. الخيارات قُرئت: {new Date(worker!.observedAt).toLocaleString('ar-IQ')}.</p></> }</section>;
}
export function Pipeline(){const cloud=useCloud();return cloud?.selected?<PipelineReady requestId={cloud.selected._id}/>:null;}
function PipelineReady({requestId}:{requestId:Id<'requests'>}){
 const cloud=useCloud()!,jobs=useQuery(api.pipeline.state,{requestId}),worker=useQuery(api.pipeline.worker),edits=useQuery(api.editing.state,{requestId});const stop=useMutation(api.pipeline.stop),resume=useMutation(api.pipeline.resume),existing=useMutation(api.pipeline.assembleExisting),authorize=useMutation(api.pipeline.authorize);const [busy,setBusy]=useState(false),[error,setError]=useState(''),[now,setNow]=useState(Date.now());const lock=useRef(false);
 useEffect(()=>{const timer=setInterval(()=>setNow(Date.now()),5000);return()=>clearInterval(timer)},[]);const job=jobs?.[0],online=worker&&now-worker.seenAt<30000&&worker.state!=='offline';
 async function act(fn:()=>Promise<unknown>){if(lock.current)return;lock.current=true;setBusy(true);setError('');try{await fn();}catch(e){setError(cloudError(e))}finally{lock.current=false;setBusy(false)}}
 const final=jobs?.find(j=>j.finalId),output=edits?.exports.find(e=>e.status==='completed'&&e.fileId),exporting=edits?.exports.find(e=>e._id===job?.exportId);const option=worker?.options.find(o=>job&&o.model===job.option.model&&o.aspect===job.option.aspect&&o.seconds===job.option.seconds&&o.resolution===job.option.resolution);const active=job&&!job.paused&&job.stage!=='completed';
 return <section id="pipeline" className="card cloud-preview"><h2>التشغيل الكامل</h2><p className={online?'online':'offline'}>{worker===undefined?'جارٍ فحص اتصال Worker…':online?`Worker متصل · ${worker.state==='online'?'Flow جاهز':'قراءة Flow أو تسجيل الدخول يحتاج متابعة؛ المونتاج مستقل'}`:'Worker متوقف؛ لا يعني حفظ الطلب بدء التوليد'}</p><p>معرّف الطلب: <code dir="ltr">{requestId}</code></p>{jobs===undefined?<p>جارٍ تحميل حالة التشغيل…</p>:job?<><p><strong>{pipelineStages[job.stage]}</strong> · معرّف التشغيل: <code dir="ltr">{job._id}</code></p><p>المطلوب {job.form.duration} ث · {job.clips.length} مقطع · {job.option.actualModel} · {job.option.resolution}. المتوقّع {job.mode==='existing'?0:job.option.cost*job.clips.length} نقطة؛ الفعلي غير معروف.</p><ol>{job.clips.map(c=><li key={c.index}>المقطع {c.index+1}: {clipStages[c.state]} {c.duration!==undefined&&`· الفعلي ${c.duration.toFixed(3)} ث`}{c.assetId&&<> · المهمة <code dir="ltr">{c.assetId}</code></>}{c.projectPath&&<details><summary>معرّف مشروع المصدر وخطة المقطع</summary><code dir="ltr">{c.projectPath}</code><p>{c.prompt}</p></details>}</li>)}</ol>{exporting&&<p>المونتاج: {exportPhases[exporting.status]} {exporting.percent!==undefined&&`· ${exporting.percent}%`}</p>}{job.error&&<p role="alert" className="notice error">{job.error}</p>}<div className="submit-row"><button type="button" disabled={busy||!active} onClick={()=>void act(()=>stop({jobId:job._id}))}>إيقاف الخطوات اللاحقة</button><button type="button" disabled={busy||!job.paused} onClick={()=>void act(()=>resume({jobId:job._id}))}>استئناف الأصل دون إعادة توليد</button>{!active&&job.mode==='generate'&&option&&<button type="button" disabled={busy||now-(worker?.observedAt??0)>3600000} onClick={()=>void act(()=>authorize({requestId,key:`regenerate-${crypto.randomUUID()}`,option,count:job.clips.length,template:job.template}))}>تفويض توليد جديد · {option.cost*job.clips.length} نقطة متوقعة</button>}</div><p className="warning">الإيقاف يمنع الخطوات اللاحقة، ولا يضمن إلغاء مهمة أُرسلت إلى Flow أو استرجاع نقاطها. الاستئناف يسترجع المهمة الأصلية؛ الإرسال غير المحسوم لا يُرسل تلقائيًا مرة أخرى.</p></>:<p>هذا الطلب لم يحصل على تفويض توليد من زر الواجهة. الطلبات القديمة لا تُشغّل تلقائيًا.</p>}
 {!!cloud.selected?.results?.length&&<button type="button" disabled={busy||!!active} onClick={()=>void act(()=>{const settings=edits?.edit?.settings;const template:Template=settings?{aspect:cloud.selected!.form.aspect as '9:16'|'16:9',fit:settings.fit,width:settings.width,logo:settings.logo,text:settings.text}:defaultTemplate(cloud.selected!.form);const snapshot=canonical(template);const cached=JSON.parse(localStorage.getItem(`existing-pipeline-v5-${requestId}`)??'null') as {snapshot:string;key:string}|null;const key=cached?.snapshot===snapshot?cached.key:`existing-${crypto.randomUUID()}`;localStorage.setItem(`existing-pipeline-v5-${requestId}`,JSON.stringify({snapshot,key}));return existing({requestId,key,template})})}>إكمال من المقاطع الحالية دون توليد أو نقاط</button>}{error&&<p role="alert" className="notice error">{error}</p>}
 {(output?.fileId??final?.finalId)&&<FinalVideo id={(output?.fileId??final?.finalId)!} label={`${output?.media?.duration.toFixed(3)??'غير معروف'} ث · ${output?.media?.width??'?'}×${output?.media?.height??'?'} · ${output?.media?.size??'?'} بايت · المصدر ${output?.media?.sources.map(s=>`${s.width}×${s.height}`).join('، ')??'غير معروف'}`}/>}<p><a href="#cloud-preview">الرجوع إلى المقاطع الأصلية</a> · <a href="#montage">تعديل إعدادات المونتاج وإعادة التصدير دون توليد</a></p></section>;
}
function FinalVideo({id,label}:{id:Id<'_storage'>;label:string}){const cloud=useCloud()!,loader=useRef(cloud.getFile),[url,setUrl]=useState(''),[error,setError]=useState('');useEffect(()=>{loader.current=cloud.getFile},[cloud.getFile]);useEffect(()=>{const abort=new AbortController();let u='';setUrl('');setError('');loader.current(id,abort.signal).then(blob=>{if(!abort.signal.aborted){u=URL.createObjectURL(blob);setUrl(u)}}).catch(e=>{if(!abort.signal.aborted)setError(cloudError(e))});return()=>{abort.abort();if(u)URL.revokeObjectURL(u)}},[id]);return <div><h3>الإعلان النهائي</h3><p>{label}</p>{url?<><video src={url} controls playsInline preload="metadata"/><a className="download" href={url} download="mashhad-final.mp4">تحميل الإعلان النهائي</a></>:<p>{error||'جارٍ تحميل الإعلان المحمي…'}</p>}</div>}
