import {useEffect,useRef,useState} from 'react';
import {Camera,Upload,X,Check,MapPin,Building2} from 'lucide-react';
import {useMutation} from 'convex/react';
import {api} from '../convex/_generated/api';
import type {Id} from '../convex/_generated/dataModel';
import {cloudError,useCloud} from './cloud';
import {useMedia} from './studio-media';
import {photoDirections,forAspect,imageGuide,type PhotoAspect,type PhotoNotes} from '../shared/place-photos';
export {forAspect,imageGuide};
export type {PhotoAspect};
export type PlaceReference={slot:number;aspect?:PhotoAspect;storageId:Id<'_storage'>};
export function PlacePhotos({references,onChange,disabled,onError,onBusy,initialAspect,notes,onNotes}:{references:PlaceReference[];onChange:(refs:PlaceReference[])=>void;disabled:boolean;onError:(message:string)=>void;onBusy:(busy:boolean)=>void;initialAspect:PhotoAspect;notes:PhotoNotes;onNotes:(notes:PhotoNotes)=>void}){
 const cloud=useCloud()!,save=useMutation(api.studio.savePhotos),lock=useRef(false),[busySlot,setBusySlot]=useState<number|null>(null),[saving,setSaving]=useState(false),[message,setMessage]=useState('');
 const [aspect,setAspect]=useState<PhotoAspect>(initialAspect),selected=forAspect(references,aspect),notesKey=aspect==='9:16'?'portrait':'landscape';
 useEffect(()=>{onBusy(busySlot!==null||saving);return()=>onBusy(false)},[busySlot,saving,onBusy]);
 async function upload(slot:number,file:File){if(lock.current||disabled)return;lock.current=true;setBusySlot(slot);setMessage('');onError('');try{if(file.size>10*1024*1024||!['image/png','image/jpeg','image/webp'].includes(file.type))throw new Error('اختر PNG أو JPG أو WebP حتى 10 MB.');const bitmap=await createImageBitmap(file),valid=aspect==='9:16'?bitmap.height>bitmap.width:bitmap.width>bitmap.height;bitmap.close();if(!valid)throw new Error(`هذه المجموعة تحتاج صورة ${aspect==='9:16'?'عمودية':'أفقية'}. غيّر المجموعة أو ارفع صورة بالمقاس المناسب؛ لا نقصّها تلقائيًا.`);const storageId=await cloud.uploadImage(file);onChange([...references.filter(r=>!(r.slot===slot&&(r.aspect??'9:16')===aspect)),{slot,aspect,storageId}]);setMessage('رُفعت الصورة. اضغط حفظ صور المكان لتثبيت ترتيبها.');}catch(e){onError(cloudError(e))}finally{lock.current=false;setBusySlot(null)}}
 async function store(){if(lock.current||disabled)return;lock.current=true;setSaving(true);setMessage('');onError('');try{await save({references,referenceNotes:notes});setMessage('تم حفظ صور المكان وترتيبها في حسابك.');}catch(e){onError(cloudError(e))}finally{lock.current=false;setSaving(false)}}
 return <section className="place-photos"><span className="studio-kicker">مراجع المكان الحقيقي</span><div className="photo-aspects" role="group" aria-label="مقاس صور المكان">{(['9:16','16:9'] as PhotoAspect[]).map(a=><button type="button" key={a} aria-pressed={aspect===a} disabled={disabled||busySlot!==null||saving} onClick={()=>setAspect(a)}>{a==='9:16'?'عمودي 9:16':'أفقي 16:9'} <small>{forAspect(references,a).length}/8</small></button>)}</div><p>خانات اختيارية؛ صوّر بإضاءة واضحة. تُحفظ الصور الأصلية دون حذف أو تعديل.</p>{['صور الشارع والواجهة','صور داخل المحل أو الشركة'].map((title,group)=><details className="photo-group" key={title}><summary>{group===0?<MapPin size={17}/>:<Building2 size={17}/>}<span>{title}</span><small>{selected.filter(r=>Math.floor(r.slot/4)===group).length}/4</small></summary><div className="photo-slots">{Array.from({length:4},(_,i)=>{const slot=group*4+i;return <PhotoSlot key={slot} slot={slot} storageId={selected.find(r=>r.slot===slot)?.storageId} disabled={disabled||busySlot!==null||saving} loading={busySlot===slot} onUpload={file=>void upload(slot,file)} onRemove={()=>{onChange(references.filter(r=>!(r.slot===slot&&(r.aspect??'9:16')===aspect)));setMessage('أُزيل الربط من الإعدادات؛ اضغط حفظ لتثبيته. الصورة الأصلية لم تُحذف.')}}/>})}</div></details>)}<div className="image-guide"><strong>وصف الصور للموديل — {aspect==='9:16'?'عمودي':'أفقي'}</strong>{selected.length>0?<p>{imageGuide(references,aspect,{portrait:'',landscape:''})}</p>:<p>يظهر الوصف التلقائي حسب الخانات المعبأة وترتيب الصور.</p>}<label>تعليمات إضافية لصور {aspect==='9:16'?'العمودي':'الأفقي'}<textarea rows={3} maxLength={4000} disabled={disabled||busySlot!==null||saving} placeholder="مثلاً: استخدم الواجهة في افتتاح الإعلان، ثم انتقل إلى داخل المحل…" value={notes[notesKey]} onChange={e=>onNotes({...notes,[notesKey]:e.target.value})}/></label></div><button className="studio-secondary" type="button" disabled={disabled||busySlot!==null||saving} onClick={()=>void store()}><Check size={16}/>{saving?'جارٍ الحفظ…':'حفظ صور المكان'}</button>{message&&<p role="status" className="studio-message">{message}</p>}<small className="studio-fine">استخدام المراجع في Flow يعتمد على وضع الموديل وحدوده؛ يتوقف النظام قبل التوليد إذا لم يقبل الصور.</small></section>;
}
function PhotoSlot({slot,storageId,disabled,loading,onUpload,onRemove}:{slot:number;storageId:Id<'_storage'>|undefined;disabled:boolean;loading:boolean;onUpload:(file:File)=>void;onRemove:()=>void}){const media=useMedia(storageId);return <div className="photo-slot"><div className="photo-slot-title"><b>{slot%4+1}</b><p>{photoDirections[slot]}</p></div>{media.url&&<div className="place-image"><img src={media.url} alt={photoDirections[slot]}/><button type="button" disabled={disabled} aria-label={`إزالة صورة المكان ${slot+1}`} onClick={onRemove}><X size={14}/></button></div>}{media.error&&<p className="studio-error">{media.error}</p>}<div className="photo-buttons"><label><Upload size={14}/>{loading?'جارٍ الرفع…':'رفع صورة'}<input type="file" aria-label={`رفع صورة المكان ${slot+1}`} accept="image/png,image/jpeg,image/webp" disabled={disabled} onChange={e=>{const f=e.target.files?.[0];e.target.value='';if(f)onUpload(f)}}/></label><label><Camera size={14}/>التقاط صورة<input type="file" aria-label={`التقاط صورة المكان ${slot+1}`} accept="image/*" capture="environment" disabled={disabled} onChange={e=>{const f=e.target.files?.[0];e.target.value='';if(f)onUpload(f)}}/></label></div></div>}
