import {useRef,useState} from 'react';
import {useAction,useMutation,useQuery} from 'convex/react';
import {Facebook,Instagram,Link2,Send} from 'lucide-react';
import {api} from '../convex/_generated/api';
import type {Id} from '../convex/_generated/dataModel';
import {socialNames,type SocialPlatform} from '../shared/meta';
import {cloudError} from './cloud';
import './social.css';
import {BufferSettings,BufferPublish} from './buffer';
const phases={preparing:'تجهيز الطلب',processing:'Meta تعالج الفيديو',publishing:'إرسال إلى Meta',accepted:'استلم فيسبوك الفيديو؛ تحقق من اكتمال المعالجة على الصفحة',published:'نُشر على إنستغرام',failed:'تعذر التجهيز',uncertain:'نتيجة الإرسال غير مؤكدة؛ راجع حسابك'};
const callbackMessages:Record<string,string>={connected:'تم جلب حساباتك. اختر وجهة النشر أدناه.',no_accounts:'لم نجد صفحة لديك صلاحية نشر عليها، أو حساب إنستغرام احترافيًا مرتبطًا بصفحة. تحقق من صلاحيات الربط.',failed:'تعذر إكمال الربط. تحقق من إعداد التطبيق والصلاحيات وحاول الربط من جديد.',cancelled:'أُلغيت عملية الربط.',expired:'انتهت مهلة الربط. ابدأ من جديد.'};
const reasonMessages:Record<string,string>={no_pages:'Meta لم تُرجع أي صفحة لهذا التصريح رغم اختيارها. نحتاج التحقق من وصول حسابك للصفحة وصلاحيات دور التطبيق.',no_publish_access:'Meta أعادت صفحة لكن دون صلاحية نشر متاحة لهذا التصريح.',instagram_not_linked:'الصفحة متاحة، لكن لا يوجد حساب إنستغرام احترافي مرتبط بها.',pages_permission_missing:'لم تمنح Meta إذن عرض الصفحات لهذا الحساب. تحقق من دور الحساب في تطبيق مشهد أثناء الاختبار.'};
export function SocialSettings(){const state=useQuery(api.social.state),begin=useAction(api.social.begin),select=useMutation(api.social.select),disconnect=useMutation(api.social.disconnect),[busy,setBusy]=useState(false),[error,setError]=useState('');const lock=useRef(false),message=reasonMessages[new URLSearchParams(window.location.search).get('social_reason')??'']??callbackMessages[new URLSearchParams(window.location.search).get('social')??''];async function run(task:()=>Promise<unknown>){if(lock.current)return;lock.current=true;setBusy(true);setError('');try{await task()}catch(e){setError(cloudError(e))}finally{lock.current=false;setBusy(false)}}async function connect(platform:SocialPlatform){const url=await begin({platform,origin:window.location.origin});window.location.assign(url);}return <section className="social-settings" aria-label="ربط حسابات النشر"><h3><Link2 size={18}/> حسابات النشر</h3><BufferSettings/>{message&&<p role="status" className="studio-message">{message}</p>}{state===undefined?<p role="status">جارٍ تحميل الربط…</p>:<>{(['facebook','instagram'] as const).map(platform=>{const accounts=state.accounts.filter(a=>a.platform===platform);return <div className={`social-card social-${platform}`} key={platform}><div className="social-heading">{platform==='facebook'?<Facebook size={23}/>:<Instagram size={23}/>}<strong>{socialNames[platform]}</strong><span>{accounts.some(a=>a.selected)?'مرتبط':'غير مرتبط'}</span></div><p>{platform==='facebook'?'سجّل بحسابك الشخصي ثم اختر البيج الذي تديره للنشر.':'اربط حساب Business أو Creator المتصل بصفحة فيسبوك.'}</p><button type="button" className="studio-secondary" disabled={busy||!state.configured} onClick={()=>void run(()=>connect(platform))}>{accounts.length?'تحديث الربط':`ربط ${socialNames[platform]}`}</button>{accounts.length>0&&<><label>وجهة النشر<select disabled={busy} value={accounts.find(a=>a.selected)?._id??''} onChange={e=>void run(()=>select({id:e.target.value as Id<'socialAccounts'>}))}><option value="" disabled>اختر الحساب أو الصفحة</option>{accounts.map(a=><option key={a._id} value={a._id}>{a.name}</option>)}</select></label><button type="button" className="social-disconnect" disabled={busy} onClick={()=>void run(()=>disconnect({platform}))}>إلغاء الربط وحذف بياناته</button></>}</div>})}{!state.configured&&<p className="studio-fine">الربط ينتظر تفعيل إعداد تطبيق Meta من الإدارة. لن تظهر عملية ربط وهمية.</p>}</>}{error&&<p className="studio-error" role="alert">{error}</p>}<p className="studio-fine">النشر على البيجات والحسابات الاحترافية فقط. للحساب الشخصي حمّل الفيديو وشاركه بنفسك. لا نشر تلقائي بعد الربط.</p><div className="social-legal"><a href="./privacy.html" target="_blank" rel="noreferrer">سياسة الخصوصية</a><a href="./data-deletion.html" target="_blank" rel="noreferrer">حذف بيانات الربط</a></div></section>}
export function SocialPublish({storageId}:{storageId:Id<'_storage'>}){const state=useQuery(api.social.state),publish=useAction(api.social.publish),[open,setOpen]=useState(false),[accountId,setAccount]=useState(''),[caption,setCaption]=useState(''),[confirmed,setConfirmed]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[postId,setPost]=useState<Id<'socialPosts'>|null>(null),key=useRef<string|null>(null),lock=useRef(false);const accounts=state?.accounts.filter(a=>a.selected)??[],post=state?.posts.find(p=>p._id===postId);async function send(){if(lock.current||!confirmed||!accountId)return;lock.current=true;setBusy(true);setError('');key.current??=crypto.randomUUID();try{setPost(await publish({key:key.current,storageId,accountId:accountId as Id<'socialAccounts'>,caption,confirmed}));}catch(e){setError(cloudError(e))}finally{lock.current=false;setBusy(false)}}return <><BufferPublish storageId={storageId}/><section className="social-publish"><button type="button" className="studio-secondary" onClick={()=>setOpen(v=>!v)} aria-expanded={open}><Send size={17}/>نشر على حساباتي</button>{open&&<div className="social-publish-panel">{accounts.length?<><label>وجهة النشر<select value={accountId} disabled={busy||!!key.current} onChange={e=>{setAccount(e.target.value);setConfirmed(false)}}><option value="">اختر الحساب</option>{accounts.map(a=><option key={a._id} value={a._id}>{socialNames[a.platform]} · {a.name}</option>)}</select></label><label>وصف المنشور<textarea maxLength={2200} value={caption} disabled={busy||!!key.current} onChange={e=>{setCaption(e.target.value);setConfirmed(false)}} rows={3}/></label><small>{caption.length}/2200</small><label className="studio-switch"><input type="checkbox" checked={confirmed} disabled={busy||!!key.current} onChange={e=>setConfirmed(e.target.checked)}/><span>راجعت هذا الفيديو والوصف وأوافق على نشرهما علنًا على الحساب المختار.</span></label><button type="button" className="studio-generate" disabled={busy||!state?.configured||!accountId||!confirmed||!!postId} onClick={()=>void send()}>{busy?'جارٍ تسجيل الطلب…':'أوافق، انشر الفيديو'}</button></>:<p>اربط حسابك واختر وجهة النشر من إعدادات الاستوديو أولًا.</p>}{post&&<p role="status">{phases[post.stage]}{post.providerId&&<> · معرّف Meta: <span dir="ltr">{post.providerId}</span></>}</p>}{post?.error&&<p className="studio-error">{post.error}</p>}{error&&<p role="alert" className="studio-error">{error}</p>}<p className="studio-fine">سيُرسل الفيديو ووصفه إلى Meta. لا توجد إعادة نشر تلقائية إذا انقطع الاتصال. افحص حسابك عند ظهور نتيجة غير مؤكدة.</p></div>}</section></>}
