import {defaultLanguage,spokenLanguage} from '../shared/generation-language';
import {defaultFlowOption} from '../shared/flow-options';
import {useEffect,useRef,useState,type ReactNode} from 'react';
import {useMutation,useQuery} from 'convex/react';
import {useMedia} from './studio-media';
import {ArrowUp,Film,Image,Plus,SlidersHorizontal,Sparkles,X} from 'lucide-react';
import {api} from '../convex/_generated/api';
import type {Id} from '../convex/_generated/dataModel';
import {defaultTemplate,type FlowOption} from '../shared/pipeline';
import {validateFile} from '../shared/validation';
import {cloudError,useCloud} from './cloud';
import {draftRepository,type Draft} from './data';
import {topupUrl} from '../shared/topup';
import {imagePoints} from '../shared/images';
const imageModels=['Nano Banana Pro','Nano Banana 2','Nano Banana 2 Lite'];
const modelNames:Record<string,string>={'Omni Flash':'Omni 1.1 Flash','Veo 3.1 Fast':'Veo 3.1 · Fast','Veo 3.1 Quality':'Veo 3.1 · Quality'};
export function VideoChat({hidden,renderProgress}:{hidden:boolean;renderProgress:(id:Id<'requests'>)=>ReactNode}){
 const imageJobs=useQuery(api.images.list),authorizeImage=useMutation(api.images.authorize);
 const branding=useQuery(api.studio.branding);const cloud=useCloud()!,worker=useQuery(api.pipeline.worker),wallet=useQuery(api.wallets.mine),rates=useQuery(api.wallets.pricing);
 const [kind,setKind]=useState<'video'|'image'>('video'),[prompt,setPrompt]=useState(''),[model,setModel]=useState(cloud.draftScope?'Omni Flash':'Veo 3.1 Fast'),[imageModel,setImageModel]=useState('Nano Banana 2'),[aspect,setAspect]=useState('9:16'),[imageAspect,setImageAspect]=useState('9:16'),[choice,setChoice]=useState<FlowOption|null>(null),[settings,setSettings]=useState(false),[files,setFiles]=useState<File[]>([]),[previews,setPreviews]=useState<string[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState(''),[sent,setSent]=useState(false),[key,setKey]=useState(()=>crypto.randomUUID()),[now,setNow]=useState(Date.now());
 const lock=useRef(false),input=useRef<HTMLInputElement>(null),panel=useRef<HTMLDivElement>(null),trigger=useRef<HTMLButtonElement>(null);
 const options=worker?.options.filter(o=>o.model===model&&o.aspect===aspect)??[],option=options.find(o=>o.resolution===choice?.resolution&&o.seconds===choice?.seconds)??defaultFlowOption(options,!!cloud.draftScope);
 const imageOption=worker?.imageOptions?.find(o=>o.model===imageModel&&o.aspect===imageAspect),imageJob=imageJobs?.find(j=>j.key===`image-${key}`);
 const points=kind==='video'?rates?.find(r=>r.model===option?.model&&r.resolution===option?.resolution&&r.seconds===option?.seconds)?.points:imagePoints(rates?.find(r=>r.model===imageModel&&r.resolution==='original'&&r.seconds===0));
 const fresh=!!worker&&now-(kind==='image'?(worker.imageObservedAt??0):worker.observedAt)<3600000,online=worker?.state==='online'&&now-worker.seenAt<30000,request=cloud.requests?.find(r=>r.key===key),insufficient=wallet!==undefined&&(!wallet||wallet.wallet.balance<=0||points!==undefined&&wallet.wallet.balance<points);
 useEffect(()=>{const timer=setInterval(()=>setNow(Date.now()),5000);return()=>clearInterval(timer)},[]);
 useEffect(()=>{const urls=files.map(f=>URL.createObjectURL(f));setPreviews(urls);return()=>urls.forEach(url=>URL.revokeObjectURL(url))},[files]);
 useEffect(()=>{if(!settings)return;panel.current?.scrollIntoView({block:'nearest'});const click=(e:PointerEvent)=>{if(!panel.current?.contains(e.target as Node)&&!trigger.current?.contains(e.target as Node))setSettings(false)};const keydown=(e:KeyboardEvent)=>{if(e.key==='Escape'){setSettings(false);trigger.current?.focus()}};document.addEventListener('pointerdown',click);document.addEventListener('keydown',keydown);return()=>{document.removeEventListener('pointerdown',click);document.removeEventListener('keydown',keydown)}},[settings]);
 function attach(list:FileList|null){if(!list)return;setError('');try{const next=[...files,...Array.from(list)];if(next.length>8)throw new Error('يمكن إرفاق 8 صور كحد أقصى.');for(const f of next)validateFile(f.type,f.size,'image');setFiles(next)}catch(e){setError(cloudError(e))}}
 async function send(){if(lock.current||sent||busy||cloud.busy)return;lock.current=true;setBusy(true);setError('');try{
  if(kind==='image'){
   if(!prompt.trim()||!imageOption||!fresh)throw new Error('اكتب الوصف وانتظر خيارات الصور الحديثة من Worker.');
   if(insufficient||!wallet?.wallet.enabled)throw new Error('رصيدك غير كافٍ أو محفظتك معطلة.');
   if(!wallet.wallet.models.includes(imageModel))throw new Error('فعّل صلاحية موديل الصور لهذه المحفظة من الأدمن.');
   const referenceIds:Id<'_storage'>[]=[];for(const file of files)referenceIds.push(await cloud.uploadImage(file));
   await authorizeImage({key:`image-${key}`,prompt:prompt.trim(),referenceIds,option:imageOption});setSent(true);setSettings(false);return;
  }if(branding===undefined)throw new Error('انتظر تحميل إعدادات اللغة.');if(!prompt.trim())throw new Error('اكتب وصف الفيديو أولًا.');if(!option||!fresh)throw new Error('خيارات Flow تحتاج تحديثًا من Worker قبل الإرسال.');if(points===undefined||wallet===undefined)throw new Error('انتظر تحميل تسعير المحفظة.');if(insufficient)throw new Error('رصيدك غير كافٍ؛ اشحن حسابك عبر واتساب.');
  const draft:Draft={id:key,createdAt:new Date().toISOString(),updatedAt:new Date().toISOString(),status:'مسودة',clipCount:1,logo:null,references:files,form:{name:prompt.trim().slice(0,80),address:'غير مذكور',phone:'غير مذكور',products:'فيديو من وصفك',prompt:prompt.trim(),instructions:'',model:option.model,aspect:option.aspect,duration:option.seconds,dialect:spokenLanguage(branding?.generationLanguage??defaultLanguage),productionLanguage:'en'}};
  await draftRepository.save(draft);const template=defaultTemplate(draft.form,false);template.width=option.resolution==='360p'?360:720;template.text={...template.text,name:false,address:false,phone:false};await cloud.generate(draft,option,template);setSent(true);setSettings(false);
 }catch(e){setError(cloudError(e))}finally{lock.current=false;setBusy(false)}}
 function newMessage(){setKey(crypto.randomUUID());setSent(false);setPrompt('');setFiles([]);setError('');}
 const frozen=busy||cloud.busy||sent||!!request||!!imageJob;
 return <section hidden={hidden} className="video-chat" aria-label="دردشة فيديو Al">
  {imageJob?<div className="chat-conversation"><div className="chat-user-message"><small>وصف الصورة</small><p>{imageJob.prompt}</p></div><ImageTask job={imageJob}/><button className="studio-secondary" disabled={busy||cloud.busy} onClick={newMessage}><Plus size={16}/>فكرة جديدة</button></div>:request?<div className="chat-conversation"><div className="chat-user-message"><small>وصفك</small><p>{request.form.prompt}</p></div>{renderProgress(request._id)}<button className="studio-secondary" disabled={busy||cloud.busy} onClick={newMessage}><Plus size={16}/>فكرة جديدة</button></div>:<div className="chat-welcome"><div className="chat-emblem"><Sparkles size={36}/></div><span className="studio-kicker">فيديو Al</span><h1>{kind==='video'?'شنو المشهد اللي ببالك؟':'شنو الصورة اللي تتخيلها؟'}</h1><p>اكتب فكرتك، واختر إعداداتك.<br/>{kind==='video'?'نحوّل وصفك إلى فيديو يستحق المشاهدة.':'صورة واحدة من فكرتك، محفوظة وجاهزة للتحميل.'}</p></div>}
  <div className="chat-composer">
   {settings&&<div ref={panel} className="chat-settings" role="region" aria-label="إعدادات الإنشاء"><div className="chat-settings-heading"><strong>إعدادات الإنشاء</strong><button type="button" aria-label="إغلاق إعدادات الإنشاء" onClick={()=>setSettings(false)}><X size={17}/></button></div>
    <div className="chat-segments" aria-label="نوع الإنشاء"><button disabled={frozen} aria-pressed={kind==='video'} onClick={()=>setKind('video')}><Film size={18}/>فيديو</button><button disabled={frozen} aria-pressed={kind==='image'} onClick={()=>setKind('image')}><Image size={18}/>صورة</button></div>
    {kind==='video'&&<p className="chat-mode-note">المكوّنات · الصور المرفقة تستخدم كمراجع للفيديو. الإطارات المتتابعة تبقى ضمن «إعلان Al».</p>}
    <div className="chat-segments chat-aspects" aria-label="نسبة الأبعاد">{(kind==='video'?['9:16','16:9']:['9:16','3:4','1:1','4:3','16:9']).map(value=><button key={value} disabled={frozen} aria-pressed={(kind==='video'?aspect:imageAspect)===value} onClick={()=>{if(kind==='video'){setAspect(value);setChoice(null)}else setImageAspect(value)}}><span className={`aspect-icon ${value==='16:9'||value==='4:3'?'wide':value==='1:1'?'square':''}`}/><b dir="ltr">{value}</b></button>)}</div>
    <label className="chat-model">الموديل<select disabled={frozen} value={kind==='video'?model:imageModel} onChange={e=>{if(kind==='video'){setModel(e.target.value);setChoice(null)}else setImageModel(e.target.value)}}>{kind==='video'?<>{Object.entries(modelNames).map(([value,name])=><option key={value} value={value}>{name}</option>)}<option disabled>Veo 3.1 · Lite — غير مربوط حاليًا</option></>:imageModels.map(name=><option key={name} disabled={!worker?.imageOptions?.some(o=>o.model===name)}>{name}</option>)}</select></label>
    {kind==='video'?<><div className="chat-segments" aria-label="الجودة">{[...new Set(options.map(o=>o.resolution))].map(resolution=><button disabled={frozen} key={resolution} aria-pressed={option?.resolution===resolution} onClick={()=>setChoice(options.find(o=>o.resolution===resolution&&o.seconds===option?.seconds)??options.find(o=>o.resolution===resolution)??null)}>{resolution}</button>)}</div><div className="chat-segments" aria-label="مدة الفيديو">{[...new Set(options.filter(o=>o.resolution===option?.resolution).map(o=>o.seconds))].map(seconds=><button disabled={frozen} key={seconds} aria-pressed={option?.seconds===seconds} onClick={()=>setChoice(options.find(o=>o.seconds===seconds&&o.resolution===option?.resolution)??null)}>{seconds.toLocaleString('en-GB')} ث</button>)}</div>{!options.length&&<p className="chat-mode-note">لا توجد خيارات متحققة لهذا الموديل والمقاس حاليًا.</p>}<p className="chat-cost">{option?`${option.cost.toLocaleString('en-GB')} نقطة Flow متوقعة · ${points?.toLocaleString('en-GB')??'…'} نقطة مشهد`:'الكلفة غير معروفة'}<small>نتيجة واحدة · الاستهلاك الفعلي لا يُفترض مسبقًا.</small></p></>:<p className="chat-cost">{imageOption?`${imageOption.cost.toLocaleString('en-GB')} نقطة Flow متوقعة · ${points?.toLocaleString('en-GB')??'…'} نقطة مشهد`:'1 نقطة مشهد · كلفة Flow بانتظار القراءة'}<small>صورة واحدة · الجودة الأصلية، دون تكبير.</small></p>}
   </div>}
   {!!files.length&&<div className="chat-attachments">{files.map((file,i)=><div key={`${file.name}-${i}`}><img src={previews[i]} alt={`صورة مرجعية ${i+1}`}/><button disabled={frozen} type="button" aria-label={`حذف الصورة ${i+1}`} onClick={()=>setFiles(items=>items.filter((_,index)=>index!==i))}><X size={13}/></button></div>)}</div>}
   <textarea aria-label="وصف فيديو Al" maxLength={10000} rows={3} disabled={frozen} placeholder={kind==='video'?'اكتب وصف الفيديو الذي تريد إنشاءه…':'اكتب وصف الصورة…'} value={prompt} onChange={e=>setPrompt(e.target.value)}/>
   <div className="chat-composer-actions"><input ref={input} hidden type="file" multiple accept="image/png,image/jpeg,image/webp" onChange={e=>{attach(e.target.files);e.target.value=''}}/><button className="chat-attach" disabled={frozen||files.length>=8} aria-label="إرفاق صور مرجعية" onClick={()=>input.current?.click()}><Plus size={21}/></button><button ref={trigger} className="chat-settings-trigger" aria-label="فتح إعدادات الإنشاء" aria-expanded={settings} onClick={()=>setSettings(s=>!s)}><SlidersHorizontal size={17}/><span>{kind==='video'?`${option?.actualModel??modelNames[model]} · ${option?.resolution??'…'} · ${option?.seconds??'…'} ث`:`صورة · ${imageModel}`}</span><b dir="ltr">{kind==='video'?aspect:imageAspect}</b></button><button className="chat-send" aria-label={kind==='image'?'توليد صورة Al':'توليد فيديو Al'} disabled={busy||cloud.busy||sent||!prompt.trim()||(kind==='video'?!option:!imageOption)||!fresh||points===undefined||wallet===undefined} onClick={()=>void send()}><ArrowUp size={21}/></button></div>
  </div>
  {error&&<p className="studio-error" role="alert">{error}</p>}{insufficient&&<p className="chat-footnote">رصيدك غير كافٍ. <a href={topupUrl(wallet?.wallet.publicId)} target="_blank" rel="noopener noreferrer">اشحن عبر واتساب</a></p>}
  <p className="chat-footnote">{online?'Worker متصل':'بانتظار اتصال Worker'} · {kind==='image'?imageOption?.cost??'…':option?.cost??'…'} نقطة Flow متوقعة · {points??'…'} نقطة مشهد · {kind==='image'?'صورة واحدة.':'ضغطة الإرسال تفوّض فيديو واحدًا.'} {!fresh&&'خيارات Flow تحتاج تحديثًا.'}{kind==='image'&&wallet&&!wallet.wallet.models.includes(imageModel)&&' فعّل صلاحية موديل الصور من الأدمن أولًا.'}</p>
 </section>;
}






type ImageJob=import('../convex/_generated/dataModel').Doc<'imageJobs'>;
const imageStatuses:Record<string,string>={queued:'بانتظار التشغيل',generating:'توليد الصورة',downloading:'تنزيل الصورة',uploading:'رفع الصورة',completed:'مكتمل',failed:'فشل',login:'يحتاج تسجيل دخول',uncertain:'النتيجة غير محسومة',stopped:'متوقف'};
function ImageTask({job}:{job:ImageJob}){const stop=useMutation(api.images.stop),resume=useMutation(api.images.resume),media=useMedia(job.fileId),[error,setError]=useState(''),[busy,setBusy]=useState(false);async function act(fn:()=>Promise<unknown>){if(busy)return;setBusy(true);setError('');try{await fn()}catch(e){setError(cloudError(e))}finally{setBusy(false)}}return <div className="studio-panel image-task"><span className="studio-kicker">{imageStatuses[job.status]??job.status}</span><h2>{job.status==='completed'?'صورتك جاهزة':'نتابع صورتك خطوة بخطوة'}</h2>{media.url&&<><a href={media.url} target="_blank" rel="noopener noreferrer"><img src={media.url} alt={job.prompt}/></a><p>{job.width} × {job.height} · {job.size?`${(job.size/1024/1024).toFixed(2)} MB`:''}</p><a className="studio-generate" href={media.url} download={`mashhad-${job._id}.${job.fileType==='image/jpeg'?'jpg':job.fileType==='image/webp'?'webp':'png'}`}>تحميل الصورة</a></>}<p>{job.option.model} · <b dir="ltr">{job.option.aspect}</b> · {job.option.cost} نقطة Flow متوقعة</p><small>نقاط مشهد للطلب: {job.points} · الاستهلاك الفعلي في Flow غير مؤكد.</small><details className="task-details"><summary>تفاصيل المهمة</summary><code>{job._id}</code>{job.assetId&&<code>{job.assetId}</code>}</details>{(job.error||error||media.error)&&<p className="studio-error" role="alert">{error||job.error||media.error}</p>}{job.status!=='completed'&&<><div className="task-actions"><button disabled={busy||job.paused} onClick={()=>void act(()=>stop({jobId:job._id}))}>إيقاف الخطوات اللاحقة</button>{job.paused&&<button disabled={busy} onClick={()=>void act(()=>resume({jobId:job._id}))}>استئناف المهمة الأصلية</button>}</div><small>الإيقاف لا يضمن إلغاء مهمة Flow أو استرجاع نقاطها. الاستئناف لا يعيد التوليد.</small></>}</div>;}
export function ImageGallery(){const jobs=useQuery(api.images.list),[opened,setOpened]=useState<ImageJob|null>(null);const complete=jobs?.filter(j=>j.status==='completed'&&j.fileId)??[];return <>{complete.length>0&&<><div className="gallery-heading"><h2>صوري</h2><span>{complete.length.toLocaleString('en-GB')} صورة</span></div><div className="video-grid">{complete.map(job=><ImageCard key={job._id} job={job} onOpen={()=>setOpened(job)}/>)}</div></>}{!!jobs?.some(j=>j.status!=='completed')&&<details className="saved-jobs"><summary>طلبات الصور قيد التنفيذ أو تحتاج متابعة</summary>{jobs.filter(j=>j.status!=='completed').map(j=><button key={j._id} onClick={()=>setOpened(j)}><span>{j.prompt.slice(0,60)}</span><small>{imageStatuses[j.status]}</small></button>)}</details>}{opened&&<div className="studio-backdrop"><section className="studio-dialog" role="dialog" aria-modal="true" aria-label="معاينة الصورة"><div className="dialog-heading"><h2>الصورة</h2><button className="studio-icon" aria-label="إغلاق الصورة" onClick={()=>setOpened(null)}><X size={20}/></button></div><ImageTask job={jobs?.find(j=>j._id===opened._id)??opened}/></section></div>}</>;}
function ImageCard({job,onOpen}:{job:ImageJob;onOpen:()=>void}){const media=useMedia(job.fileId);return <button className="video-tile" onClick={onOpen} aria-label={`فتح صورة ${job.prompt.slice(0,60)}`}><div className="tile-picture">{media.url?<img className="image-tile-picture" src={media.url} alt={job.prompt}/>:<Image size={30}/>}</div><div className="tile-caption"><strong>{job.prompt}</strong><small>{job.option.model} · {new Date(job.createdAt).toLocaleDateString('en-GB')}</small></div></button>;}
