import {AiWallet} from './ai-wallet';
import {useState} from 'react';
import {useQuery} from 'convex/react';
import {api} from '../convex/_generated/api';
import {Wallet,Copy,Plus} from 'lucide-react';
import {topupUrl,topupPhone} from '../shared/topup';
export function MyWallet(){
 const data=useQuery(api.wallets.mine),[expanded,setExpanded]=useState(false),[points,setPoints]=useState(''),[message,setMessage]=useState('');
 return <section className="my-wallet"><div className="wallet-art"><Wallet size={30}/></div><h2>محفظتي</h2>{!data?<p>جارٍ تجهيز المحفظة…</p>:<><div className="wallet-balance"><strong dir="ltr">{data.wallet.balance.toLocaleString('en-GB')}</strong><span>نقطة</span></div><div className="wallet-id"><small>معرّف حسابك للشحن</small><code>{data.wallet.publicId}</code><button className="studio-secondary" onClick={()=>void navigator.clipboard.writeText(data.wallet.publicId).then(()=>setMessage('نُسخ معرّف حسابك.')).catch(()=>setMessage('انسخ المعرّف يدويًا.'))}><Copy size={15}/>نسخ ID</button></div><div className="wallet-topup"><button type="button" className="studio-secondary" aria-expanded={expanded} onClick={()=>setExpanded(x=>!x)}><Plus size={16}/>شحن الرصيد</button>{expanded&&<><label>عدد النقاط المطلوب<input type="number" dir="ltr" min="1" max="1000000" step="1" value={points} onChange={e=>setPoints(e.target.value)} placeholder="مثلاً 100"/></label><p>أرسل معرّفك عبر واتساب لنضيف الرصيد إلى حسابك.</p><a className="studio-generate" href={topupUrl(data.wallet.publicId,Number(points))} target="_blank" rel="noopener noreferrer">طلب الشحن عبر واتساب <b dir="ltr">{topupPhone}</b></a></>}</div><details className="saved-jobs"><summary>سجل رصيدي</summary>{data.ledger.map((e,i)=><div className="wallet-entry" key={i}><strong dir="ltr">{e.amount>0?'+':''}{e.amount.toLocaleString('en-GB')}</strong><div><p>{e.note}</p><small>{new Date(e.createdAt).toLocaleString('en-GB')} · الرصيد {e.balanceAfter.toLocaleString('en-GB')}</small></div></div>)}</details></>}<AiWallet/>{message&&<p role="status" className="studio-message">{message}</p>}</section>;
}
